### ISSUE TITLE
dev: Use actuall contract class hash for the genesis ones

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1049]
As you can see here: https://github.com/keep-starknet-strange/madara/blob/main/docs/genesis.md#contract-classes-node-genesis, and in the code, some of the contracts we deploy during the genesis step of the chain have funky ClassHash (`0x1000`, `0x90000`, etc).

Those are not the result of a regular hash computation based on their class code. We set those arbitrary values manually because it was easier at the time.

This had to change. Your mission will be to compute the actual class of those contracts, in the canon starknet way, and modify code and documentation in order to use those new, actual class hashes

**Comment by ayushtom** [comment]
I can pick this
