### ISSUE TITLE
feat: add ABI to contract class ✨

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#105]
# Feature Request

**Describe the Feature Request**

The ABI should be read from the compiled contract when declaring a new contract class.

**Describe Preferred Solution**

Should be done in a similar fashion as `program` and `entry_points_by_type`.
Once implemented `// TODO: Uncomment once we have ABI support` can be uncommented.

Some thinking should be put into the "why" of this issue, what should the ABI be used for. 
For example :
- Sequencer contract verification 
- Explorer

**Comment by Cheelax** [comment]
Hey @EvolveArt glad to help on this one. just not sure on where do we find the "compiled contract".
Can you give some advices? Thank you !

**Comment by EvolveArt** [comment]
> Hey @EvolveArt glad to help on this one. just not sure on where do we find the "compiled contract". Can you give some advices? Thank you !

Thank you for your help! Compiled contracts can be found under the `ressources` folder for now as `.json` files.
You can see that we load them in tests when using `get_contract_class(include_bytes!({path}))`
