### ISSUE TITLE
add a BTreeMap conversion step in cairo-rs

### ISSUE THREAD

**Issue by lana-shanghai** [keep-starknet-strange/madara#1054]
This issue is a sub-issue of [this one](https://github.com/keep-starknet-strange/madara/issues/907). 

Please look at the example [PR](https://github.com/keep-starknet-strange/blockifier/pull/11) here, and add an extra `HashMap` to `BTreeMap` conversion step in the `cairo-rs` repo. This ensures that when we encode and decode the map, we will always get the same result. 

The same conversion needs to be done in [this branch](https://github.com/keep-starknet-strange/cairo-rs/tree/no_std-support-21eff70) of `cairo-rs` for `HashMap` values that are encoded for the madara runtime, which is `no-std`. The [Cargo.toml](https://github.com/keep-starknet-strange/madara/blob/main/Cargo.toml#L130) in Madara points to this branch. 

The structs that have fields with `HashMap` and that have a manual encode / decode implementation are `Identifier`, `Program`, `FlowTrackingData`, `SharedProgramData` and `ExecutionResources`. Add the extra conversion step to the corresponding field of each in the manual `Encode` and `Decode` impl, and check if there are other structs that may need the conversion.

**Comment by MdTeach** [comment]
Can I take this ?

**Comment by lana-shanghai** [comment]
@MdTeach please, go ahead!

**Comment by MdTeach** [comment]
@lana-shanghai I've raised the pr [here](https://github.com/keep-starknet-strange/cairo-rs/pull/9)

**Comment by MdTeach** [comment]
@lana-shanghai do you think this issue is still required ?

As, the [pr](https://github.com/keep-starknet-strange/cairo-rs/pull/9)  is merged by @tdelabro.
So, I think you can close this issue.
