### ISSUE TITLE
test: remove `#[ignore]` in starknet-rpc-test/{get_class,get_class_at}.rs when refactoring is done.

### ISSUE THREAD

**Issue by ptisserand** [keep-starknet-strange/madara#1056]
`work_ok_retrieving_class_for_contract_version_1` test depends on #992 which should fixed issue related to sierra program storage.

Once #992 is merged, this test should be reenabled to ensure RPC endpoint is working correctly.

**Comment by ptisserand** [comment]
Update also needed in `starknet-rpc-test/get_class.rs`

**Comment by dhirajs0** [comment]
after removing the [#ignore], getting panic in work_ok_retrieving_class_for_contract_version_1 in starknet-rpc-test/get_class.rs.
Though no issue in starknet-rpc-test/get_class_at.rs 
So, I closed the PR. Sorry

**Comment by hhamud** [comment]
@apoorvsadana can you assign me this one?

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
