### ISSUE TITLE
feat: Nonce Verification 🎱

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#107]
# Feature Request

**Describe the Feature Request**

Upon each transaction, the nonce should verified and ensured to be followed sequentially for each account address.

**Describe Preferred Solution**

One can simply take inspiration from the blockifier [implementation](https://github.com/tdelabro/blockifier/blob/no_std-support/crates/blockifier/src/transaction/account_transaction.rs#LL115C5-L133C6).

**Comment by chirag-bgh** [comment]
I can take this.

**Comment by EvolveArt** [comment]
not stale
