### ISSUE TITLE
dev: increase threshold for codecov to 1%

### ISSUE THREAD

**Issue by kasteph** [keep-starknet-strange/madara#1072]
I have noticed that some commits fail the CI because code coverage decreases by up to 1%:

- 1729adc39d05b7e40c3e79731a1a0cba52579ba1
- 8ad2a16ac6ebfc7b88314fd6af480d5543d58167
- 9a15dbfb23027f5329be2bb8911b94418e498ea0
- c5a9cbbf238fe07f22fd3c70303c5af82fac2baf
- 8c0eb02448b3c3e9ec8c7d74b0b13120e8a6b78e

If these commits get merged but is failing CI due to codecov, then the check should be more lenient as a ❌ next to the commit signals a failing build.

**Comment by tdelabro** [comment]
It sound like a great idea
