### ISSUE TITLE
dev: impl a braavos tx signer

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1077]
`given_contract_run_deploy_account_braavos_tx_works` is a test in `crates/pallets/starknet/src/tests/deploy_account_tx.rs`

It uses a Braavos account to sign and execute a tx.
Braavos has an unusual way of signing tx. It does not just sign the tx hash, it adds a bunch of stuff around it and then hash it all together and signs the output.

Here is how the Braavos wallet verify the signature: https://github.com/myBraavos/braavos-account-cairo/blob/develop/src/account/library.cairo#L328

Right now we hardcoded the correct value that must be signed for our tx. It would be better if we have a function that would compute this value on the fly.

Maybe some lib already exist that does that. Maybe you will have to code it all yourselve

**Comment by tonypony220** [comment]
Can I take this?

**Comment by tdelabro** [comment]
sure ! Wish you best luck !

**Comment by tdelabro** [comment]
I think #1131 did. We will be merging it soon (waiting for another PR to be merged in main first)
@EvolveArt do you think we should keep waiting for Code Coverage?
