### ISSUE TITLE
feat: generate and publish state diffs

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/madara#1081]
# Feature Request

In order to function properly as a Validity Rollup, Madara needs to be able to publish to a settlement layer. Hence it needs to generate state diffs.

State diffs are simply the representation of how to go to one state to another state, after apply a given block with a set of transactions.

Learn more about data availability in the [Starknet Data Availability Documentation](https://docs.starknet.io/documentation/architecture_and_concepts/Network_Architecture/on-chain-data/).

**Describe Preferred Solution**

Leverage substrate storage changes mechanism.

As you can see [here](https://github.com/keep-starknet-strange/madara/blob/a6f6554ed3aab76a1836cdaee37e86680bbe74a4/crates/client/block-proposer/src/lib.rs#L310) in the `block-proposer propose_with` function there it seems there is a way to retrieve the storage changes after executing a block:

```rust
let (block, storage_changes, proof) = block_builder.build()?.into_inner();
``` 

From this, there should be a way to determined the storage changes related to the `starknet` pallet. Then we need to construct the state diff following the same format as the public Starknet.

**Describe Alternatives**

Implement from scratch on the client side. Deduce the storage changes from the execution of the block and construct the state diff.

**Comment by tdelabro** [comment]
Wait until we have Bonzai MPT. It should help for this

**Comment by tdelabro** [comment]
Closed by https://github.com/keep-starknet-strange/madara/pull/1217
