### ISSUE TITLE
dev: return deployed contract address in ` get_transaction_receipt` api

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1095]

**Comment by a-moreira** [comment]
@tdelabro I'd like to take this one, although I imagine it needs #992 to be merged first

**Comment by tdelabro** [comment]
Yes exactly. I will ping you when it is merged :)
Thanks a lot

**Comment by tonypony220** [comment]
seems to be available now, isn't it?

**Comment by tdelabro** [comment]
Yes indeed. You want to give it a try?

**Comment by tonypony220** [comment]
@tdelabro Yes, I think to try. 
From first glance it seems that we could get transaction and calculate contract address, but maybe it's not right way.
Also this is related one [#1111](https://github.com/keep-starknet-strange/madara/issues/1111)
