### ISSUE TITLE
dev: update correct UDC class hash  in genesis config

### ISSUE THREAD

**Issue by ayushtom** [keep-starknet-strange/madara#1100]
Problem Description

Current the Universal Deployer Contract with contract address - 0x041a78e741e5af2fec34b695679bc6891742439f7afb8484ecd7766661ad02bf  

has a class hash which is taken from starkscan [here](https://starkscan.co/contract/0x041a78e741e5af2fec34b695679bc6891742439f7afb8484ecd7766661ad02bf#class-code-history)

This classhash isn't generated by us and might affect madara when we connect with other tools where this value needs to be consistent.

Your mission is to generate this class hash from starknet cli using the same compiler version with which this contract has been compiled and update this in the genesis.json and anywhere in the rust code and docs where this value seems to be hardcoded.

**Comment by dbejarano820** [comment]
So generate a new contract instance with the class hash?

**Comment by ayushtom** [comment]
I think you can just recompile and get the class hash. New instance shouldn't be necessary but yea that works too!
Make sure you use starknet-cli version 10.0 to do this otherwise you will get different class hash

**Comment by tdelabro** [comment]
#951 should also fix this one

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
