### ISSUE TITLE
feat: test transaction helper 🧪 

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#111]
# Feature Request

**Describe the Feature Request**

While writing tests for the `starknet` pallet, we have to manually create new transactions by using its constructor `Transaction::new`. This is very cumbersome and affects tests' readability overall.

**Describe Preferred Solution**

- Add a helper function/macro that would generate a `Transaction` object from a json file. 
- Add a `transactions` subfolder in `ressources`.
- Refractor related tests with the helper function.

**Related Code**

- [Example of cumbersome test](https://github.com/keep-starknet-strange/madara/blob/main/crates/pallets/starknet/src/tests.rs#L186)

**Comment by Matth26** [comment]
I'll make a proposal for this one

**Comment by abdelhamidbakhta** [comment]
> I'll make a proposal for this one

could, assigned it to you!
