### ISSUE TITLE
feat: return valid `actual_fee` in `get_transaction_receipt`

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1111]
Currently the `get_transaction_receipt` rpc return an incomplete object. The `actual_fee` field is set to `0`. 

Instead we should retrieve it from the events related to this TX and return it.

Also, uncomment the check for this in `starknet-rpc-test/get_transaction_receipt.rs` (signaled by a `TODO`)

**Comment by antiyro** [comment]
Can I take this one?

**Comment by tdelabro** [comment]
My DM are open if you have questions about the required impl
