### ISSUE TITLE
bug: cache miss not working properly

### ISSUE THREAD

**Issue by dbejarano820** [keep-starknet-strange/madara#1121]
# Bug Report

**Madara version:**
Commit: 0dfe2c4396a9545b9e6eb1ed8e08a2ef10ccb751

**Current behavior:**
Workflows are showing some odd behaviors that might be related to the cache miss not working properly

**Expected behavior:**
Should work fine

**Other information:**
https://github.com/actions/cache/issues/1114

**Comment by dbejarano820** [comment]
@d-roak

**Comment by d-roak** [comment]
notes to self:
- `fail-on-cache-miss: true` not working properly e.g. https://github.com/keep-starknet-strange/madara/actions/runs/6242895841/job/16947518922?pr=1101

**Comment by d-roak** [comment]
cache changed on #1188, it shouldn't happen anymore
