### ISSUE TITLE
feat: benchmark cargonexttest against current tests

### ISSUE THREAD

**Issue by d-roak** [keep-starknet-strange/madara#1122]
We want to benchmark `cargonexttest` against our current test runner to check if it runs the tests faster. If it does, we will replace it

**Comment by gogo2464** [comment]
could you assign me to this issue please?

**Comment by gogo2464** [comment]
@d-roak is this issue still open?

**Comment by d-roak** [comment]
Sure

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
