### ISSUE TITLE
feat: optimize tests

### ISSUE THREAD

**Issue by d-roak** [keep-starknet-strange/madara#1123]
Currently, the tests take a long time to run. We want to optimize them. Some ideas on what to improve:
- Spawn less madara nodes
- Parallelize the tests
- Increase performance of the current tests

**Comment by petscheit** [comment]
Have you considered using a mock runtime for the majority of the unit tests? It runs much faster, as a lot of the p2p/node overhead is removed.

**Comment by dbejarano820** [comment]
doesn't Rust already run tests in parallel? Each test function running its own thread

**Comment by d-roak** [comment]
This is tricky. Starting a madara currently takes some time, because of the genesis loading. Initializing one node for every test is very costly, thus we can run multiple tests within the same node instance.
That said, there are some tests that require a clean bootstrap to test specific scenarios. In those instances, we can parallelize the tests that are run across different node instances.
Tests on one instance should be sequential to have reproducibility of the results (i think currently, they are parallel)

**Comment by Juul-Mc-Goa** [comment]
Would be interested to work on this issue. This would be my first issue, so I might need some assistance at first.

**Comment by d-roak** [comment]
sry @Juul-Mc-Goa , this was done recently on #1145
