### ISSUE TITLE
bug: setup logs not displaying

### ISSUE THREAD

**Issue by apoorvsadana** [keep-starknet-strange/madara#1126]
Before the node starts we log some [information](https://github.com/keep-starknet-strange/madara/blob/e7513f22417198e3e3bb5860fae4a2f5ef6bed87/crates/pallets/starknet/src/utils.rs#L55) to tell the user that we are downloading/setting up files. However, the logger is only initialised once the node has started because of which these logs aren't showed up at all. You can find more about the reasons in the discussion here - https://github.com/keep-starknet-strange/madara/pull/1011

We need to evaluate if it's possible to start the logger before the node starts and if yes, we need to implement that.

**Comment by d-roak** [comment]
i assigned it to you. Look carefully to the discussion, it doesn't seem to be a trivial thing to resolve

**Comment by dbejarano820** [comment]
well that was painful, i'm moving on 😆

**Comment by justinfrevert** [comment]
@d-roak I'd like to take a look at this one

**Comment by d-roak** [comment]
All the info is logged in the setup subcommand
