### ISSUE TITLE
feat: Change error types to anyhow

### ISSUE THREAD

**Issue by d-roak** [keep-starknet-strange/madara#1129]
The true fix will be to use anyhow rather than `String` as the error type

_Originally posted by @tdelabro in https://github.com/keep-starknet-strange/madara/pull/1018#discussion_r1306694578_

**Comment by tdelabro** [comment]
You can start now!

**Comment by tdelabro** [comment]
Wait for #1018 to be merged.
I think you can still look at the code, but you may need to do a huge rebase if you start a branch right now

**Comment by Immanuel-john** [comment]
@tdelabro ok i will wait for the merge then!

**Comment by d-roak** [comment]
@Immanuel-john it's merged, you can start !

**Comment by tdelabro** [comment]
@Immanuel-john are you still interested to work on it?

**Comment by Immanuel-john** [comment]
hello @tdelabro i am working on it. will update ASAP!

**Comment by d-roak** [comment]
Any updates on this?

**Comment by Immanuel-john** [comment]
I tried working on this but finding difficult to get the context where I need to use anyhow. could you please help since I am a first time contributor here.

**Comment by tdelabro** [comment]
Hey, 
It looks like it has been taken care of in https://github.com/keep-starknet-strange/madara/pull/1165

**Comment by tdelabro** [comment]
Sorry about this it wasn't intentional.
But I think we can close this issue
