### ISSUE TITLE
feat: Extended Configuration

### ISSUE THREAD

**Issue by raynear** [keep-starknet-strange/madara#1138]
# Feature Request

**Describe the Feature Request**

This is raynear from Radius who is developing an encrypted mempool.

I suggest an extended configuration.
I added an extended command to facilitate the selection of an encrypted mempool. To enable this option in the transaction pool initialization process, we need to pass it as an argument. Currently, Madara has only incorporated a custom configuration for sealing. However, as more projects integrate their extended commands into Madara, the number of parameters will grow. To manage this expansion effectively, we recommend implementing an Extended Configuration feature.

**Describe Preferred Solution**

Currently, Madara still sends configure for sealing as a variable. We can make this a structure so that multiple configurations are available.

**Describe Alternatives**

**Related Code**

```rust
  // crates/node/src/cli.rs
  // as-is
  let runner = cli.create_runner(&cli.run.run_cmd)?;
  runner.run_node_until_exit(|config| async move {
      service::new_full(config, cli.sealing, cli.run.encrypted_mempool).map_err(sc_cli::Error::Service)
  })
  
  // to-be
  let runner = cli.create_runner(&cli.run.run_cmd)?;
  let extended_config = ExtendedConfiguration{sealing:cli.sealing, encrypted_mempool: cli.run.encrypted_mempool};
  runner.run_node_until_exit(|config| async move {
      service::new_full(config, extended_config).map_err(sc_cli::Error::Service)
  })
```

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_
Yes

**Comment by EvolveArt** [comment]
Thanks for this @raynear ! 

You can go ahead and make a PR for this sounds like the best approach so we don't overload with config parameters in the future and easier to maintain too!

**Comment by tdelabro** [comment]
Currently we only want to maintain in this repository starknet's core feature. The idea is that the content of this repo should reflect the state of starknet main-net. Anything else should be hosted there: https://github.com/keep-starknet-strange/madara-extentions/
