### ISSUE TITLE
spike:  explore Firewood - Compaction-Less Database Optimized for Efficiently Storing Recent Merkleized Blockchain State

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/madara#1147]
# Resources

- [Github repo](https://github.com/ava-labs/firewood)
- [Explainer article](https://www.avax.network/blog/introducing-firewood-a-next-generation-database-built-for-high-throughput-blockchains)

**Comment by tdelabro** [comment]
Not sure it's relevant right now
