### ISSUE TITLE
test: add a CI workflow for starknet.js compatibility

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1148]
We make sure that we stay compatible with `starknet.js` lib.

Add a workflow in the CI.
It should declare, deploy, call, estimate fee and invoke the contract.
It will be enough for now.

**Comment by lana-shanghai** [comment]
starknet js scripts that will massively help are here [https://github.com/lana-shanghai/madara_contract_scripts](url)

**Comment by dbejarano820** [comment]
I could take this on, how urgent is it?

**Comment by lana-shanghai** [comment]
> I could take this on, how urgent is it?

I would say we are quite behind on usability, and it would be super if you could take it in the coming week! Let us know if you need any help

**Comment by tdelabro** [comment]
@dbejarano820 we don't want to overcharge the madara repo with the compatibility test.
Do you think you could work on this on a repo of your own, that you will transfer to the https://github.com/keep-starknet-strange organization when ready?

Then we will use it in Madara CI :)

Does that sound ok to you?

**Comment by petscheit** [comment]
I'm happy to pick this up

**Comment by tdelabro** [comment]
@dbejarano820 are you actively working on it?
Or can it be given to @petscheit?
