### ISSUE TITLE
test: add CI workflow for starknet-foundry compatiblity

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1149]
We want starknet-foundry to work 100% with madara, ideally just by specifying the correct rpc url

Add a workflow to the CI.
It should use a custom starknet-foundry project and run it against madara, making sure the tool is compatible

**Comment by justinfrevert** [comment]
@tdelabro can I take this one?

**Comment by tdelabro** [comment]
@justinfrevert do you think it should live in the madara repository? Or exist in another repo and just be used in the madara repo CI?

**Comment by justinfrevert** [comment]
> @justinfrevert we don't want to overcharge the madara repo with the compatibility test. Do you think you could work on this on a repo of your own, that you will transfer to the @keep-starknet-strange organization when ready?
> 
> Then we will use it in Madara CI. Given the repo define a gh action
> 
> Does that sound ok to you?

Sure, it works for me. It seems like a fine approach. Will start on a separate repo focused on its own gh action.

**Comment by justinfrevert** [comment]
@tdelabro how extensive do you think the testing of the initial github action should be?

**Comment by tdelabro** [comment]
I think, `declare`, `deploy`, and `invoke` would be a good start. 
I think that is what 95% of foundry time is spent doing. But I may be missing something. What do you think?

**Comment by tdelabro** [comment]
Hey, all good?

**Comment by justinfrevert** [comment]
Hey @tdelabro I am looking into the incompatibilities themselves in https://github.com/keep-starknet-strange/madara/issues/1168 before I create the github action

**Comment by tdelabro** [comment]
@justinfrevert sure! Thanks a lot!!

**Comment by tdelabro** [comment]
@justinfrevert What is the state here?

**Comment by justinfrevert** [comment]
Hi @tdelabro this was blocked because of https://github.com/keep-starknet-strange/madara/issues/1168. I just found the fix for that yesterday, so I will create the PR today and also begin working on this issue.

**Comment by tdelabro** [comment]
@justinfrevert okay perfect. That's great to hear!
