### ISSUE TITLE
test: add starknet-rpc-test for get_state_update

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1150]
Blocked by #773, blocked by @lana-shanghai working on developing the state update logic

**Comment by kasteph** [comment]
Is it ok if I pick this back up from my old PR at #1080 once #773 is done?

**Comment by tdelabro** [comment]
@kasteph where are you at with this one?

**Comment by hhamud** [comment]
can I get this one assigned to me? @apoorvsadana

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
