### ISSUE TITLE
feat(rpc): add starknet_simulateTransactions rpc

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1152]
# Feature Request

## What to do?
We should add support for the `starknet_simulateTransactions` rpc

## How to do it?
@m-kus did most of the work in #883, but we delayed the merge due to #992
You should probably start from a fresh branch, since so much has changed, but the flow developed there can probably be kept.

## Related code
The specs: https://github.com/starkware-libs/starknet-specs/blob/59b838cdcc7b1cbf92f4249b00927185c93628e9/api/starknet_trace_api_openrpc.json#L41

**Comment by ayushtom** [comment]
I can pick this

**Comment by tdelabro** [comment]
Hey, All good?

**Comment by tdelabro** [comment]
👋

**Comment by ayushtom** [comment]
Hi @tdelabro . I haven't been able to continue on this due to time constraints. You can unassign me from this issue. 
Sorry for the delay from my end!

**Comment by tdelabro** [comment]
closed by #1281
