### ISSUE TITLE
test: test `validate_unsigned` for all tx types

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1163]
All the extrinsics wrapping tx are filtered by the `valited_unsigned` method in ` crates/pallets/starknet/src/lib.rs`

Yet, we have no tests to enforce the behavior.

We should have those for each type of tx, covering everything that can go wrong.
Those test should be pallet tests, ran against a mock runtime :)

**Comment by tdelabro** [comment]
I think this one goes directly to main, not to the l1-l2 messaging branch

**Comment by tdelabro** [comment]
I think you can do two PRs one to main, for the regular tests, and then, once we rebased another to the l1-l2 branch.
Wdyt?

**Comment by bidzyyys** [comment]
Yep, good idea!

**Comment by tdelabro** [comment]
Hey, all good?

**Comment by bidzyyys** [comment]
@tdelabro IMHO to be closed
