### ISSUE TITLE
feat: Usability: Starknet Foundry with Madara 

### ISSUE THREAD

**Issue by lana-shanghai** [keep-starknet-strange/madara#1168]
## Using starknet foundry with Madara 

Investigate how to add compatibility with Madara. Currently trying to create an Open Zeppelin account (default in Starknet Foundry) results in the following error:

```
sncast --url http://127.0.0.1:9944 account create --name my-account
command: account create
error: JSON-RPC error: code=61, message="The transaction version is not supported"
```

Account creation [code](https://github.com/foundry-rs/starknet-foundry/blob/33bd7a7c8247ad360fae1b47e69b1cd744199d10/crates/cast/src/starknet_commands/account/create.rs#L40)

The point where Madara fails with `UnsupportedTxVersion` is [here](https://github.com/keep-starknet-strange/madara/blob/6207f1c3a1376ac9e26d3a18a9685328422ec580/crates/client/rpc/src/lib.rs#L591) 

Open a PR in the Starknet Foundry [repo](https://github.com/foundry-rs/starknet-foundry) and test creating an account, fund it from the predeployed account, declare, deploy, invoke some test contracts. Reach out to the creators if necessary. Use the [starknet js scripts](https://github.com/lana-shanghai/madara_contract_scripts/tree/main) for inspiration.

**Comment by justinfrevert** [comment]
This also impacts https://github.com/keep-starknet-strange/madara/issues/1149 which I had briefly looked into. I'm happy to look into this one

**Comment by justinfrevert** [comment]
I did some digging: it seems the main cause for the errors is starknet-rs defaulting to `is_query: false` for `DeployAccount` actions(that happens [here)](https://github.com/xJonathanLEI/starknet-rs/blob/4ab2f36872435ce57b1d8f55856702a6a30f270a/starknet-accounts/src/factory/mod.rs#L346). I spoke to one of the devs in the starknet.rs channel, and [sounds like they're aware and planning to fix](https://t.me/starknet_rs/4880).

In the meantime, I can do a quick check if we can change the check on `is_query`, though it sounds like it might be good to just keep in place.

**Comment by lana-shanghai** [comment]
@justinfrevert cool! Do you suggest we do a temporary check skip for now, until it is fixed in starknet rs?

**Comment by justinfrevert** [comment]
We can do that for now, but it's critical that we undo this later because it affects transaction security(as I've heard). I'll do that and create an issue.

**Comment by justinfrevert** [comment]
I'm not doing the above change yet, as I haven't been able to test the full flow. I don't think it makes sense to make a change yet without ensuring there are not other compatibility issues
