### ISSUE TITLE
feat: Update to Polkadot SDK v1.1.0

### ISSUE THREAD

**Issue by d-roak** [keep-starknet-strange/madara#1170]
We want to update all the substrate stuff to [Polkadot SDK v1.1.0](https://github.com/paritytech/polkadot-sdk/releases/tag/polkadot-v1.1.0).

This is quite a big refactor, my advice is to open a draft PR and comment there on questions and issues that you might have.

**Comment by akhercha** [comment]
Hey, I'd like to try this one! 🫡

**Comment by d-roak** [comment]
I'll assign it to you. You can ask ur questions within the draft pr and ping me, I'll try to redirect u to someone who can answer it

**Comment by d-roak** [comment]
Change the dependency in the `Cargo.toml` and start fixing errors from the `cargo build`

**Comment by d-roak** [comment]
@onchezz has limited knowledge of rust. He will still try to tackle the issue by giving weekly updates and sending most questions to https://substrate.stackexchange.com/

If there is one week without any update, we can safely unassign it cc @tdelabro 

If there is someone more experienced in rust/polkadot-sdk, you can ping me

**Comment by tdelabro** [comment]
Okay. It's true that it is not an ideal first issue for someone beginning at Rust. @onchezz feel free to give up and take another issue if you feel that it's more frustrating than motivating and you cannot learn from it.

**Comment by fishseabowl** [comment]
@d-roak Could I try this? Thanks

**Comment by d-roak** [comment]
yes, assigned

**Comment by d-roak** [comment]
I am unassigning due to no updates and the pr #1264

**Comment by d-roak** [comment]
@notlesh can you comment here for me to assign to you pls

**Comment by tdelabro** [comment]
closed by #1264

**Comment by notlesh** [comment]
> @notlesh can you comment here for me to assign to you pls

Sorry, missed this earlier...
