### ISSUE TITLE
Bug: balance transfer to a new non-deployed address with starknet-js breaks 

### ISSUE THREAD

**Issue by lana-shanghai** [keep-starknet-strange/madara#1175]
# Bug Report

**Current behavior:**

Trying to send balance from a predeployed account to a Braavos address that has not been deployed yet in order to be able to deploy it. The address is `0x05dc3d9511372803f632fb7b6ce3db2c999454d7d28c7bbc07f355146dff0917`. 

Madara logs: 

```
Failed to retrieve storage at 'ContractAddress(PatriciaKey(StarkFelt("0x05dc3d9511372803f632fb7b6ce3db2c999454d7d28c7bbc07f355146dff0917")))' and 'StorageKey(PatriciaKey(StarkFelt("0x03ad34fad732b51fe0d1a1350f149f21a0cf14a9382c9c6e7b262c4e0c8dbf18")))'  
```

**Expected behavior:**

Successful transaction and new balance reflected in Braavos. 

**Steps to reproduce:**

Paste your Braavos address into the script and run it with `node scripts/argent_account_cairo_0/transfer_balance.js`

**Comment by lana-shanghai** [comment]
Bug part II: 

```
2023-10-09 15:47:25 Failed to retrieve contract class hash at 'ContractAddress(PatriciaKey(StarkFelt("0x031f77ab0441cd5d3a01ee26a3269acbb5e62a1704c0dd7d5e0e9ba85429d716")))'
```

Why is Madara expecting a deployed contract at the address to where the funds are being sent? Investigate where the error is propagating from.

**Comment by apoorvsadana** [comment]
assigning it to you @anshalshukla

**Comment by anshalshukla** [comment]
I think we can close this issue, the fixes to braavos was merged in a PR by @apoorvsadana with the changes I had proposed on my fork of madara.
cc: @lana-shanghai
