### ISSUE TITLE
feat: update declaration of Braavos account in genesis

### ISSUE THREAD

**Issue by lana-shanghai** [keep-starknet-strange/madara#1178]
# Feature Request

**Describe the Feature Request**

Currently in genesis we have these Braavos account class hashes 

```
pub const BRAAVOS_ACCOUNT_CLASS_HASH_CAIRO_0: &str =
    "0x0244ca3d9fe8b47dd565a6f4270d979ba31a7d6ff2c3bf8776198161505e8b52";
pub const BRAAVOS_PROXY_CLASS_HASH_CAIRO_0: &str = "0x06a89ae7bd72c96202c040341c1ee422474b562e1d73c6848f08cae429c33262";

```

When we try to declare a new account using Braavos, we get errors: 

```
{"jsonrpc":"2.0","error":{"code":40,"message":"Contract error"},"id":0}
{"jsonrpc":"2.0","error":{"code":20,"message":"Contract not found"},"id":0}
``` 

because the latest wallet expects a different class hash declared. 

In Madara logs, the following class hash is not found `0x03ae692aaf1ded26a0b58cf42490f757563850acea887ed57b4894fee8279063`

which is a Braavos account as seen on [Starkscan](https://testnet.starkscan.co/class/0x03ae692aaf1ded26a0b58cf42490f757563850acea887ed57b4894fee8279063#code)

Compiled program [link](https://alpha-mainnet.starknet.io/feeder_gateway/get_class_by_hash?classHash=0x03ae692aaf1ded26a0b58cf42490f757563850acea887ed57b4894fee8279063) 

Add this class hash and code to the genesis contracts deployed on Madara and verify the flow of setting up a new account on Braavos. This issue is also linked to [transaction version](https://github.com/keep-starknet-strange/madara/issues/1168) which blocks both starknet foundry flow and Braavos, but the temporary removal of the `is_query` check allows to decouple the Braavos flow from starknet foundry.

**Comment by ftupas** [comment]
Hello, may I take this?

**Comment by lana-shanghai** [comment]
Please do!

**Comment by EvolveArt** [comment]
Hey @ftupas what's the status on this ?

**Comment by ftupas** [comment]
Hey there @EvolveArt, sorry I took a bit of time off to deal with personal things. I started to continue working on this, apologies for the delay

**Comment by apoorvsadana** [comment]
This was recently fixed but broke again with a new Braavos update. Assigning it to myself for now.

**Comment by tdelabro** [comment]
@apoorvsadana what is the status here?

**Comment by apoorvsadana** [comment]
Asked on the group, will update

**Comment by tdelabro** [comment]
@apoorvsadana can you document what to do?

**Comment by apoorvsadana** [comment]
Ya, so basically, we want to declare Braavos contracts on Madara and check if using the wallet extension are we able to use Braavos with Madara or not. If it works fine, we can add the new contracts to the genesis. I will ask @ocdbytes to pick it up.

**Comment by ocdbytes** [comment]
I will take this

**Comment by tdelabro** [comment]
@ocdbytes thanks a lot

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
