### ISSUE TITLE
bug: starknet_getTransactionReceipt returns a "Internal server error"

### ISSUE THREAD

**Issue by antiyro** [keep-starknet-strange/madara#1206]
# Bug Report

**Madara version:**

I am currently using the latest version of Madara fetching Starknet mainnet via Deoxys implementation

**Current behavior:**

When I try to do:

```
curl --request POST \
     --url https://deoxys.kasar.io/rpc \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "starknet_getTransactionReceipt",
  "params": [
    "0x3bade3c1dc9d6c0c4cadf562012df2df032066f6e2174bf572f817af268d1fd"
  ]
}
'
```

For example, with https://voyager.online/tx/0x3bade3c1dc9d6c0c4cadf562012df2df032066f6e2174bf572f817af268d1fd beeing a known Starknet mainnet block I receive:

```
{"jsonrpc":"2.0","error":{"code":500,"message":"Internal server error"},"id":1}
```

- For the same call using a blast rpc key I receive the right data
- For the same address using getTransactionByHash I receive the right data
- Picked up 10 random tx between block 0-10k and get the same error

**Comment by antiyro** [comment]
Yes, I wasn't in archive mode. Still I think we should return `State already discarded for {:?}, tx_hash` in that case instead of an Internal server error

**Comment by tdelabro** [comment]
I created #1214 to improve the user experience

**Comment by antiyro** [comment]
1. Tested in --prunning archive mode, and my Madara still panics
2. Tested with recent blocks, and my Madara still panics

Calling your attention on this since anyone could shutdown a Madara node trough this rpc call
