### ISSUE TITLE
dev(StarknetRPC): log all errors content

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1214]
## Current Behaviour

The values of errors we return from the StarknetRpcApi is dictated by the starknet OpenRPC specifications.
We impl them in ` crates/client/rpc/src/errors.rs` with our struct `StarknetRpcApiError`.

## Problem

A lot of errors are just cast as `InternalServerError` and therefore partially silenced, which is not optimal for debugging.

## Solution

We should make sure to `log::error!` the actual error we receive from the node before casting returning them as `InternalServerError`

**Comment by jobez** [comment]
may i be assigned?
