### ISSUE TITLE
dev: move StarknetRuntimeApi trait definition in it's own crate

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1223]
We don't have to import the whole starknet pallet each time we just want this simple trait definition.

The crate name should be `pallet-starknet-runtime-api`
and it should exist at `crates/pallet/starknet/runtime_api/`

**Comment by Yogalholic** [comment]
I  would like to give it a try please

**Comment by EvolveArt** [comment]
hey @Yogalholic any progress on this ?

**Comment by Yogalholic** [comment]
> hey @Yogalholic any progress on this ?

Hello. Yes I am still working on it. I was slow down with parts of the code that were hard to read. I corrected those issues on PR #1238.
I apologized for the delay and will upload my work very soon.

**Comment by EvolveArt** [comment]
> > hey @Yogalholic any progress on this ?
> 
> Hello. Yes I am still working on it. I was slow down with parts of the code that were hard to read. I corrected those issues on PR #1238. I apologized for the delay and will upload my work very soon.

Thanks, this PR was closed cause too small just apply this change in the PR that relates to this issue.

**Comment by tdelabro** [comment]
@Yogalholic Cool. Keep us updated!

**Comment by tdelabro** [comment]
@Yogalholic How is it going?

**Comment by Yogalholic** [comment]
It takes me longer than expected, I'm a little bit drowned in the dependencies (especially the std features), I am comparing the different Cargo.toml files.

**Comment by tdelabro** [comment]
Any questions I may help with?

**Comment by tdelabro** [comment]
closed by #1272
