### ISSUE TITLE
feat: Sync from L1

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/madara#1224]
Enable Madara to Sync it's state from L1.

As Starknet is a Validity Rollup on top of an L1 (Ethereum) we can query the base chain to retrieve all of the information needed to recompute the `last proved` state of Starknet.  

The information needed to recompute the state is known as a [StateDiff](https://github.com/starkware-libs/starknet-api/blob/89c32d3a2188c3aa4ee7d8fbe19b3d791d4be92a/src/state.rs#L38) and it includes pertinent changes to the Starknet State per block:
- deployed contracts
- storage updates
- declared(+deprecated) classes 
- nonce updates
- replaced classes

This information is encoded by the Starknet OS as calldata, encoding defined [here](https://docs.starknet.io/documentation/architecture_and_concepts/Network_Architecture/on-chain-data). This calldata is PUBLISHED AND LOGGED to the [L1 Core Contracts](https://etherscan.io/address/0x16938e4b59297060484fa56a12594d8d6f4177e8#code#F1#L186) and checked against the [verifier's](https://goerli.etherscan.io/address/0xb59d5f625b63fbb04134213a526aa3762555b853#code#F5#L1) fact registry in the following function `updateState`

```
    /**
      Updates the state of the StarkNet, based on a proof of the
      StarkNet OS that the state transition is valid.

      Arguments:
        programOutput - The main part of the StarkNet OS program output.
        data_availability_fact - An encoding of the on-chain data associated
        with the 'programOutput'.
    */
    function updateState(
        uint256[] calldata programOutput,
        uint256 onchainDataHash,
        uint256 onchainDataSize
    ) external onlyOperator {
```
Each state update is tied to a `Fact` which is a hash represents the output of the StarknetOS and its program hash and serves as an attestation of the block verification(simple [fact hash example](https://github.com/dontpanicdao/starknet-da/blob/main/section-2/fact_check.py)). These facts can be registered as mulitple MemoryPages in the verifier fact registry.

## Syncing
The implementation will involve(w/ python examples):
- [SN Genesis defs](https://github.com/eqlabs/pathfinder/blob/main/crates/common/src/consts.rs)
- from genesis fetch the [state update logs and the state transition fact logs](https://github.com/dontpanicdao/starknet-da/blob/main/section-3/fact_retrieval.py#L41-L42)
- [fetch the memory page logs](https://github.com/dontpanicdao/starknet-da/blob/4242225c42de914de6910b8097fec958ddd52323/section-3/fact_retrieval.py#L57) for that block(or in bulk)
- Fetch all `LogMemoryPageFactContinuous` [events from the MemoryPageFactRegistry](https://github.com/dontpanicdao/starknet-da/blob/4242225c42de914de6910b8097fec958ddd52323/section-3/fact_retrieval.py#L67)
- [decode](https://github.com/dontpanicdao/starknet-da/blob/4242225c42de914de6910b8097fec958ddd52323/section-3/fact_retrieval.py#L82) the function input tied to this memory page fact which will correspond to the encoded DA output described above
- [parse the DA](https://github.com/dontpanicdao/starknet-da/blob/4242225c42de914de6910b8097fec958ddd52323/section-3/fact_retrieval.py#L111) and apply the relevant changes to your aggregated state via [mapping sync](https://github.com/keep-starknet-strange/madara/blob/281a12f9fe5a123fbfe005a4dfed60bbe3f8bf76/crates/client/mapping-sync/src/sync_blocks.rs#L98)
- repeat until you reach to current head

**Comment by jerrybaoo** [comment]
Our team has essentially implemented this feature. This is our PR: https://github.com/keep-starknet-strange/madara/pull/1296

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
