### ISSUE TITLE
feat: RPC call to get pre funded accounts in Madara

### ISSUE THREAD

**Issue by apoorvsadana** [keep-starknet-strange/madara#1230]
Wallets need an RPC where they can fetch funded accounts on a devnet. It helps them easily fund new accounts for users to play with. Katana and starknet-devent already support this. It's `predeployed_accounts` for `devnet/devnet-rs` and `/katana_predeployedAccounts` for `katana`. 

We need to do the same for Madara. We can call it `madara_predeployedAccounts`. We already log the pre funded accounts when the user starts the node in `--dev` mode. You can see it [here](https://github.com/keep-starknet-strange/madara/blob/57fc9a21b3f6f6474f00d50d2f7ec11623155bd1/crates/node/src/chain_spec.rs#L113). Ideally, we can move this information to constants or a JSON config and use it for both - logs and for this API.

BONUS: This isn't necessary, but ideally if we can fetch the balance of the native token for each of these accounts it would be a nice feature.

**Comment by Juul-Mc-Goa** [comment]
Would be interested to work on this issue :)
Still learning the codebase though

**Comment by apoorvsadana** [comment]
Awesome! Feel free to message on the Madara group if you any doubts. Assigned to you @Juul-Mc-Goa

**Comment by EvolveArt** [comment]
Hey @Juul-Mc-Goa any progress on this ? Let us know if you need any help

**Comment by web3olalala** [comment]
@apoorvsadana Maybe I'll give it a try, before I do I need to know exactly what data is returned by `madara_predeployedAccounts`, all I see printed is this information
<img width="1557" alt="image" src="https://github.com/keep-starknet-strange/madara/assets/111047493/ea1fef75-c5ad-4b1a-95e1-4c3190b9134f">

**Comment by tdelabro** [comment]
@Juul-Mc-Goa can you write to me on telegram for payment please.
@timothee_delabrouille
