### ISSUE TITLE
clean: Analyze the pallets we currently use and check if we can remove some that are not necessary. 🧹

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/madara#124]
# Description
Analyze the pallets we currently use and check if we can remove some that are not necessary. It could save some extrinsic calls and optimize performances.

**Comment by DavideSilva** [comment]
I'll take this one

**Comment by DavideSilva** [comment]
I have been looking into this and it seems all the remaining pallets are essential and can not be removed
