### ISSUE TITLE
feat: add argent multicall contract to genesis

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#1243]
# Feature Request

**Describe the Feature Request**

Argent is relying on this [multicall](https://github.com/argentlabs/argent-contracts-starknet/blob/main/contracts/multicall/src/multicall.cairo) contract for calling contracts. We should add it to genesis along with the other contracts (ERC20, ERC721...)

**Comment by jobez** [comment]
i can work on this
