### ISSUE TITLE
feat: add storage values to fee token contract in genesis

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#1244]
# Feature Request

**Describe the Feature Request**

The fee token contract is already deployed at genesis as shown [here](https://github.com/keep-starknet-strange/madara/blob/main/configs/genesis-assets/genesis.json#L124).

We just need to add new entries to the `storage` such that `name`, `symbol` and `decimals` storage values are correctly initialized respecively to `0x4574686572`, `0x455448` and `0x12`.(https://goerli.voyager.online/contract/0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7#readContract)

**Comment by tonypony220** [comment]
I can give it a try
