### ISSUE TITLE
feat: tx version verification ✨

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#127]
# Feature Request

**Describe the Feature Request**

We want to verify the transaction version upon execution.
You can have a look at the blockifier implementation [here](https://github.com/tdelabro/blockifier/blob/no_std-support/crates/blockifier/src/transaction/account_transaction.rs#L100).

**Acceptance Criteria**

- We can change the transaction version type to u8 quite safely
- Should only accept transaction v1 except for `declare`
- Error should be handled and propagated to the pallet
- Tests should be added

**Comment by zediogoviana** [comment]
Hi! I can try to tackle this one

**Comment by abdelhamidbakhta** [comment]
> 

awesome, assigned it to you. Are you on the telegram group ?

**Comment by zediogoviana** [comment]
Yes, I'm the dependabot guy, from finiam 😅
