### ISSUE TITLE
feat: use starknet-bootstrap in genesis loader

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#1280]
# Feature Request

**Describe the Feature Request**

We need a better way to initialise the chain state that doesn't require hardcoding storage keys/values in the config unless for very specific needs but it shouldn't be the baseline.

**Describe Preferred Solution**

Recently release, we can leverage the [starknet-boostrap](https://github.com/xJonathanLEI/starknet-bootstrap) repo, which is used to bootstrap the new Starknet Sepolia Testnet.
This could then be further extended to fit the needs of any app-chain.

**Comment by ybensacq** [comment]
@EvolveArt  can you assign to me please, I will manage that after my current task.

**Comment by tdelabro** [comment]
starknet-bootstrap is not maintained anymore (last commit 6 month ago)
Are you aware of another tool @EvolveArt ?
