### ISSUE TITLE
dev: DA publishing by block author

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#1283]
**Current Behavior**

State diffs are published to the DA layer using `client.import_notification_stream()` so every node running the DA outer-node service will be publishing which is not what we want in a decentralized context as it would result with duplicates.

**Expected Behavior**

Only the block author should be able to publish state diffs to the DA layer.

**Comment by frisitano** [comment]
Can I pick this up?

**Comment by tdelabro** [comment]
da is not part of madara anymore since https://github.com/keep-starknet-strange/madara/pull/1580
