### ISSUE TITLE
dev: DA layer synchronicity

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#1284]
**Current Behavior**

State diffs are published at a frequency defined by the notification stream, so more or less the app-chain block time. This leads to an ever-growing queue of un-settled DA facts, that would make it hard/impossible to derive state properly from the DA layer.

**Expected Behavior**

Instead publishing schedule should be defined in the DA layer's configuration. 
Given this property, state diffs could also be batched efficiently.

**Comment by edisontim** [comment]
Hey! Can I take this :) ?

**Comment by EvolveArt** [comment]
> Hey! Can I take this :) ?

Sure! Assigned

**Comment by edisontim** [comment]
Waiting for #1287 to be merged before working on this

**Comment by tdelabro** [comment]
This is not required anymore. This whole "snos/proving/da" flow will be moved in another repo
