### ISSUE TITLE
dev: Upgrade Madara JSON-RPC specs to v0.6.0-rc5

### ISSUE THREAD

**Issue by antiyro** [keep-starknet-strange/madara#1291]
# Upgrade Madara JSON-RPC specs to v0.6.0-rc5

## Overview
This issue concerns the implementation of the latest version of Starknet's JSON-RPC API: [v0.6.0-rc5](https://github.com/starkware-libs/starknet-specs/releases/tag/v0.6.0-rc5) within Madara (currently on [v0.4.0](https://github.com/starkware-libs/starknet-specs/releases/tag/v0.4.0)) to ensure and maintain full compatibility with Starknet.

## Detailed Description
Since version 0.4.0 of Starknet RPC, here's what has changed:

### v0.5.1 New Features
- [x] **General Improvements**: Focused on covering information gaps between the feeder-gateway and the RPC.
- [x] **Extracted `broadcasted declare txn`**: Separated from `declare txn`.
- [x] **Schema Enhancements**: Fixed references and added "required" to write-API results.
- [x] **Pending Block Schema Fixes**: Adjustments for pending block & block with hash.
- [x] **Broadcasted Transaction**: Reintroduced with query version capability.
- [x] **Receipts & Block Header Fields**: 
  - [x] Introduced `starknet_specVersion` endpoint.
  - [x] Added type field to transaction trace objects.
  - [x] Added order field to events/messages in transaction trace.
  - [x] Added `l1_gas_price` and `starknet_version` to block header.
  - [x] Split transaction receipt objects by type with `execution_resources`.
- [x] **Trace Improvement**: Added state diffs and order to events/messages.
- [x] **`CONTRACT_ERROR` Enhancement**: Included string data.
- [x] **Transaction Status API**: Added `starknet_getTransactionStatus` and removed `starknet_pendingTransactions`.
- [x] **`PENDING_STATE_UPDATE` Schema Fix**: Addressed schema issues.
- [x] **`broadcasted_declare_txn_v1` Fields**: Added missing fields.
- [x] **Error Type Change**: Modified `traceBlockTransaction` error type.
- [x] **Pending Block Header**: Added missing fields.

### v0.6.0 New Features
- **v0.6.0-rc5**:
  - [ ] Imported `BROADCASTED_DECLARE_TXN` in write API.
  - [ ] Added string data to `VALIDATION_FAILURE`.
- **v0.6.0-rc4**:
  - [ ] Typo fix and property addition to schema object.
  - [ ] Mandatory simulation flags in `starknet_estimateFee`.
- **v0.6.0-rc3**:
  - [ ] Refactored `traceTransactions` and `estimateFee`.
  - [ ] Renamed `STRK` to `FRI`.
  - [ ] Introduced `TRANSACTION_EXECUTION_ERROR`.
  - [ ] Added `SKIP_VALIDATE` flag to `starknet_estimateFee`.
  - [ ] Included units in `FEE_ESTIMATE`.
- **v0.6.0-rc2**:
  - [ ] Stricter restrictions on v3 fields.
  - [ ] Fixed `DECLARE_TXN_V1` version.
  - [ ] Made trace fields optional (as in 0.5.1).
- **v0.6.0-rc1**:
  - [ ] Added v3 transactions additional fields.
  - [ ] Bound numeric properties by `FELT` and made built-in resources optional.
  - [ ] Added segment arena built-in.
- **v0.6.0-rc0**:
  - [ ] Changed execution resource counters to integers.
  - [ ] Fixed schema in `PENDING_DEPLOY_TXN_RECEIPT`.
  - [ ] Allowed `EMITTED_EVENT` in pending block.
  - [ ] Disallowed certain fields in `PENDING_BLOCK_HEADER`.
  - [ ] Introduced v3 transactions.
  - [ ] Added `state_diff` to `L1_HANDLER` and `DELEGATE` call type.
  - [ ] Added resources to internal calls in a trace.

## Goals/Objectives
To implement all the new features of the latest version as well as to reference here any potential problems and changes to track the status of the implementation.

## Potential Challenges/Risks
Track potential risks or problems of the implementation: TBD.

## Testing
Update and set up tests for the implementation: TBD.

## Timeline
I expect the implementation to take around one week: TBD.

**Comment by antiyro** [comment]
This issue will be solved gradually starting with a v0.5.1 (last stable) full upgrade. Please reffer to the [v0.5.1](https://github.com/starkware-libs/starknet-specs/blob/v0.5.1/api/starknet_api_openrpc.json) release.

**Comment by antiyro** [comment]
Now that https://github.com/keep-starknet-strange/madara/pull/1313 is about to be merged to implement v0.5.1 and v0.6.0 has been released here: https://github.com/starkware-libs/starknet-specs/releases. We can continue on another issue. I'll comment it under here and close it when v0.5.1 is merged.

**Comment by hhamud** [comment]
I can help by grabbing this issue

Imported BROADCASTED_DECLARE_TXN in write API.

**Comment by apoorvsadana** [comment]
0.6.0 being tracked #1352
