### ISSUE TITLE
bug: rpc reads on local node

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#1295]
While conducting load-tests on a local Madara node using [this](https://github.com/keep-starknet-strange/gomu-gomu-no-gatling) tool, we observed the following behavior:
- Sending write transactions work well to some extent (see #818)
- The tool is supposed to check transactions in parallel to make sure they have correctly been processed by the sequencer and thus have the `ACCEPTED_ON_L2` status.

However the witnessed behavior is that the *more* connections to the node we have, each connection being in a different thread, the slower RPC calls get. This goes up to the point where 100 connections can lead to RPC calls taking a few minutes which is unacceptable and a huge DOS factor.

This clearly shows that some lock is taken by the RPC service and release only after the query has been processed thus slowing down all pending calls.

In the end, it's impossible to efficiently check thousands of transactions in parallel on a local madara node.
This might also be *not a big deal* if we take into the account that in production environments, we will have RPC only nodes and specialized actors that make sure the load is distributed correctly.

**Expected Behavior**

[Katana](https://github.com/dojoengine/dojo/tree/main/crates/katana) on the other hand is able to correctly process read calls in parallel.

**Comment by haroune-mohammedi** [comment]
Related to https://github.com/keep-starknet-strange/gomu-gomu-no-gatling/issues/18

**Comment by hhamud** [comment]
Can I take this one?
