### ISSUE TITLE
dev: Implement tests for new rpc method starknet_getTransactionStatus

### ISSUE THREAD

**Issue by antiyro** [keep-starknet-strange/madara#1298]
## Implement tests for new rpc method starknet_getTransactionStatus

The goal of this issue is to implement tests regarding the recently implemented rpc method starknet_getTransactionStatus under `starknet-rpc-tests/`

**Comment by ybensacq** [comment]
@antiyro can you assign it to me
Plz ?

**Comment by antiyro** [comment]
Sure if you need any help please let me know!

**Comment by fishseabowl** [comment]
@tdelabro Could I take this? Thanks

**Comment by tdelabro** [comment]
@fishseabowl sure
