### ISSUE TITLE
feat: global state root computation 🦀

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#130]
# Feature Request

**Describe the Feature Request**

Computed the global state root as defined in the starknet specs [here](https://docs.starknet.io/documentation/architecture_and_concepts/State/starknet-state/#state-commitment) and feed it into the block.

You can find the `IntermediateStateRoot` object under `pallets/starknet/src/state_root.rs`

**Acceptance Criteria**

- Tests should be added
- Hash function should be generic
- It should correctly take into account the constant prefix currently based on what is defined under the `storage` primitive

**Comment by ben2077** [comment]
Let me give it a try.

**Comment by abdelhamidbakhta** [comment]
> 

thanks!

**Comment by abdelhamidbakhta** [comment]
hey @ben2077 any news on this one ?

**Comment by ben2077** [comment]
I am starting to deal with this now, and I had some work to do in the past
two days.

Abdel @ StarkWare ***@***.***> 于2023年4月5日周三 18:23写道：

**Comment by ben2077** [comment]
I have the following two questions that I need answers to in order to continue development.
1.How to calculate the storage_root for a given contract address, considering that it is constructed as a Merkle-Patricia tree with the Pedersen hash function?

2.Where can we find the compiled_class_hash and how does it differ from the classHash we are currently reading in our system?

And i have one thing to do：
Implementation of Poseidon2 to support ClassHash.

**Comment by ben2077** [comment]
https://github.com/keep-starknet-strange/madara/pull/166

**Comment by LucasLvy** [comment]
Does it answer all your questions ? https://docs.starknet.io/documentation/architecture_and_concepts/State/starknet-state/

**Comment by LucasLvy** [comment]
Note that you probably need to store this in the db to avoid recomputing the whole tree at each block

**Comment by LucasLvy** [comment]
I strongly suggest that you take a look at Pathfinder's implementation [here](https://github.com/eqlabs/pathfinder/tree/main/crates/merkle-tree/src)

**Comment by ben2077** [comment]
> https://docs.starknet.io/documentation/architecture_and_concepts/State/starknet-state/ compiled class hash = class hash Does it answer all your questions ?

Thanks, this helped me a lot

**Comment by ben2077** [comment]
Sorry of being delayed for a week in meeting at HK.  This is exatctly  is what I am doing：
1.Create a new Merkle tree structure that supports a maximum height of 251.
Implement a Merkle tree storage trait that abstracts the storage layer and allows for different storage implementations, such as in-memory or on-chain storage.
2.Implement a Substrate pallet that includes the Merkle tree implementation and supports a custom storage layer. This involves using a StorageMap to store the Merkle tree nodes on the blockchain.
3.Modify the existing Merkle tree implementation to accommodate the new storage layer using the storage trait.

**Comment by ben2077** [comment]
Will everyone think this approach is OK, for example, can we reuse some of the existing code in the current codebase for storage?
