### ISSUE TITLE
feat(rpc): Implement starknet_estimateMessageFee 

### ISSUE THREAD

**Issue by antiyro** [keep-starknet-strange/madara#1301]
# Feature Request

**feat(rpc): Implement starknet_estimateMessageFee**

This PR aims to implement `starknet_estimateMessageFee` rpc call introduced in v0.4.0-rc1 according to the v0.5.1 RPC specs described in #1291 

`starknet_estimateMessageFee`

 Estimates the L2 fee of a message sent on L1.

 This function estimates the resources required by the l1_handler
 transaction induced by the message.

 ### Arguments

 * `message`: The message's parameters.
   - This parameter must follow the structure defined in `MSG_FROM_L1`.
 * `block_id`: The hash of the requested block, or number (height) of the requested block,
   or a block tag, for the block referencing the state or call the transaction on.
   - This parameter must follow the structure defined in `BLOCK_ID`.

 ### Returns

 Returns the fee estimation as defined in `FEE_ESTIMATE`.

 ### Errors

 This function might return the following errors:
 * `CONTRACT_ERROR` - An error related to the contract's execution or state.
 * `BLOCK_NOT_FOUND` - The specified block could not be found.

**Comment by Tbelleng** [comment]
Can i take this one sir ?

**Comment by antiyro** [comment]
Yes! @Tbelleng could you please provide an expected behavior under here?

**Comment by Tbelleng** [comment]
<img width="1083" alt="Screenshot 2023-12-06 at 4 04 48 PM" src="https://github.com/keep-starknet-strange/madara/assets/117627242/4f70c855-aa29-4da5-a46f-708785b2de38">
Yes sir 🫡 !

**Comment by antiyro** [comment]
Nice! glhf tell me if you need anything

**Comment by Tbelleng** [comment]
Im gonna do it since missing implems are now live on madara
