### ISSUE TITLE
feat: Add l1_gas_price and starknet_version to block and pending block headers

### ISSUE THREAD

**Issue by antiyro** [keep-starknet-strange/madara#1303]
# Feature Request

**Add l1_gas_price and starknet_version to block and pending block headers**

This issue aims to implement `l1_gas_price` and `starknet_version`to `BLOCK_HEADER` and `PENDING_BLOCK_HEADER`
Based on the following specs: https://github.com/starkware-libs/starknet-specs/blob/v0.6.0-rc5/api/starknet_api_openrpc.json#L1375

**`l1_gas_price` Element:**
   - **Title:** L1 Gas Price
   - **Description:** This element represents the price of Layer 1 (L1) gas in a given block.
   - **Reference:** The element references a schema defined under `components/schemas/RESOURCE_PRICE` check [here](https://github.com/starkware-libs/starknet-specs/blob/v0.6.0-rc5/api/starknet_api_openrpc.json#L3752C13-L3770C15)

**`starknet_version` Element:**
   - **Title:** StarkNet Version
   - **Description:** This element specifies the version of the Starknet protocol being used. The version is indicated using Semantic Versioning (SemVer). Please do not confuse with spec_version returning RPC spec version!
   - **Type:** The type of this element is defined as a `string`. The implementation must validate that the version string adheres to the SemVer format. If no version is specified an empty string should be returned like `"starknet_version":""`

### Exepected behavior

exemple with in `starknet_getBlockWithTxHashes` for Starknet mainnet on block: 40000

<img width="855" alt="Capture d’écran 2023-12-06 à 16 57 59" src="https://github.com/keep-starknet-strange/madara/assets/74653697/b9910fea-7134-4661-9cc2-fafc6c404c7a">

**Comment by antiyro** [comment]
This issue is related to a task under #1291

**Comment by antiyro** [comment]
Those can be find under `TODO(#1291)` assignments in the code base

**Comment by makluganteng** [comment]
Would like to research on the `l1_gas_price` if thats okey
