### ISSUE TITLE
feat: `to_rpc_contract_class` is still returning contracts with a lot of missing data

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1316]
```rust
/// Returns a [`ContractClass`] from a [`BlockifierContractClass`]
pub fn to_rpc_contract_class(contract_class: BlockifierContractClass) -> Result<ContractClass> {
    match contract_class {
        BlockifierContractClass::V0(contract_class) => {
            let entry_points_by_type = to_legacy_entry_points_by_type(&contract_class.entry_points_by_type)?;
            let compressed_program = compress(&contract_class.program.to_bytes())?;
            Ok(ContractClass::Legacy(CompressedLegacyContractClass {
                program: compressed_program,
                entry_points_by_type,
                // FIXME 723
                abi: None,
            }))
        }
        BlockifierContractClass::V1(_contract_class) => Ok(ContractClass::Sierra(FlattenedSierraClass {
            sierra_program: vec![], // FIXME: https://github.com/keep-starknet-strange/madara/issues/775
            contract_class_version: option_env!("COMPILER_VERSION").unwrap_or("0.11.2").into(),
            entry_points_by_type: EntryPointsByType { constructor: vec![], external: vec![], l1_handler: vec![] }, /* TODO: add entry_points_by_type */
            abi: String::from("{}"), // FIXME: https://github.com/keep-starknet-strange/madara/issues/790
        })),
    }
}
```

This piece of code is still missing most fields. How to solve this?

Possible solution:
- store the data lost when passed to the runtime (eg. abi) in a kvStorage in the client, read them back from there when answering `get_class` rpc request

**Comment by Juul-Mc-Goa** [comment]
Hi, would be interested to work on this.

**Comment by tdelabro** [comment]
Thanks a lot @Juul-Mc-Goa ! Message me if you don't know how to design things.

**Comment by tdelabro** [comment]
Hey @Juul-Mc-Goa, this one had been assigned to you but I don't think you ever worked on it.
Do you want to, or can I unassign you?

**Comment by Juul-Mc-Goa** [comment]
Hey, sorry got busy with other things.
I can start working on it next monday, or you can unassign me if you prefer.

**Comment by tdelabro** [comment]
Starting next Monday will be great! Thank you

**Comment by Juul-Mc-Goa** [comment]
Hey @tdelabro, just to be sure, the kvStorage in the client will not be gossiped to other nodes ?
If it has to be gossiped, as said in #775, then I don't know how it should be implemented.

**Comment by tdelabro** [comment]
@Juul-Mc-Goa indeed it would be gossiped. We have to find some other way.
Starknet does not have the issue coz it is centralized.
I think we have to gossip them or make them available one way or another.

Put your work here in hold, and open a [discussion](https://github.com/keep-starknet-strange/madara/discussions) so that we can find the best way to do that.
List the potential solutions you can think as a starting point for the discussion.

**Comment by Juul-Mc-Goa** [comment]
@tdelabro  started a discussion [there](https://github.com/keep-starknet-strange/madara/discussions/1395)

**Comment by tdelabro** [comment]
I'm working on this whole flow. There is a number of task to do first, but I'm on it

**Comment by elielnfinic** [comment]
has this been fixed? @tdelabro @Juul-Mc-Goa

**Comment by tdelabro** [comment]
@elielnfinic nope, still an issue

**Comment by elielnfinic** [comment]
I will come back to this after completing the other task you just assigned to me. If you don't mind, you can assign this to me too.

**Comment by elielnfinic** [comment]
Has this function been changed to `blockifier_to_rpc_contract_class_types` in `crates/client/rpc-core/src/utils.rs`?

**Comment by tdelabro** [comment]
@elielnfinic yes indeed

**Comment by elielnfinic** [comment]
Is conversion from `EntryPointV1` to `SierraEntryPoint` available?

**Comment by elielnfinic** [comment]
I think, I am able to fix that conversion.

**Comment by tdelabro** [comment]
@elielnfinic I think this PR will be fixed by some work I'm doing, storing the casm contract class on the client.
It will provide all the data required to fill those missing fields. I don't think you will be able to complete this issue without this

**Comment by elielnfinic** [comment]
I can create a draft PR to see if some parts of my code be used.

**Comment by tdelabro** [comment]
Sure, but don't spend too much time on that :)

**Comment by elielnfinic** [comment]
Hey @tdelabro, please proceed, I will not submit the PR draft.

**Comment by Juul-Mc-Goa** [comment]
Hey,

Is this issue still relevant ? I would be interested to work on this.

**Comment by tdelabro** [comment]
I'm on it #1631

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
