### ISSUE TITLE
dev: Maybe we can improve the way we init our RPC servers

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1319]
In `crates/node/src/rpc/mod.rs` we init one `Starknet` instance for each one of the RPC server extensions we have.
Maybe there is some opti to do there.
Either share a single `Starknet` instance for all, inside an Arc. Or something else.
Also, not every RPC server we define needs all of the fields inside `Starknet`.

Something to think about, but not crucial performance-wise.

**Comment by hhamud** [comment]
Can you assign this one to me

**Comment by tdelabro** [comment]
@hhamud give it a try
