### ISSUE TITLE
feat(rpc): bumped starknet.rs to match v0.6.0

### ISSUE THREAD

**Issue by antiyro** [keep-starknet-strange/madara#1324]
### feat(rpc): bumped starknet.rs to match v0.6.0

The first step to implement [v0.6.0](https://github.com/starkware-libs/starknet-specs/blob/v0.6.0/api/starknet_api_openrpc.json) into madara is to bump starknet rs to [this commit](https://github.com/xJonathanLEI/starknet-rs/commit/63f091d356cbc26acf4aea31f7f821d10fe608d0). This implies bumping https://github.com/keep-starknet-strange/blockifier and https://github.com/keep-starknet-strange/starknet-api.

Please notify me when you have a working version ready to merge into Madara

**Comment by ybensacq** [comment]
@antiyro can you assign it to me ?

**Comment by antiyro** [comment]
@ybensacq you should actually wait for this one to be merged to avoid doubling work: https://github.com/keep-starknet-strange/madara/pull/1313

**Comment by tdelabro** [comment]
@ybensacq @antiyro is this issue still a thing? Should it be re-activated or closed?

**Comment by tdelabro** [comment]
Is it required for #1352

**Comment by tdelabro** [comment]
I'm not sure. @antiyro ?

**Comment by antiyro** [comment]
It's an easy task that could be pushed already but I would like to wait for the other components (including starknet.rs) to rebase on v0.13 to start anything related to the v0.6.0 JSON-RPC integration. I'm closing this one.
