### ISSUE TITLE
feat(rpc): Impl EstimateResources wrapper for transactiont receipt result

### ISSUE THREAD

**Issue by antiyro** [keep-starknet-strange/madara#1325]
### Introduction

We need an implementation for [JSON-RPC v0.5.1](https://github.com/starkware-libs/starknet-specs/blob/v0.5.1/api/starknet_api_openrpc.json#L3273) `ExecutionResources` field.

Currently, on Madara, there are two implementations for `ExecutionResources`:

1. The one from the Blockifier [here](https://github.com/keep-starknet-strange/blockifier/blob/3108164451fb5a429cc8af5934f646a69393f119/crates/blockifier/src/execution/entry_point.rs#L63)
2. A simple `ExecutionResourcesWrapper` around the [execution wrapper from starknet.rs](https://github.com/xJonathanLEI/starknet-rs/blob/6cadb198644cf5e942187896c2e6bb3ecc9edc6e/starknet-core/src/types/codegen.rs#L769), recently implemented to address the ExecutionResources field from v0.5.1.

### Solution

This presents us with three options:

1. Modify the `ExecutionResources` implementation from the Blockifier to meet our needs (JSON-RPC schema + encode/decode compatibility).
2. Expand the `ExecutionResourcesWrapper` in Madara to support encode/decode + ensure compatibility with the Blockifier's implementation.
3. Synchronize the latest versions of the Starknet API containing an `ExecutionResources` [field](https://github.com/starkware-libs/starknet-api/blob/ef97dee3db911177b17efb8f8b087cebe51f4f15/src/transaction.rs#L646), make it no-std, and ensure compatibility with starknet.rs as well as JSON-RPC compatibility.

While I was writing this issue, I realized that clearly the best option was to implement this field in Madara, thus resolving step 3. I am turning this into an issue, please comment below with any questions or if you want to take it.

**Comment by tdelabro** [comment]
So what will be the flow?

| Runtime | RuntimeAPI |Client | RPC response |
| ---|---|---|---|
| execution -> BlockifierExecutionRessource | ??? | ??? | StarknetRPCExecutionRessource|

**Comment by antiyro** [comment]
So the goal of this issue would be to keep the same `BlockifierExecutionRessource` where it is declared and add to it a conversion into a new `StarknetRPCExecutionRessource` (wrapping `StarknetRsExecutionResources`) encode/decode compatible that will be located on the `mc-rpc` crate to fill out the trace apis.

**Comment by tdelabro** [comment]
I don't think you should have a wrapper type. 
Just create another with the same fields.

So the flow would be:


| Runtime | RuntimeAPI |Client | RPC response |
| ---|---|---|---|
| execution -> BlockifierExecutionRessource | OurCustomExecutionRessourceType | OurCustomExecutionRessourceType | StarknetRPCExecutionRessource|

??

**Comment by tdelabro** [comment]
Also what is the RPC route that need to return that struct?

**Comment by antiyro** [comment]
The trace api rpc methods like estimate fee and simulate tx

**Comment by antiyro** [comment]
@ybensacq

**Comment by antiyro** [comment]
> Runtime	RuntimeAPI	Client	RPC response
> execution -> BlockifierExecutionRessource	OurCustomExecutionRessourceType	OurCustomExecutionRessourceType	StarknetRPCExecutionRessource

For now if I'm not mistaken the execution ressource is unchanged on the whole code base but converted in the Starknet rpc response, it would be more like:

Runtime | RuntimeAPI | Client | RPC response
-- | -- | -- | --
execution -> BlockifierExecutionRessource | BlockifierExecutionRessource | BlockifierExecutionRessource | BlockifierExecutionRessource -> StarknetRPCExecutionRessource

**Comment by ybensacq** [comment]
@antiyro  I started to work on this one, can you assign to me please?

**Comment by antiyro** [comment]
solved by @ybensacq here: https://github.com/antiyro/madara/pull/1
