### ISSUE TITLE
dev: Blockifier upstream synchronization

### ISSUE THREAD

**Issue by antiyro** [keep-starknet-strange/madara#1329]
Should'nt we synchronize with upstream since we are around 400 commits behind and a lot of versions were implemented to Starknet mainnet since last sync?

<img width="1021" alt="Capture d’écran 2023-12-23 à 11 22 46" src="https://github.com/keep-starknet-strange/madara/assets/74653697/ca08dd07-9a7f-4849-8fa3-7b71c97457ec">

**Comment by jerrybaoo** [comment]
In my opinion, Madara forked the Blockifier project solely to implement the Parity Codec interface for certain structures within it. If that's the case, why not directly implement the Codec interface for these structures within the Madara project by wrapping them?

**Comment by apoorvsadana** [comment]
Closing this in favor of #1430
