### ISSUE TITLE
dev: check that class exist before using it in `BuildGenesisConfig`

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1345]
### Problem

```rust
    #[pallet::genesis_build]
    impl<T: Config> BuildGenesisConfig for GenesisConfig<T> {
        fn build(&self) {
            <Pallet<T>>::store_block(0);
            frame_support::storage::unhashed::put::<StarknetStorageSchemaVersion>(
                PALLET_STARKNET_SCHEMA,
                &StarknetStorageSchemaVersion::V1,
            );

            for (class_hash, contract_class) in self.contract_classes.iter() {
                ContractClasses::<T>::insert(class_hash, contract_class);
            }

            for (sierra_class_hash, casm_class_hash) in self.sierra_to_casm_class_hash.iter() {
                CompiledClassHashes::<T>::insert(sierra_class_hash, CompiledClassHash(casm_class_hash.0));
            }

            for (address, class_hash) in self.contracts.iter() {
                ContractClassHashes::<T>::insert(address, class_hash);
            }

            for (key, value) in self.storage.iter() {
                StorageView::<T>::insert(key, value);
            }

            LastKnownEthBlock::<T>::set(None);
            // Set the fee token address from the genesis config.
            FeeTokenAddress::<T>::set(self.fee_token_address);
            SeqAddrUpdate::<T>::put(true);
        }
    }
```

Here we "declare" classes:
```
 for (class_hash, contract_class) in self.contract_classes.iter() {
        ContractClasses::<T>::insert(class_hash, contract_class);
}
```

Here we map them to their sierra
```
for (sierra_class_hash, casm_class_hash) in self.sierra_to_casm_class_hash.iter() {
       CompiledClassHashes::<T>::insert(sierra_class_hash, CompiledClassHash(casm_class_hash.0));
}
```

And here we "deploy" new contracts:
```
            for (address, class_hash) in self.contracts.iter() {
                ContractClassHashes::<T>::insert(address, class_hash);
            }
```

It would be nice for "declare", "map ot sierra" and "deploy" to make sure we are refering to `ContractClass` that actually exist. Meaning that have been stored in the first storage `ContractClasses`.

### What to do?
Add those checks, panic if we are using a `ClassHash` which don't have been declared before in the first `for loop`

**Comment by kfastov** [comment]
I would like to take this

**Comment by tdelabro** [comment]
Rather than checking it is in the storage. You can check it is in the in-memory array. I will probably be a bit more efficient

**Comment by kfastov** [comment]
I've implemented it using `ContractClasses::<T>::contains_key(class_hash)`, I am a bit worried about O(n^2) complexity in the case of array, not sure how storage lookup is implemented though. I will test this simple implementation compared to an in-memory array and choose the best option

**Comment by tdelabro** [comment]
I think the storage lookup is a kind of hashmap. Due to caching. So probably better performances.
Forget what I said

**Comment by tdelabro** [comment]
Hey, @kfastov, do you have an ETA for opening a PR?  understood you were quite close

**Comment by kfastov** [comment]
Hey, sorry for delaying it so hard, will open PR tomorrow (Jan 21st)
