### ISSUE TITLE
dev: replace md5

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1348]
We use md5 to make sure of our genesis-assets integrity.
But this hashing function had been broken in the past. Maybe we should replace it with something more solid

**Comment by fishseabowl** [comment]
Which is better: SHA-3 or BLAKE2? Thanks!

**Comment by tdelabro** [comment]
@LucasLvy do you have a recomendation here?

**Comment by LucasLvy** [comment]
sha3

**Comment by tdelabro** [comment]
@fishseabowl you want to work on this?
