### ISSUE TITLE
feat: Access support for pending Madara state 

### ISSUE THREAD

**Issue by antiyro** [keep-starknet-strange/madara#1354]
# feat: Access support for pending Madara state

### Current behavior

Block times on `mainnet` can be prohibitively long for certain applications. As a workaround, Starknet added the concept of a `pending` block which is the block currently under construction. Currently Madara does not support pending state and only serves finalized state. The problem is that as defined in the [JSON-RPC specs](https://github.com/starkware-libs/starknet-specs/blob/v0.6.0/api/starknet_api_openrpc.json) pending blocks are needed for full Starknet compatibility.

It is important to maintain full compatibility because dapps, wallets are based on those universal specs. Specially on pending state.

**Comment by tdelabro** [comment]
We agree that pending tx are txs that are in the tx_pool for madara nodes, didn't we?
So we could just use the dedicated substrate API for this.

So I guess I can close this one @antiyro?

**Comment by antiyro** [comment]
Yes lets open a proper issue.

**Comment by tdelabro** [comment]
> We agree that pending tx are txs that are in the tx_pool for madara nodes, didn't we? So we could just use the dedicated substrate API for this.
> 
> So I guess I can close this one @antiyro?

So I was wrong. We will have to go find the one in the block being built.

**Comment by antiyro** [comment]
I opened this one which is more detailed: https://github.com/keep-starknet-strange/madara/issues/1405
