### ISSUE TITLE
feat(rpc): Implement starknet_traceTransaction RPC call

### ISSUE THREAD

**Issue by Tbelleng** [keep-starknet-strange/madara#1367]
**feat(rpc): Implement starknet_traceTransaction**

This PR aims to implement starknet_traceTransaction rpc call introduced in v0.4.0-rc1 according to the v0.5.1 RPC specs described in https://github.com/keep-starknet-strange/madara/issues/1291

starknet_traceTransaction

For a given executed transaction, return the trace of its execution, including internal calls

**Arguments**

    transaction_hash : The hash of the transaction to trace

**Return**

Returns the function call trace of the transaction designated by the given hash

**Errors**

This function might return the following errors:

    TXN_HASH_NOT_FOUND - The specified transaction could not be found.
    NO_TRACE_AVAILABLE - No trace found for the specified transaction.

**Comment by tdelabro** [comment]
This is different from #1372 ? Or they are the same?

**Comment by Tbelleng** [comment]
Yeah i will do it its ok for you, i guess we can also reuse some element introduced by simulate_transaction.

**Comment by tdelabro** [comment]
Sure, that would be perfect. Lets wait for #1372 then
