### ISSUE TITLE
dev: Better estimate fee test

### ISSUE THREAD

**Issue by 0xLucqs** [keep-starknet-strange/madara#1368]
Instead of comparing hardcoded values, execute the transaction and compare the actual fees with the estimated fees

**Comment by kenkomu** [comment]
Hello, can I take this?

**Comment by tdelabro** [comment]
@kenkomu sure!!

Do you have a clear view on how to do that?

I think @LucasLvy was talking about tests in `starknet-rpc-test/estimate_fee.rs` but it would certainly be cool if you could also add such a test in the pallet tests.

**Comment by tdelabro** [comment]
@kenkomu you don't seem to be active. Comment again if you want to work on it again

**Comment by fishseabowl** [comment]
@tdelabro could I take it? Thanks

**Comment by kenkomu** [comment]
> @kenkomu you don't seem to be active. Comment again if you want to work on it again

I want to work on it again.

**Comment by tdelabro** [comment]
@kenkomu What is your estimated ETA?

**Comment by kenkomu** [comment]
What do you mean by ETA?
Can you guide me on how to tackle the task?

**Comment by tdelabro** [comment]
@kenkomu Estimated Time of Arrival: when do you think you will be finished? We gave you the issue two weeks ago and you haven't started it yet, so this time I would like you to commit to a schedule. 

> Instead of comparing hardcoded values, execute the transaction and compare the actual fees with the estimated fees

Lucas was referring tho this test:

starknet-rpc-test/estimate_fee.rs 
```rust
#[rstest]
#[tokio::test]
async fn works_ok(madara: &ThreadSafeMadaraClient) -> Result<(), anyhow::Error> {
    let rpc = madara.get_starknet_client().await;

    let tx = BroadcastedInvokeTransaction {
        max_fee: FieldElement::ZERO,
        signature: vec![],
        nonce: FieldElement::ZERO,
        sender_address: FieldElement::from_hex_be(ACCOUNT_CONTRACT).unwrap(),
        calldata: vec![
            FieldElement::from_hex_be(TEST_CONTRACT_ADDRESS).unwrap(),
            get_selector_from_name("sqrt").unwrap(),
            FieldElement::from_hex_be("1").unwrap(),
            FieldElement::from(81u8),
        ],
        is_query: true,
    };

    let invoke_transaction = BroadcastedTransaction::Invoke(tx.clone());

    let invoke_transaction_2 =
        BroadcastedTransaction::Invoke(BroadcastedInvokeTransaction { nonce: FieldElement::ONE, ..tx });

    let estimates =
        rpc.estimate_fee(&vec![invoke_transaction, invoke_transaction_2], BlockId::Tag(BlockTag::Latest)).await?;

    // TODO: instead execute the tx and check that the actual fee are the same as the estimated ones
    assert_eq!(estimates.len(), 2);
    assert_eq!(estimates[0].overall_fee, 420);
    assert_eq!(estimates[1].overall_fee, 420);
    // https://starkscan.co/block/5
    assert_eq!(estimates[0].gas_consumed, 0);
    assert_eq!(estimates[1].gas_consumed, 0);

    Ok(())
}
```
As you can see at the end we do `assert_eq` against hardcoded values. A better approach, as said by lucas would be to execute the transaction and then compare the fee taken during the execution with those estimated by the call to `estimate_fee` and make sure they match.

Does it sound doable?

**Comment by kenkomu** [comment]
Yes, it sounds doable. Can you give me a week to complete it?  I will be reaching out to you frequently.

**Comment by tdelabro** [comment]
@kenkomu are you still working on this?

**Comment by kenkomu** [comment]
No, sorry for the late reply.

**Comment by tdelabro** [comment]
Don't worry no problem

**Comment by fishseabowl** [comment]
@tdelabro could I take it? Thanks

**Comment by tdelabro** [comment]
sure. Go ahead @fishseabowl

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
