### ISSUE TITLE
dev: Get the block status from the actual block in `get_block_with_tx_hashes`

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/madara#1369]
Currently we hardcode `AcceptedOnL2`, get the block status from the block itself.

**Comment by azurwastaken** [comment]
would like to take a look at this one if possible

**Comment by tdelabro** [comment]
@azurwastaken sure!

I think you can use the `MessagingDb::last_synced_l1_block_with_event` method to get the last block number we know for sure has been seen on L1.
If the block requested has a block number lower or equal to that one, it is `AcceptedOnL1`. 

If not, but we are aware of this block, it's `AcceptedOnL2`.
