### ISSUE TITLE
feat: configure the chain id in the genesis file.

### ISSUE THREAD

**Issue by jerrybaoo** [keep-starknet-strange/madara#1387]
# Feature Request

**Describe the Feature Request**

As an AppChain stack, Madara should allow appchain developers to customize the chain id. However, currently, the chain id is hardcoded in the pallet config.

**Describe Preferred Solution**

Configure the chain id in the genesis file.
Then set the chain id in `BuildGenesisConfig` of `pallet_starknet`. Just like setting the `FeeTokenAddress`.

``` #[pallet::genesis_build]
    impl<T: Config> BuildGenesisConfig for GenesisConfig<T> {
        fn build(&self) {
          
            FeeTokenAddress::<T>::set(self.fee_token_address);
            SeqAddrUpdate::<T>::put(true);
        }
  }
```

**Describe Alternatives**

**Related Code**

chain id hard code: [https://github.com/keep-starknet-strange/madara/blob/main/crates/runtime/src/pallets.rs#L48]()

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

Yes

**Comment by apoorvsadana** [comment]
@jerrybaoo, so can I assign this issue to you?

**Comment by jerrybaoo** [comment]
Yes, you can assign this issue to me.

**Comment by apoorvsadana** [comment]
Sure, assigned!

**Comment by apoorvsadana** [comment]
Hey @jerrybaoo, any progress on this?

**Comment by MrishoLukamba** [comment]
> Hey @jerrybaoo, any progress on this?

If @jerrybaoo is not active , I can take this fast @apoorvsadana

**Comment by jerrybaoo** [comment]
Sorry for not contributing code to this issue. Some unexpected situation caused me to have no extra time to contribute code. If you have any questions about this issue. I'll answer as best I can. @apoorvsadana @MrishoLukamba

**Comment by MrishoLukamba** [comment]
madara cannot compile. Issues on the patched dependency, ( ring-vrf)

**Comment by MrishoLukamba** [comment]
Some outside work activities caught up on me. But will push some commit today
