### ISSUE TITLE
feat(rpc): Support real highest block in starknet_syncing

### ISSUE THREAD

**Issue by antiyro** [keep-starknet-strange/madara#1388]
Currently when you call the `starknet_syncing` method:

```
curl --request POST \
     --url https://starknet-mainnet.g.alchemy.com/v2/docs-demo \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "starknet_syncing"
}
'
```

The `highest_block_num` and `highest_block_hash` are equal to the last synced block hash/num whi
le according to the current [Starknet JSON-RPC specs](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json#L1086) they should be equal to the highest hash/num of the network.

We need to think about an implementation fetching the highest finalized block. According to the telemetry this is a known value within the network:

<img width="248" alt="Capture d’écran 2024-01-22 à 11 38 21" src="https://github.com/keep-starknet-strange/madara/assets/74653697/5fb846be-ef9c-4271-bceb-f7a00675bc0c">

**Comment by tdelabro** [comment]
```
"highest_block_hash": {
                        "title": "Highest block hash",
                        "description": "The hash of the estimated highest block to be synchronized",
                        "$ref": "#/components/schemas/BLOCK_HASH"
                    },
```
Which mean the head of the chain. Like the highest block the node knows about and will synchronize to. It does not mention finalization (which for starknet mean l1 settlement).

And we are using ` self.client.info().best_number` which is exactly that for substrate. The highest known block.

I don't think there is an issue there.

**Comment by tdelabro** [comment]
best finalized block <= best block

**Comment by hhamud** [comment]
Can I be assigned to this?

**Comment by apoorvsadana** [comment]
@antiyro should we close this?
