### ISSUE TITLE
dev: struct based error handling in client/data-availablity crate

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1394]
Right now we use `anyhow`. That's okay but we can improve our codebase by using struct based errors types

**Comment by peyha** [comment]
Can I take this one ?

**Comment by tdelabro** [comment]
Sure @peyha.
Try your best to give us comprehensive error handling. Use `thiserror` on your errors types

**Comment by peyha** [comment]
Started working on it, happy to have some feedback @tdelabro

**Comment by tdelabro** [comment]
closed by #1406
