### ISSUE TITLE
feat(rpc): Support for pending state

### ISSUE THREAD

**Issue by antiyro** [keep-starknet-strange/madara#1405]
### Current Behavior

Block times on `mainnet` can be prohibitively long for certain applications. To address this, Starknet introduced the concept of a `pending` block, which is the block currently under construction.

Currently, Madara does not support pending state and only serves finalized state. However, as defined in the [JSON-RPC specs](https://github.com/starkware-libs/starknet-specs/blob/v0.6.0/api/starknet_api_openrpc.json), supporting pending blocks is necessary for full Starknet compatibility.

### Solution

1. **Identify RPC calls affected by this issue**:
   - `starknet_getBlockWithTxs`: Pending blocks can be called [here](https://github.com/starkware-libs/starknet-specs/blob/49665932a97f8fdef7ac5869755d2858c5e3a687/api/starknet_api_openrpc.json#L81).
   - `starknet_getBlockWithTxHashes`: Similar to the above, pending blocks [here](https://github.com/starkware-libs/starknet-specs/blob/49665932a97f8fdef7ac5869755d2858c5e3a687/api/starknet_api_openrpc.json#L50).
   - `starknet_getStateUpdate`: Pending state updates can be called [here](https://github.com/starkware-libs/starknet-specs/blob/49665932a97f8fdef7ac5869755d2858c5e3a687/api/starknet_api_openrpc.json#L124).
   - `starknet_getTransactionReceipt`: Pending transactions can be called [here](https://github.com/starkware-libs/starknet-specs/blob/49665932a97f8fdef7ac5869755d2858c5e3a687/api/starknet_api_openrpc.json#L353).

2. **Implementing the Solution**:
   - Determine if the `block_id` parameters correspond to `pending`.
   - Call the substrate `author_pendingExtrinsics` method to access the pending extrinsic data where blocks and transactions are added and encoded.
   - Identify how to decode them on the client side.
   - Format and return them as they are.

Please discuss under this issue the potential implications of such an implementation. We'll proceed with a simple implementation within Madara for `starknet_getBlockWithTxHashes` to gain a clearer understanding of how to proceed.

**Comment by MSghais** [comment]
I would love to take this one, please. 

Not sure that it's a good first issue, but want to think, and try.
I can get back later, and after I'll know if it's on my level of knowledge/skills, if I can do it, and have some ideas on how to do it.

**Comment by antiyro** [comment]
yes please feel free to explore it and comment under this issue, then we'll assign it to you! @MSghais

**Comment by bidzyyys** [comment]
I would be happy to take this issue @tdelabro

**Comment by antiyro** [comment]
I think @bidzyyys can take it since @MSghais is working on other stuff while acknowledging the codebase.

**Comment by bidzyyys** [comment]
@antiyro do I understand correctly that as a first step you want to see `starknet_getBlockWithTxHashes` that is 
defined here: 
- [interface](https://github.com/keep-starknet-strange/madara/blob/main/crates/client/rpc-core/src/lib.rs#L120) 
- [impl](https://github.com/keep-starknet-strange/madara/blob/main/crates/client/rpc/src/lib.rs#L840)

**Comment by bidzyyys** [comment]
@tdelabro @antiyro 
In my opinion, instead of using Substrate RPC `author_pendingExtrinsics`, I would suggest providing RPC call directly to `Pallet Starknet` allowing fetching pending transactions directly from the pallet's storage (e.g.`pub(super) type Pending<T: Config> = StorageValue<_, Vec<Transaction>, ValueQuery>;`). 

I think that we are here interested in getting only Starknet's extrinsic, not the other (like Substrate's internal). 

Let me know what you think about it and which direction should I go. I am fine with both ways.

**Comment by tdelabro** [comment]
When you read the storage from a runtimeAPI, you provide a block hash to specify at which state of the chain you want to read. There is no hash for a block being produced. It is not stored with the other ones, it doesn't exist, yet, as far as this part of the substrate framework is concerned

**Comment by bidzyyys** [comment]
@tdelabro fair point, so your suggest going with `author_pendingExtrinsics` ?

**Comment by tdelabro** [comment]
It was @apoorvsadana suggestion I believe.
My solution was to go deep into substrate and read from there:
```rust
/// Utility for building new (valid) blocks from a stream of extrinsics.
pub struct BlockBuilder<'a, Block: BlockT, A: ProvideRuntimeApi<Block>, B> {
	extrinsics: Vec<Block::Extrinsic>,
	api: ApiRef<'a, A::Api>,
	version: u32,
	parent_hash: Block::Hash,
	backend: &'a B,
	/// The estimated size of the block header.
	estimated_header_size: usize,
}
```
in client/block-builder/src/lib.rs.
But it involves at least a custom block builder lib, and probably even forking substrate (something we will do anyway for https://github.com/keep-starknet-strange/madara/pull/1407

If `author_pendingExtrinsics` is easier, you can go with it. Even if a bit less performant, we will be fine for now

**Comment by bidzyyys** [comment]
yep, that is my attitude right now.
