### ISSUE TITLE
dev: cleanup da_db

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1408]
In `crates/client/db/src/da_db.rs` we use the `DaDb` to store information about proving jobs. One per block.
Once the blocks are proved on l1, we can remove those jobs from our DB.

## TODO
Listen to l1.
When a new bunch of blocks is proven, read `last_proven_block`, find all the block hash for blocks since last_proven, remove their jobs from db, and call `update_last_proven_block`.
It has to be done before updating the last proven block. Ideally in the same function.

**Comment by MSghais** [comment]
Can I take this one, please?

Need to be deep in the code before doing others' PR.

I think that's can help me to move to this PR: 
https://github.com/keep-starknet-strange/madara/issues/1405

**Comment by tdelabro** [comment]
Sure. Contact us on telegram if you need help. Don't stay stuck on something you don't understand or don't know how to find in the codebase

**Comment by tdelabro** [comment]
Not ready yet

**Comment by dhirajs0** [comment]
Hi, can I take this issue ? 
@tdelabro

**Comment by tdelabro** [comment]
@dhirajs0 sorry it's still not ready to be done

**Comment by dhirajs0** [comment]
It's fine, thank you for the update.

**Comment by tdelabro** [comment]
not relevant anymore as we are moving the proving flow out of madara repo
