### ISSUE TITLE
feat(rpc): Implement testing suit for estimate message fee method

### ISSUE THREAD

**Issue by antiyro** [keep-starknet-strange/madara#1412]
## feat(rpc): Implement testing suit for estimate message fee method

Please implement tests for the `starknet_estimateMessageFee` method as implemented [here](https://github.com/keep-starknet-strange/madara/blob/main/crates/client/rpc/src/lib.rs#L1007) and referenced in the official [JSON-RPC specs](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json#L643)

**Comment by Tbelleng** [comment]
I can take it sir !
