### ISSUE TITLE
dev: Refactor Eth config used in settlement/messaging/DA crates

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/madara#1413]

**Comment by apoorvsadana** [comment]
@anshalshukla is wokring on this, has anyone else picked it up already?

**Comment by tdelabro** [comment]
@m-kus was about to work on it. I wasn't aware of @anshalshukla, it there another issue about this?

**Comment by apoorvsadana** [comment]
Not really, so he also just started today.

**Comment by tdelabro** [comment]
So he should keep working on it. I have other tasks for m-kus no worries. He just know this part very well.
