### ISSUE TITLE
dev: optimize tx trace creation

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1417]
in `crates/client/rpc/src/trace_api.rs`, `tx_execution_infos_to_simulated_transactions` will call `tx_execution_infos_to_tx_trace` in a loop, that will do multiple recursive calls to `try_get_funtion_invocation_from_call_info`.
For each one of these calls, this code will be executed:
```rust
    // Blockifier call info does not give use the class_hash "if it can be deducted from the storage
    // address". We have to do this deduction ourselves here
    let class_hash = if let Some(class_hash) = call_info.call.class_hash {
        class_hash.0.into()
    } else {
        let class_hash = storage_override
            .contract_class_hash_by_address(substrate_block_hash, call_info.call.storage_address)
            .ok_or_else(|| TryFuntionInvocationFromCallInfoError::ContractNotFound)?;

        FieldElement::from_byte_slice_be(class_hash.0.bytes()).unwrap()
    };
```
This means we will go read the cold storage on disk every time the class hash can be deduced. There is a really high probability of going there to read the same value twice or more.
We can improve performance by passing initializing a cache at the top level and passing it down to every method I listed, if we miss we go read the disk and insert the value in our cache.
I think such a cache can be implement as a HashMap, owned by the top level function and passed by reference.

**Comment by fishseabowl** [comment]
@tdelabro could I take this? Thanks
