### ISSUE TITLE
dev: E2E test scenario for bridging funds from L1 to L2 and backdev: 

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1419]
Write a single e2e test executing this scenario
- user1 bridge funds from l1 to l2
- user2 transfer funds to user2 on l2
- user2 withdraw funds from l2 to l1 and then from the corecontract to it’s address

I guess bridging from l1 to l2 will require using `Starkgate`. It should be added to zaun

**Comment by anshalshukla** [comment]
Yeah, started looking into it today. You can assign this to me.

**Comment by apoorvsadana** [comment]
closed with #1512
