### ISSUE TITLE
dev: always spawn `commitment-state-diff-worker`

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#1428]
So we are not able to correctly answer the rpc.
Two solutions:
- always spawn `commitment-state-diff` worker and store them in db
- if state-diff-not in db, simulate the block in the runtime and get the state diff out of this 

@apoorvsadana @antiyro @EvolveArt wdyt?

_Originally posted by @tdelabro in https://github.com/keep-starknet-strange/madara/pull/1378#discussion_r1473110822_
            
**Expected Behavior**

The `commitment-state-diff-worker` should always be spawned wether there is a da layer or not. 
The option can then be removed from the rpc tests CI workflow.

**Comment by apoorvsadana** [comment]
I think option 1 makes more sense because

1. (2) would take a lot of time and unnecessary call the runtime
2. I see most app chains starting with a DA layer in the near future

What are the advantages of doing (2)?

**Comment by tdelabro** [comment]
> What are the advantages of doing (2)?

Store less data on disk

**Comment by apoorvsadana** [comment]
> Store less data on disk

So if we have a separate service for DA and full nodes will serve read calls, then the ideal solution I guess is that full nodes always have it running and validators do not build the state diff at all? However, for now, till we are doing DA via Madara I think (1) would be good imo. But what do you'll think

**Comment by tdelabro** [comment]
Deoxys reported going from 75Go for 300k block to 185Go for 140k blocks when they started storing the state updates.
It's non-negligible.

**Comment by EvolveArt** [comment]
> Deoxys reported going from 75Go for 300k block to 185Go for 140k blocks when they started storing the state updates. It's non-negligible.

It's also a concern that are having full nodes in public starknet with the higher throughput.

**Comment by tdelabro** [comment]
As discussed: not planned
