### ISSUE TITLE
dev: scale-codec in blockifier & starknet-api main

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1430]
Since https://github.com/keep-starknet-strange/madara/pull/1407 we are able to execute std only code in the runtime. Meaning we are losing the use of our blockifier/starknet-api/cairo-vm forks. 
Still, we cannot use the libs directly yet, because we need a lot of the types defined there to implement `parity-scale-codec::{Encode, Decode}`.
Those impl are already done in our branches on our forks, but we need them on upstream/main now.

That is the purpose of this issue: open PR to the upstream repos, where you add a `parity-scale-codec` feature and impl/derive the trait (mostly copy-paste from our branch) on every type defined there.

**Comment by bidzyyys** [comment]
@tdelabro I can take this one

**Comment by jerrybaoo** [comment]
I believe this issue is an important prerequisite for upgrading the Cairo and RPC versions. I'd like to know how much work is left to complete. Do we need more people to speed things up?

**Comment by tdelabro** [comment]
It most likely will stay in our forks for a bit more. But most types have proper impl at this point

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
