### ISSUE TITLE
bug: git action Run Rpc tests without cache, some tests fail

### ISSUE THREAD

**Issue by fishseabowl** [keep-starknet-strange/madara#1439]
# Bug Report

**Madara version:**

**Current behavior:**
In PR #1420  checks, some tests failed due to the following code returning Err
https://github.com/keep-starknet-strange/madara/blob/7900c0b884ee3fb978711ff65b19e98f0c143c03/starknet-rpc-test/src/utils.rs#L173

Details:
https://github.com/keep-starknet-strange/madara/actions/runs/7806424794/job/21292853182?pr=1420
running 4 tests
test fails_already_declared ... FAILED
test fail_validation_step ... FAILED
test works_with_storage_change ... FAILED
test fail_execution_step_with_no_storage_change ... FAILED

failures:

---- fails_already_declared stdout ----
error: test failed, to rerun pass `--test starknet_add_declare_transaction`
thread 'fails_already_declared' panicked at starknet-rpc-test/src/utils.rs:173:95:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }

---- fail_validation_step stdout ----
thread 'fail_validation_step' panicked at starknet-rpc-test/src/utils.rs:173:95:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- works_with_storage_change stdout ----
thread 'works_with_storage_change' panicked at starknet-rpc-test/src/utils.rs:173:95:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }

---- fail_execution_step_with_no_storage_change stdout ----
thread 'fail_execution_step_with_no_storage_change' panicked at starknet-rpc-test/src/utils.rs:173:95:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }

failures:
    fail_execution_step_with_no_storage_change
    fail_validation_step
    fails_already_declared
    works_with_storage_change

**Expected behavior:**

Passed the test

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Comment by chop-pixel** [comment]
perhaps try modifying the test to handle the error slightly more gracefully as while also providing a more informative error message in such instances where the file cannot be opened:

let file_path = format!("{}/{}", env!("CARGO_MANIFEST_DIR"), path_to_sierra);
let file = std::fs::File::open(&file_path)
    .expect(&format!("Failed to open file at path: {}", file_path));

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
