### ISSUE TITLE
bug: creating a local testnet with multiple nodes fails using only flags

### ISSUE THREAD

**Issue by d-roak** [keep-starknet-strange/madara#1468]
# Bug Report

**Madara version:** v0.7.0

**Current behavior:** When trying to bootstrap a local testnet with multiple nodes, the nodes fail to connect with the validator node because of a genesis mismatch. Tested with chains `dev` and `local`.
![image](https://github.com/keep-starknet-strange/madara/assets/5263301/c3d0535b-ded7-497d-b06d-ad89060ca466)

**Expected behavior:** We should be able to run a local testnet while following the steps of this: https://docs.substrate.io/tutorials/build-a-blockchain/simulate-network/

**Steps to reproduce:** Check image in current behavior and the docs on the expected behavior

**Related code:** N/A

**Other information:** An alternative solution that works is creating a raw chainspec and pass it with the `--chain` flag. Another weird message we are getting is a genesis mismatch when passing a non-raw chainspec (the file is the same, so the genesis shouldn't mismatch)

**Comment by hhamud** [comment]
can I get assigned to this?

**Comment by apoorvsadana** [comment]
Assigned!
