### ISSUE TITLE
bug: fix contract serialisation

### ISSUE THREAD

**Issue by apoorvsadana** [keep-starknet-strange/madara#1469]
We've modified the Cairo VM form to remove `main_scope` as it should be according the main version - https://github.com/keep-starknet-strange/cairo-rs/pull/13/files

However, as a result of this change, main_scope is longer returned as a response when we deserialise the program from `get_class`. This causes the `work_ok_retrieving_class_for_contract_version_0` test to fail. This isn't a functionality change as before we used to just return an empty string and now we don't return anything. 

I observed that on Starknet mainnet, this field is usually `__main__`. As a part of this issue, we need to debug what needs to change so we can return the correct value to the user (or if it's ok to skip this completely).

**Comment by fishseabowl** [comment]
@apoorvsadana can I take this? Thanks

**Comment by apoorvsadana** [comment]
Sure @fishseabowl, assigned

**Comment by fishseabowl** [comment]
@apoorvsadana Could you please help to review the PR #1523? Thanks
