### ISSUE TITLE
feat: submit state diff to the memory pages contract on Ethereum (sovereign DA mode)

### ISSUE THREAD

**Issue by m-kus** [keep-starknet-strange/madara#1480]
## Sovereign rollups

A sovereign rollup is a type of blockchain that publishes its transactions to another blockchain, typically for ordering and [data availability](https://celestia.org/glossary/data-availability/), but handles its own [settlement](https://celestia.org/learn/modular-settlement-layers/settlement-in-the-modular-stack/).

For ZK case in particular, sovereign rollups publish state diffs and execution proofs to DA layer, without on-chain verification. Instead, anyone running full node can verify proofs on their own and apply state diffs to obtain the latest rollup state. ZK rollups can have a bridge to the DA layer with the caveat that only full node operators can verify that a particular L1 message has been processed or that a particular L2 message has been emitted by the rollup.

Read more:
- https://celestia.org/learn/sovereign-rollups/an-introduction/#what-is-a-sovereign-rollup
- https://celestia.org/learn/sovereign-rollups/misconceptions/

## Ethereum as DA layer in sovereign mode

Starknet sovereign appchains using Ethereum as a DA layer would rely on the following contracts:
- Core contract, [sovereign](https://github.com/keep-starknet-strange/zaun/blob/main/src/StarknetSovereign.sol) version that does not verify state transition facts, just used for L1<>L2 messaging and block level tracking;
- Memory pages contract used for indexing transactions containing state diffs as calldata;
- Verifier contract, sovereign version (not yet available) that does not do verification & fact storing, but accepts full proofs (as calldata) instead.

The exact design is not yet determined (as of my knowledge), but the idea is that you should be able to sync a Madara node from scratch using that scheme (fetch, verify proof, apply diff, repeat).

Read more:
- https://docs.starknet.io/documentation/architecture_and_concepts/Network_Architecture/on-chain-data/
- https://github.com/keep-starknet-strange/zaun

## Step 1: publishing state diffs w/o proofs

In order to enable unverified state indexing it's enough to just populate state diffs. The syncing algorithm is [the one used in Starknet full nodes](https://docs.starknet.io/documentation/architecture_and_concepts/Network_Architecture/on-chain-data/#extract_from_ethereum) and implemented in #1224 #1296.

Note that since core contract is used for tracking the block number, settlement worker (which is currently manages that contract & L1<>L2 messaging in particular) should be adapted to wait for state diffs publication (this is applicable for non-sovereign mode as well). It's probably worth renaming settlement crate to "bridge" or to something else in order to avoid confusion.

**Comment by tdelabro** [comment]
state diff is not part of madara anymore https://github.com/keep-starknet-strange/madara/pull/1580
