### ISSUE TITLE
feat: robust DA service

### ISSUE THREAD

**Issue by apoorvsadana** [keep-starknet-strange/madara#1488]
Currently we've off chain workers in Madara that listen to new block changes and storage changes and accordingly submit DA jobs. We want to move this work away from the Madara sequencer itself and have a different service which polls on for new blocks and does the same thing. We want this service to be robust in the way that

- It can retry in case of submission failures
- Understand reorgs of the DA layer and resubmit blocks
- Batch DA submissions across multiple blocks

**Comment by rphmeier** [comment]
Maybe https://github.com/paritytech/orchestra would be useful. This is what we use in the Polkadot node to coordinate all off-chain work instead of off-chain workers.

**Comment by apoorvsadana** [comment]
Hey @rphmeier, thanks for the suggesting! Can you point me to the places where this is used if possible?

**Comment by rphmeier** [comment]
https://github.com/paritytech/polkadot-sdk/blob/master/polkadot/node/overseer/src/lib.rs

Each of the subsystems here is in the adjacent `node/core` or `node/network` directories. I've found this architecture is reasonably good for separating concerns and coordinating many moving pieces around chain updates.

**Comment by tdelabro** [comment]
da is not part of madara anymore since https://github.com/keep-starknet-strange/madara/pull/1580
