### ISSUE TITLE
bug: return actual execution resources in transaction receipt

### ISSUE THREAD

**Issue by apoorvsadana** [keep-starknet-strange/madara#1489]
Right now, getTransactionReceipt returns 0 for all transactions. Fix this to return the actual value

**Comment by anukkrit149** [comment]
I will pick this up.

**Comment by fishseabowl** [comment]
@apoorvsadana Can I take this? thanks

**Comment by tdelabro** [comment]
I think this is solved now.

And we have a test in `starknet-rpc-test/get_transaction_receipt.rs` `work_with_pending_invoke_transaction` that checks the trace exec resources are indeed the same as the real execution one
