### ISSUE TITLE
bug: DA PUBLISH ERROR(Celestia)

### ISSUE THREAD

**Issue by chappie1998** [keep-starknet-strange/madara#1490]
# Bug Report

**Madara version:**

 0.7.0

**Current behavior:**
Getting error while submitting the data on Celestia
on madara node side:- 
`2024-03-03 12:09:18 Failed to update the DA state: DA PUBLISH ERROR: celestia error: could not submit blob ErrorObject { code: ServerError(1), message: ": incorrect account sequence", data: None }`

on celestia node side:- `2024-03-03T12:48:31.414+0530    WARN    rpc     go-jsonrpc@v0.3.1/handler.go:444        error in RPC call to 'blob.Submit': : incorrect account sequence`

**Steps to reproduce:**

Following this tutorial, but I am using arabica testnet. https://docs.madara.build/da-layer/celestia

**Comment by Ndifreke000** [comment]
Things to check for

1. Concurrent Transactions: If you're sending multiple transactions at once from the same account, each transaction needs an incremented sequence number to avoid conflicts. Make sure your code handles this correctly.

2. Transaction Logs: Check the logs associated with the error for any patterns or specific transactions causing the mismatch. 

3. Celestia Configuration: Double-confirm that your Celestia setup matches the tutorial you're following. Make sure you're using the correct network and that all configuration parameters are set properly.

4. Transaction Preparation: Ensure you're building transactions correctly, including setting the sequence number using the appropriate method

**Comment by tdelabro** [comment]
DA is not part of madara anymore since https://github.com/keep-starknet-strange/madara/pull/1580
