### ISSUE TITLE
bug: l1 message is processed repeatedly

### ISSUE THREAD

**Issue by apoorvsadana** [keep-starknet-strange/madara#1504]
If an L1 message fails to be processed, it gets processed again when you restart the node.

**Comment by prtk418** [comment]
@apoorvsadana is this available to be picked up?

**Comment by apoorvsadana** [comment]
Sure @prtk418, assigned

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
