### ISSUE TITLE
feat: test cases to check contract storage reverts for failed transactions

### ISSUE THREAD

**Issue by apoorvsadana** [keep-starknet-strange/madara#1520]
Currently, the Madara storage doesn't revert storage changes in case a smart contract transaction fails. I am referring to execution failures here, for example, you add a panic! inside the function call of a smart contract. Not other failures like missing fees etc. This should mostly be fixed in a few days. However, we need a good test case for this to ensure we don't miss this later on.

**Comment by swetshaw** [comment]
I would like to take this up
