### ISSUE TITLE
Migrate ethers-rs to alloy-rs

### ISSUE THREAD

**Issue by prtk418** [keep-starknet-strange/madara#1528]
ethers-rs is being deprecated and alloy-rs has some new features we would benefit from, ex: figuring if a block is finalised or not. ref - https://github.com/gakonst/ethers-rs/issues/2667

**Comment by dieriba** [comment]
I'd like to take this one.

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
