### ISSUE TITLE
Unable to build with personal fork of massa's polkadot-sdk

### ISSUE THREAD

**Issue by azurwastaken** [keep-starknet-strange/madara#1531]
I was trying to work on the issue #1484 and i need to do some changes in the polkadot sdk.

So I forked the repo and then updated madara's cargo.toml to make it point to my own fork instead of the massa one but i encountered a rust type error with FixedU128 of sp_arithmetic crates because this one is also pulled by the blockifier.

I managed to fix by patching the Cargo.toml like this :

`[patch.'https://github.com/massalabs/polkadot-sdk']
sp-arithmetic = { git = "https://github.com/azurwastaken/polkadot-sdk", branch = "release-polkadot-v1.3.0-std", default-features = false, features = ["std"] }`

But I was wondering how to make it easier for us to do some change in the polkadot sdk and test it with madara.

I don't think i can make a pr with my fix but at least we can put it in a dev doc or something like this.

What do you think ?

**Comment by hhamud** [comment]
I think bringing it within this repo using git submodules would make it easier to develop on.

**Comment by tdelabro** [comment]
@apoorvsadana @EvolveArt any opinion on this one?

**Comment by tdelabro** [comment]
@AbdelStark was pushing for the removal of sub-repos, but I find them useful.
What do you all think?

**Comment by apoorvsadana** [comment]
I don't think we're using them in anyway right now to be honest. I would advocate for removing it as well.

**Comment by tdelabro** [comment]
will be solved with #1596
