### ISSUE TITLE
bug: `starknet_call` errs if contract nonexistent

### ISSUE THREAD

**Issue by neelkamath** [keep-starknet-strange/madara#1537]
# Bug Report

**Madara version:**

Whichever version [52.7.206.208:9944](https://github.com/keep-starknet-strange/madara/discussions/553) is running

**Current behavior:**

Calling a nonexisting contract causes the API to return an internal server error instead of a user-level err msg.

**Expected behavior:**

The API should respond with a relatively descriptive err message instead of seeming like there's a bug in the server.

**Steps to reproduce:**

Executing the following:

```sh
curl -X POST --location "http://52.7.206.208:9944" \
    -H "Content-Type: application/json" \
    -d '{
          "id": 1,
          "jsonrpc": "2.0",
          "method": "starknet_call",
          "params": [
            {
              "contract_address": "0x1",
              "entry_point_selector": "0x1",
              "calldata": [
              ]
            },
            "latest"
          ]
        }'
```

Results in the following internal server error response:

```json
{
  "jsonrpc": "2.0",
  "error": {
    "code": 500,
    "message": "Internal server error"
  },
  "id": 1
}
```

Whereas executing the same request on Juno gives a descriptive error message:

```json
{
  "jsonrpc": "2.0",
  "error": {
    "code": 40,
    "message": "Contract error",
    "data": {
      "revert_error": "Requested contract address ContractAddress(PatriciaKey(StarkFelt(\"0x0000000000000000000000000000000000000000000000000000000000000001\"))) is not deployed."
    }
  },
  "id": 1
}
```

**Comment by hhamud** [comment]
can I take this one? @apoorvsadana

**Comment by apoorvsadana** [comment]
Sure, assigned @hhamud

**Comment by hhamud** [comment]
I can definitely see that the errors need to return more information so I will refactor this but can you describe what actually doing? As I get this error when querying the jsonrpc when running the madara rpc locally
```shell
{"jsonrpc":"2.0","error":{"code":40,"message":"Contract error"},"id":1}
```
@neelkamath

**Comment by hhamud** [comment]
> > I can definitely see that the errors need to return more information so I will refactor this but can you describe what actually doing? As I get this error when querying the jsonrpc when running the madara rpc locally
> > ```shell
> > {"jsonrpc":"2.0","error":{"code":40,"message":"Contract error"},"id":1}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @neelkamath
> 
> If that's the response you get, then perhaps there's nothing to be done as it's already been fixed but the fix hasn't been deployed?

nah its still a bug as its supposed to tell you "Contract not found" for undeployed contract addresses. What happens here is that it fails to execute rather than failing on finding the contract class.

**Comment by hhamud** [comment]
> > > > I can definitely see that the errors need to return more information so I will refactor this but can you describe what actually doing? As I get this error when querying the jsonrpc when running the madara rpc locally
> > > > ```shell
> > > > {"jsonrpc":"2.0","error":{"code":40,"message":"Contract error"},"id":1}
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > @neelkamath
> > > 
> > > 
> > > If that's the response you get, then perhaps there's nothing to be done as it's already been fixed but the fix hasn't been deployed?
> > 
> > 
> > nah its still a bug as its supposed to tell you "Contract not found" for undeployed contract addresses. What happens here is that it fails to execute rather than failing on finding the contract class.
> 
> OK. I didn't actually understand your question "can you describe what actually doing?".

Its fine now, the errors just need to be refactored and the testnet updated.
