### ISSUE TITLE
bug: github CI failing due to starknet-js

### ISSUE THREAD

**Issue by hhamud** [keep-starknet-strange/madara#1549]
# Bug Report

**Madara version:**
Latest version on main

**Current behavior:**
The github ci tests are failing specifically due to the starknet-js tests failing.
Here are the specific logs: https://github.com/keep-starknet-strange/madara/issues/1549#issuecomment-2043547828

This is the specific repo at fault, https://github.com/keep-starknet-strange/sequencer-js-compatibility-tests

**Expected behavior:**
All tests should pass

**Steps to reproduce:**
Create a pull request and view the logs.

**Comment by princeibs** [comment]
Hi @hhamud, can I try this out?
Though the logs is not displaying from my end 
<img width="1680" alt="image" src="https://github.com/keep-starknet-strange/madara/assets/64266194/62a1d56a-c498-4bdf-a9eb-8d4c1e934a0d">

**Comment by hhamud** [comment]
@princeibs I can't assign anything but I am fine with you doing this. you would need to ask @apoorvsadana or @tdelabro for it to be assigned to via github. 

Also here is the log as a file.txt: [13_Run starknet-js compatibility tests _ test.txt](https://github.com/keep-starknet-strange/madara/files/14910419/13_Run.starknet-js.compatibility.tests._.test.txt)

and this is the specific github workflow file that is used. https://github.com/keep-starknet-strange/madara/blob/main/.github/workflows/starknet-js-tests.yml

**Comment by princeibs** [comment]
Alright sure. Will hop on it 🚀

**Comment by princeibs** [comment]
@apoorvsadana @tdelabro 
Can you assign me please?

**Comment by apoorvsadana** [comment]
Sure @princeibs, assigned to you.

**Comment by tdelabro** [comment]
@princeibs any news on this one?

**Comment by princeibs** [comment]
Facing a blocker with when starting up madara.
Running this command `cargo run --release -- --dev` throws the error below: 
<img width="808" alt="image" src="https://github.com/keep-starknet-strange/madara/assets/64266194/9cd0ecb9-059d-4d38-9414-b314c6112d9b">
@tdelabro

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
