### ISSUE TITLE
feat: support for STRK token as payment

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1571]
# Feature Request
Users should be able to pay their transaction using the STRK token

**Describe Preferred Solution**

1. Deploy the ERC20 smart contract at genesis, with correct storages values being set
2. Write pallet tests making sure that an user with 0 ETH but some STRK can submit TXs and be charged for it

**Related Code**

Edit the `set_infinite_tokens` (crates/pallets/starknet/src/tests/mod.rs) method so that it supports both ETH and STRK.

Both `configs/genesis-assets/genesis.json` and `crates/pallets/starknet/src/tests/mock/genesis.json` should be modified

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

**Comment by Ugo-X** [comment]
please can i take this?

**Comment by j1mbo64** [comment]
Hi, can i take this one ? @tdelabro

**Comment by tdelabro** [comment]
Sure @j1mbo64

**Comment by tdelabro** [comment]
Ask for help if you need on the Madara channel :)

I think you can do some TDD for this one, coz I don't know exactly what the changes should be tbh
