### ISSUE TITLE
dev: write tests for tx v3

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1574]
TXs V3 were added in the latest rebase.

We need both pallet and RPC tests for those.
Pallet to tests failure, edge-cases, and so on.
RPC to test the generic flow.
And Tx computation too

**Comment by Ugo-X** [comment]
please can i take this

**Comment by Gerson2102** [comment]
I would like to try this.

**Comment by tdelabro** [comment]
@Gerson2102 enjoy!

**Comment by Gerson2102** [comment]
@tdelabro Hello mate. Can you tell me the files where is located what i have to test? And if there is other tests that i can use as examples to help me with this issue please?

**Comment by Gerson2102** [comment]
I'm exploring the starknet-rpc-test directory, i dont know if those tests can help me or something.

**Comment by tdelabro** [comment]
@Gerson2102 
The exectution of tx is tested in files like `crates/pallets/starknet/src/tests/invoke_tx.rs`.
You can probably add a tests for each type of tx at the end of the dedicated file, using TxV3 for each one.

**Comment by tdelabro** [comment]
> I'm exploring the starknet-rpc-test directory, i dont know if those tests can help me or something.

I think you can add a TxV3 test file under RPC where you use all three declare, deploy and invoke txV3 consecutively in the same test.
This one should come after the `pallet` ones

**Comment by tdelabro** [comment]
Also can you write test for the txV3 hashes_computation please.
Under `crates/primitives/transactions/src/compute_hash.rs`
