### ISSUE TITLE
dev: Add a pallet test for estimate_fee that skip validation

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1575]
It is now possible to skip the validation phase during estimate_fee. Write a check that uses it to validate an otherwise invalid tx.
Do it in ` crates/pallets/starknet/src/tests/query_tx.rs`
Replace the usual `Default::default()` parameter by an use of the flag

**Comment by stevencartavia** [comment]
Hi, can I take this?

**Comment by tdelabro** [comment]
susre @stevencartavia

**Comment by tdelabro** [comment]
solved by #1584
