### ISSUE TITLE
Increase test coverage of `crates/node` crate.

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/madara#158]

**Comment by zarboqq** [comment]
Hey can I work on this :)

**Comment by abdelhamidbakhta** [comment]
hey @zarboq are you still working on this ?

**Comment by zarboq** [comment]
Hey yes sorry I had some other work to do I'm back on this

**Comment by abdelhamidbakhta** [comment]
> Hey yes sorry I had some other work to do I'm back on this

Thanks a lot

**Comment by abdelhamidbakhta** [comment]
Any news @zarboq ?

**Comment by drspacemn** [comment]
ping @zarboq ?
