### ISSUE TITLE
bug: Cairo 2.6.0 contracts fail to compile

### ISSUE THREAD

**Issue by SamrendraS** [keep-starknet-strange/madara#1581]
# Bug Report
On declaring contracts compiled with Cairo 2.6.0, Madara returns a 500 error

2024-04-30 12:44:13 Failed to convert BroadcastedTransaction to AccountTransaction: Failed to compile to Sierra    

The same issue can be resolved when compiling with Cairo 2.5.0.

**Steps to reproduce:**
[casm.contract_class.json](https://github.com/keep-starknet-strange/madara/files/15159781/casm.contract_class.json)
[sierra.compiled_contract_class.json](https://github.com/keep-starknet-strange/madara/files/15159782/sierra.compiled_contract_class.json)

The files linked above are ones generated with Cairo 2.6.0, attempting to declare them causes an error in Madara

**Comment by m-kus** [comment]
Sorry, missed the mention 🙈 

@tdelabro yes exactly, had the same issue, mentioned here https://github.com/keep-starknet-strange/madara/blob/main/crates/client/starknet-block-import/README.md#notes

IIRC one of the proposed solutions was to have multiple external compilers for the according version ranges.

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
