### ISSUE TITLE
Increase test coverage of `crates/runtime` crate.

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/madara#159]
Runtime Testing Reference:
- https://github.com/PureStake/moonbeam/tree/master/runtime/moonbeam/tests

**Comment by jobez** [comment]
i can work on this! 🛠️

**Comment by jobez** [comment]
> hey @jobez are you still willing to tackle this issue ?

yes! is it alright to still work on this now that it is closed or shall i look for another issue?

**Comment by abdelhamidbakhta** [comment]
> > hey @jobez are you still willing to tackle this issue ?
> 
> yes! is it alright to still work on this now that it is closed or shall i look for another issue?

It’s fine. I reopened it

**Comment by jobez** [comment]
Thank you sir! Will get on it 🖖

**Comment by Godspower-Eze** [comment]
Hey abdel, I am still on it.

**Comment by abdelhamidbakhta** [comment]
> Hey abdel, I am still on it.

sounds good!

**Comment by Godspower-Eze** [comment]
No ETA yet. I am still kinda understanding madara. But, I am on it

**Comment by somthn0somthn** [comment]
Is this still open and relevant?
