### ISSUE TITLE
feat(mainnet): Make Madara compatible with Starknet mainnet

### ISSUE THREAD

**Issue by antiyro** [keep-starknet-strange/madara#1593]
# feat(mainnet): Make Madara compatible with Starknet mainnet

Now that madara is compatible with Starknet mainnet specs. We should be able to easily store and retrieve state from mainnet.

### Pathfinder snapshot (#1592)

This is in theory feasible but practicaly impossible: Pathfinder storage uses sqlite which is a relational db rather than our key/value storage architecture so we would have to build a parser, analyser and storer to retrieve and reorganise without corruption of the state, and if we manage to do so substrate and rocksdb will go brrr and we'll probably need to modify some of it's checks during the building process which we dont want to.

### Fetch from the FGW/P2p

The real solution is simple and part of our roadmap, we must make Madara compatible as a Starknet sequencer, so we will add a `—mainnet` flag and a crate client side to fetch data from outside, like the way we are doing in Deoxys. This crate will allow you to able or disable state commitments checks in order to start from a desired block of mainnet using `—starting-block` so you could deep test any mainnet context within Madara.

We wanted to implement this connection with the FGW, but the more I'm think about it the more I think that we should wait to have a spec ready p2p crate client side (we'll kickstart it right after our release soon) eta before starknet cc

I'll provide the detailed architecture below once decided.

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
