### ISSUE TITLE
feat: create `get_snos_input(block_id: BlockId) -> Resutl<SnosInput,_>` rpc route

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1595]
# Feature Request

The prover will need to be able to data out of the chain for each block it want to prove.
To allow this, we will add a custom RPC `get_snos_input` that return the Input datastruct expected by SNOS.

**Describe Preferred Solution**

Add the rpc route in `crates/client/rpc-core/src/lib.rs` to the `MadaraRpcApi` trait.
Implement it in `crate/client`.

**Related Code**
Here is the SnosInput struct
https://github.com/keep-starknet-strange/snos/blob/01ed09975cb8b0cdb878f569fe2f8aac5c9e9a7a/src/io/input.rs#L18
Import it from this crate

**Comment by BillXJ** [comment]
can I work on this

**Comment by 0xSpyC** [comment]
Hello, can i pick this one ? @tdelabro

**Comment by tdelabro** [comment]
sure. It is not an easy one tho. Don't hesitate to ask for help on our telegram channel

**Comment by tdelabro** [comment]
@0xSpyC are you still working on this? It has been two weeks?

**Comment by 0xSpyC** [comment]
Yes, I'm still on it, sorry for the delay, it took me a while to figure out how the commitment fact is calculated, I'll do my best to deliver it quickly from now on. Is there anyone who has mastered the low-level state so they can tell me if my understanding is correct?

**Comment by tdelabro** [comment]
Sure, push your code in a draft PR and add your question there

**Comment by ocdbytes** [comment]
Hey @0xSpyC 

Are you still working on it ? If not I can take it up. As we are currently integrating the SNOS job in madara orchestrator we need this component.

**Comment by apoorvsadana** [comment]
@0xSpyC I am assigning this to @ocdbytes, let me know in case you've made any progress.

**Comment by 0xSpyC** [comment]
> Hey @0xSpyC 
> 
> Are you still working on it ? If not I can take it up. As we are currently integrating the SNOS job in madara orchestrator we need this component.

It's ok i understand

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
