### ISSUE TITLE
dev: remove submodules

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1596]
remove git submodules

**Comment by Gerson2102** [comment]
Can i get this please?

**Comment by Gerson2102** [comment]
So... in this issue i just have to delete this?:

```
[submodule "madara-infra"]
	path = madara-infra
	url = https://github.com/keep-starknet-strange/madara-infra
[submodule "madara-docs"]
	path = madara-docs
	url = https://github.com/keep-starknet-strange/madara-docs
[submodule "madara-tsukuyomi"]
	path = madara-tsukuyomi
	url = https://github.com/keep-starknet-strange/madara-tsukuyomi
```

**Comment by tdelabro** [comment]
<img width="920" alt="Screenshot 2024-05-07 at 08 39 00" src="https://github.com/keep-starknet-strange/madara/assets/34384633/76b88d10-12f7-4d5d-ad99-feb3782126a8">


The submodules are those 3 blue lines. You have to `rm` them too
