### ISSUE TITLE
bug: bring back l1 messaging

### ISSUE THREAD

**Issue by apoorvsadana** [keep-starknet-strange/madara#1599]
L1 messages were removed here #1580, we need to add it back. The l1 messages crate is there, just need to spawn the worker in service.rs and add the settlement_layer option in clap args

**Comment by jancris100** [comment]
Will like to take care of this one!

**Comment by apoorvsadana** [comment]
Hey @jancris100 have already started working on this? I actually have a PR under the way which needs the same thing so I can add it if you haven't already started

**Comment by jancris100** [comment]
I haven't started working on the issue, I was waiting for a response

**Comment by apoorvsadana** [comment]
Oh ok, I will pick this one for now, sorry for the delay. But please feel free to pick any issue and also you can message me on telegram - @apoorvsadana
