### ISSUE TITLE
Increase test coverage of `crates/client/rpc` crate.

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/madara#160]

**Comment by RajeshRk18** [comment]
Can I work on this one?

**Comment by abdelhamidbakhta** [comment]
@RajeshRk18 are you on the telegram group ?

**Comment by RajeshRk18** [comment]
No! Do I need to be in the group to contribute here?

**Comment by abdelhamidbakhta** [comment]
> No! Do I need to be in the group to contribute here?

No you don't need to. You can start working on it

**Comment by RajeshRk18** [comment]
Given the crate has no logic code, how can I write tests?

**Comment by abdelhamidbakhta** [comment]
> Given the crate has no logic code, how can I write tests?

Sorry it’s actually rpc not rpc-core

**Comment by RajeshRk18** [comment]
Done😁

**Comment by RajeshRk18** [comment]
What client can I use? Is there any TestClientBuilder? Substrate has something like Substrate_test_client but I don't know how it's implemented.

**Comment by EvolveArt** [comment]
Hey @RajeshRk18 [this](https://substrate.stackexchange.com/questions/5193/testing-custom-rpc-with-a-mock-runtime-api) might be helpful

**Comment by RajeshRk18** [comment]
Thanks. I'll check this out

**Comment by abdelhamidbakhta** [comment]
hey @RajeshRk18 any progress ?

**Comment by RajeshRk18** [comment]
Will try giving a PR in 2days

**Comment by RajeshRk18** [comment]
@abdelhamidbakhta  Sorry for making it long. I don't know what the issue is. But I'm getting linking error when compiling mp_crates

**Comment by EvolveArt** [comment]
Hey @RajeshRk18 still working on this ?

**Comment by RajeshRk18** [comment]
You can find the incomplete version in the gist above. Unfortunately, I couldn't compile Madara as it outputs some weird errors I cannot even guess. So, I can't continue with the issue. Maybe assign someone and add more tests??
