### ISSUE TITLE
dev: add pallet test for declareV0

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1603]
In `crates/pallets/starknet/src/tests/declare_tx.rs` add a test that is using `DeclareTransaction::V0` instead of the `V1` we are using everywhere.

**Comment by elielnfinic** [comment]
I can take this.

**Comment by tdelabro** [comment]
@elielnfinic please go ahead

**Comment by tdelabro** [comment]
@raizo07 let me see if I can find some other task for you!

**Comment by tdelabro** [comment]
@raizo07 do you think you can do the same with InvokeTransaction::V0?
under `crates/pallets/starknet/src/tests/invoke_tx.rs`

**Comment by tdelabro** [comment]
@raizo07 you can start working on it without an issue don't worry

**Comment by raizo07** [comment]
> @raizo07 you can start working on it without an issue don't worry

I'm on it now, thanks.

**Comment by tdelabro** [comment]
@raizo07 when you create your PR add me as reviewer. Or tag me in the PR discussion

**Comment by raizo07** [comment]
> @raizo07 when you create your PR add me as reviewer. Or tag me in the PR discussion

@tdelabro Okay I will once I'm done.

**Comment by tdelabro** [comment]
@raizo07 still working on it?

**Comment by raizo07** [comment]
> @raizo07 still working on it?

Yes I am. I sent you a message on Telegram earlier.

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
