### ISSUE TITLE
dev: update the json abi to uniformize class hash used by madara and mock

### ISSUE THREAD

**Issue by j1mbo64** [keep-starknet-strange/madara#1604]
Madara and Mock don't use the same contract ABI (some have line breaks), so the class hashes are not the same between Madara and Mock.

Do you want Mock to use the same genesis.json ? Or Mock to use his own genesis.json but same contract ABI as Madara ? Or just update Mock contract ABI ?

Can you directly assign me to the task ?

**Comment by vibenedict** [comment]
Hi, i will like to take up this issue.

**Comment by j1mbo64** [comment]
Hello, I have already start to work on it

**Comment by od-hunter** [comment]
Hello, I'd love to be assigned this project as this is my first time to contribute in onlydust and I'd love to be given the opportunity

**Comment by od-hunter** [comment]
Hello @j1mbo64 I'm waiting for go ahead to start this project

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
