### ISSUE TITLE
dev: make `HasherT` methods accept iterator rather than `&[Felt]` as argument

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#1613]
True for `compute_hash_on_wrapper` and `compute_hash_on_elements`.
Then check everywhere if it can allow us to remove some `.collect()` that were only there to respect the arg type.

Also pleases add a default impl for `compute_hash_on_wrappers` and make it call `compute_hash_on_elements` and remove the concrete impl of it for `poseidon` and `pedersen`.

**Comment by tdelabro** [comment]
actually finish #1607 before claiming this one

**Comment by fishseabowl** [comment]
@tdelabro could I take this? Thanks

**Comment by tdelabro** [comment]
@fishseabowl can you rebase #1526 and #1610 before?

**Comment by fishseabowl** [comment]
@tdelabro #1526 and #1610 have been rebased. Please help to review them. Thanks

**Comment by tdelabro** [comment]
perfect! Go ahead

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
