### ISSUE TITLE
feat(quality): replace `unwrap` by error handling 🔨

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#165]
# Feature Request

**Describe the Feature Request**

`unwrap`s are dangerous to have within the runtime as a `panic` would simply crash the blockchain. 
Moreover it would impact forkless upgrades in the future.

**Describe Preferred Solution**

Go through the codebase and look for `.unwrap()`, replace them with custom errors that then propage to the pallet as `RuntimeError`s.

**Acceptance Crtieria**

No need to replace **ALL** unwraps within a single PR, even small PRs would be very helpful.

**Comment by 0xEniotna** [comment]
Hi ! Can I try something for this one ?

**Comment by EvolveArt** [comment]
hey @0xEniotna sure please go ahead!

**Comment by 0xEniotna** [comment]
To be sure I understand properly as I'm new to Rust, in the following [snippet](https://github.com/keep-starknet-strange/madara/blob/main/crates/pallets/starknet/src/lib.rs#L284) :
```
#[pallet::call_index(0)]
#[pallet::weight(0)]
pub fn ping(origin: OriginFor<T>) -> DispatchResult {
 // Make sure the caller is from a signed origin and retrieve the signer.
          let _deployer_account = ensure_signed(origin)?;
          Pending::<T>::try_append(Transaction::default()).unwrap();
          log!(info, "Keep Starknet Strange!");
          Self::deposit_event(Event::KeepStarknetStrange);
          Ok(())
 }
```
Would that be an acceptable solution ?
```
pub fn ping(origin: OriginFor<T>) -> DispatchResult {
            // Make sure the caller is from a signed origin and retrieve the signer.
            let _deployer_account = ensure_signed(origin)?;
            Pending::<T>::try_append(Transaction::default())
                .map_err(|_| Error::<T>::TooManyPendingTransactions)?;;
            log!(info, "Keep Starknet Strange!");
            Self::deposit_event(Event::KeepStarknetStrange);
            Ok(())
        }
```

Thanks amigos

**Comment by Eikix** [comment]
Can I take it?

**Comment by chee-chyuan** [comment]
can i take this pretty please??

**Comment by abdelhamidbakhta** [comment]
> can i take this pretty please??

Assigned to you

**Comment by chee-chyuan** [comment]
i did some very small work to handle unwraps. i see a majority of it is being used in chain_spec.rs. iiuc, chain_spec should only run once at startup. would it be worth it to also handle the unwrap here??

cc @EvolveArt

**Comment by LucasLvy** [comment]
I believe we have way more unwraps than that. It's fine not to fix those in the chain specs

**Comment by chee-chyuan** [comment]
> I believe we have way more unwraps than that. It's fine not to fix those in the chain specs

ok i will find more. opened a draft pr and will update that

**Comment by lambda-0x** [comment]
I can take this up. This is roughly number of unwarp each crate has, its not very accurate because this contains unwraps in tests as well.

```
client: 14
node: 33
pallets: 247
primitives: 154
runtime: 1
```

**Comment by abdelhamidbakhta** [comment]
> I can take this up. This is roughly number of unwarp each crate has, its not very accurate because this contains unwraps in tests as well.
> 
> ```
> client: 14
> node: 33
> pallets: 247
> primitives: 154
> runtime: 1
> ```

Let’s go mate. Assigned to you
