### ISSUE TITLE
bug: Denied request: HTTP header: `host` value: <HOST> verification failed

### ISSUE THREAD

**Issue by neelkamath** [keep-starknet-strange/madara#1655]
# Bug Report

**Madara version:** 0.8.0-7b405924b58

**Current behavior:**

Requests don't go through.

**Expected behavior:**

Allows requests to be made.

**Steps to reproduce:**

1. Run either `cargo run --release -- --dev` or `cargo run --release -- --dev --rpc-external`.
2. Make a request from `localhost` or `host.docker.internal`.
3. Get the error: `Denied request: HTTP header: `host` value: `host.docker.internal:9944` verification failed`

**Comment by ShantelPeters** [comment]
@neelkamath can I work on this ? This would be my first time contributing to this ecosystem…

**Comment by ShantelPeters** [comment]
I am applying for this issue via https://app.onlydust.com/p/madara

Hello, I've read the contributors guidelines and I'm excited to help with this task. I understand the bug:

- Madara version 0.8.0-7b405924b58 is not allowing requests to go through.
- Error message: "Denied request: HTTP header: host value:host.docker.internal:9944 verification failed".

To approach this problem, I would:

1. Investigate the Madara configuration files for any incorrect settings.
2. Verify the RPC settings and ensure they are correct.
3. Analyze the error message for any clues.
4. Check the Madara documentation for any known issues or solutions.
5. Test the requests using tools like Postman or cURL to isolate the issue.

My background in software development, debugging, and RPC protocols can be leveraged to efficiently identify and resolve this issue. I'm confident in my ability to debug and fix this problem.

Please assign me this task, and I'll deliver the updated code to resolve the request issue in Madara.

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
