### ISSUE TITLE
Move the global state root computation in an asynchronous task to speed up block production.

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/madara#179]
# Description

The global state root computation is a heavy process. It consumes a lot of time and resources in the block production.
A solution would be to include state root of block `N - 1` in the block header `N`, instead of the state root of the block `N`. But for this to save time it would need to be done in an asynchronous manner.

# Solution

Compute the state root in the client (in // to the block production, asynchronously) and inject it through an inherent.

**Comment by abdelhamidbakhta** [comment]
Some raw notes from telegram:

```
Basically it's a question about the interactions between the runtime, the node and the pallets in Substrate. Because in Pallets you can't do asynchronous work, everything you do in a pallet is sequential (except for offchain worker but it is not guaranteed to run on every block). So we need a way to be able to do some parallel computation for some cases, for instance the computation of the state root (which on mainnet represente something like 30% of the block production time, this is huge), if we can save this it would enable faster block production

So basically we would like something like that for block N production:
- retrieve state of block N - 1 and compute the global state root => here we want it to be done asynchronously in // to the block production of N (now we can't, we do it in a syncronous way in the pallet)
- when all transactions are executed get the result from previous step (the question is how basically) and add gblobal state root of block N -  1 in the block header of block N

The block production is orchestrated by the client part of the node. So yes you can wait for a node task to finish.
To inject the value into the block/state you can use an inherent or put it in the blockheader.
```

**Comment by tdelabro** [comment]
What is the algorithm used to compute the storage root? Is there a lib I can use to do it?

**Comment by EvolveArt** [comment]
> What is the algorithm used to compute the storage root? Is there a lib I can use to do it?

You can look at https://github.com/keep-starknet-strange/madara/pull/166 and #130

**Comment by EvolveArt** [comment]
You won't be able to work on this task until #166 is merged

**Comment by tdelabro** [comment]
I won't be able to compute the root, but I can setup the asynchronous server and client-runtime communication

**Comment by abdelhamidbakhta** [comment]
> I won't be able to compute the root, but I can setup the asynchronous server and client-runtime communication

yes definitely
