### ISSUE TITLE
feat: RPC - starknet_getStateUpdate

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/madara#190]
Get the information about the result of executing the requested block

**Comment by samueloh99** [comment]
Hi !! Can I get this issue ?

**Comment by abdelhamidbakhta** [comment]
> 

sure, thanks

**Comment by sparqet** [comment]
@samueloh99 Are you still on it ?

**Comment by sparqet** [comment]
@abdelhamidbakhta can I take it ?

**Comment by d-roak** [comment]
@sparqet are you working on this?

**Comment by sparqet** [comment]
@d-roak no you can take it mate, I was about to tell @abdelhamidbakhta to unassign me

**Comment by d-roak** [comment]
While looking at how I could implement the StateDiffs I checked how Blockifier is [handling the states](https://github.com/tdelabro/blockifier/blob/4b4f6ff20e5e872fb4cbcdd238bf980281c58b85/crates/blockifier/src/state/cached_state.rs).
And I think we should refactor the DictStateReader, to add a state cache like Blockifier has.
https://github.com/keep-starknet-strange/madara/blob/9d1126ea9321a28944a4656167384df879ca025e/crates/primitives/starknet/src/state/mod.rs#L30-L39

What are your thoughts on that? Any other suggestions on how to handle the StateDiffs?

**Comment by LucasLvy** [comment]
Right now we don't have the state root so get state update should return mocked values

**Comment by d-roak** [comment]
So in get_state_update should I return mocked values? Like:

```
StateUpdate {
    block_hash: block.header().hash(),
    new_root: block.header().state_root(), // mocked? Can I use global_state_root?
    old_root: parent_block.header().state_root(), // mocked? Can I use global_state_root?
    state_diff: StateDiff { ...... } // totally mocked
}
```

**Comment by d-roak** [comment]
I will drop this one. I think @rkdud007 wants to take over

**Comment by rkdud007** [comment]
I'll take it ser 🫡

**Comment by abdelhamidbakhta** [comment]
> I want to take it ser 🫡

Assigned to you!

**Comment by abdelhamidbakhta** [comment]
Any news on this @rkdud007 ?

**Comment by rkdud007** [comment]
@abdelhamidbakhta sorry had a busy week 😅 if this issue is urgent to be done can give it to someone else! or else, i will do at this weekend :))

**Comment by abdelhamidbakhta** [comment]
> @abdelhamidbakhta sorry had a busy week 😅 if this issue is urgent to be done can give it to someone else! or else, i will do at this weekend :))

Hey hey, any news ? Fine if you don't want to continue working on it. Just to check the status and find another contributor if needed

**Comment by MdTeach** [comment]
@abdelhamidbakhta I would like to take this

**Comment by Pilouche** [comment]
Hi @abdelhamidbakhta as discussed on Telegram, I would like to tackle this one.

**Comment by Pilouche** [comment]
Linked PR is now ready for review.
