### ISSUE TITLE
feat: RPC - starknet_getTransactionByHash

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/madara#192]
Get the details and status of a submitted transaction

**Comment by glihm** [comment]
@abdelhamidbakhta I can try to take this one to dive into how madara runtime works. 👍

**Comment by abdelhamidbakhta** [comment]
> @abdelhamidbakhta I can try to take this one to dive into how madara runtime works. 👍

Sure thing, assigned to you.

**Comment by glihm** [comment]
Quick question, as I am going through my PR for this issue, I was wondering what is the most efficient way to retrieve transaction by hash.

At the moment, we store the blocks with all their transactions. Does it mean I have no choice of iterating on all blocks using `getBlockWithTxHashes` to find the transaction the user asked for?

Do you think it is worthy to spend some time on finding an efficient way to keep somehow an index of transactions? Or did I miss it?

Thanks a lot for the feedbacks.

(For now I am doing a very naïve implementation).

**Comment by glihm** [comment]
Also to confirm, for now I can return a `Transaction`, but once the storage is implemented for `TransactionReceipWrapper` this should be the returned object, right?

**Comment by glihm** [comment]
@abdelhamidbakhta merged in #323. :+1:
