### ISSUE TITLE
feat: RPC - starknet_getTransactionReceipt

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/madara#194]
Get the transaction receipt by the transaction hash

**Comment by robinstraub** [comment]
Sounds like a good first issue to work on, can I get assigned on this one ?

**Comment by robinstraub** [comment]
I missed the message somehow sorry, I'm waiting for a required refactoring that should occur in a different PR, I should be able to complete the issue this week

**Comment by abdelhamidbakhta** [comment]
> @abdelhamidbakhta can you re-open this? I am working on it with @robinstraub. 👍

Done

**Comment by glihm** [comment]
@abdelhamidbakhta merged with the help of @LucasLvy in the #323. :+1:
