### ISSUE TITLE
feat: RPC - starknet_estimateFee

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/madara#200]
estimate the fee for of StarkNet transactions

**Comment by ClementWalter** [comment]
hey, can I try this one?

**Comment by abdelhamidbakhta** [comment]
> hey, can I try this one?

Sure, assigned to you.

**Comment by ClementWalter** [comment]
starting rn, I've been caught up by some side projects sorry

**Comment by abdelhamidbakhta** [comment]
> starting rn, I've been caught up by some side projects sorry

no worries. LFG!
