### ISSUE TITLE
Add commitment Hasher in the Starknet pallet

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/madara#233]
# Description

In order to make the starknet pallet more modular we need to add a commitment Hasher type.

# Acceptance criteria

* Commitment Hasher type is added
* Event and Tx commitment use this trait

**Comment by venkatnetha** [comment]
I would like to explore this issue. Please assign this to me.

**Comment by EvolveArt** [comment]
> I would like to explore this issue. Please assign this to me.

Hey @venkatnetha are you still working on this ?

**Comment by ftupas** [comment]
Hi, is it alright if I can take a stab at this one?

**Comment by venkatnetha** [comment]
Sure.

**Comment by ftupas** [comment]
@venkatnetha sorry didn't mean to take it from you as I saw it got unassigned, would you still like to take it?

**Comment by venkatnetha** [comment]
Please feel free to take it.

**Comment by ftupas** [comment]
> Please feel free to take it.

Thanks! Appreciate it 👍

**Comment by lana-shanghai** [comment]
If it's not being worked on, I can take it

**Comment by ftupas** [comment]
> If it's not being worked on, I can take it

Sorry just getting back to it, was afk this weekend 🤝
