### ISSUE TITLE
Add block body (transactions) in `CurrentBlock` pallet storage item and sync the RPC database of the client to store the block bodies.

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/madara#234]
# Description

Currently, we store only the block header in the pallet storage and on the client database. Multiple RPC endpoints need to have access to the transactions of a block. Hence we need to store them in `CurrentBlock` pallet storage item, and also sync them on the client database for RPC access.

**Comment by glihm** [comment]
Does the block body contain the transactions only or also all the transactions receipt?

Is there a place where this body is defined to check how it has to be implemented?

**Comment by abdelhamidbakhta** [comment]
> Does the block body contain the transactions only or also all the transactions receipt?
> 
> Is there a place where this body is defined to check how it has to be implemented?

Right now the block body is defined nowhere.
