### ISSUE TITLE
Implement `Narwhal & Bullshark` consensus as substrate client consensus

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/madara#24]
# Description

We need to do some research work and implement Narwhal & Bullshark consensus as a substrate consensus client and perform some benchmarks.

# Resources

- [Narwhal and Tusk: A DAG-based Mempool and Efficient BFT Consensus](https://arxiv.org/pdf/2105.11827.pdf)
- [Bullshark: DAG BFT Protocols Made Practical](https://arxiv.org/pdf/2201.05677.pdf)
- [Narwal Rust implementation in Sui](https://github.com/MystenLabs/sui/tree/main/narwhal)

**Comment by tdelabro** [comment]
I will work on this!
