### ISSUE TITLE
Investigate moving to `mdbx` instead of `rocksdb`

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/madara#247]
# Description

Investigate and implement a storage backed by an `mdbx` database instead of `rocksdb`.

Another possibility would be to try directly using [Papyrus storage](https://github.com/starkware-libs/papyrus/blob/main/crates/papyrus_storage/src/db/mod.rs).

# Acceptance criteria
- the implemented solution must pass all tests (unit, integration, end to end)
- performance benchmarks must be provided with a comparison with current storage implementation

# Resources

- [Rust bindings for MDBX](https://github.com/vorot93/libmdbx-rs)
- [Papyrus example](https://github.com/starkware-libs/papyrus/blob/main/crates/papyrus_storage/src/db/mod.rs)

**Comment by darmis007** [comment]
Will pick up this one @abdelhamidbakhta  as we discussed

**Comment by abdelhamidbakhta** [comment]
> Will pick up this one @abdelhamidbakhta as we discussed

Assigned to you

**Comment by h3lio5** [comment]
I can work on this.

**Comment by dbejarano820** [comment]
@abdelhamidbakhta Hey could I work on this one? 
Would we want to replace `rocksdb` with `mdbx` completely or just add it as a new source?

**Comment by EvolveArt** [comment]
> @abdelhamidbakhta Hey could I work on this one? Would we want to replace `rocksdb` with `mdbx` completely or just add it as a new source?

Hey @dbejarano820 , assigned and yes I think you'd want to remove completely and assess performance improvements/degradation.

**Comment by dbejarano820** [comment]
I will continue to look into this, it's a pretty advanced spike... If anyone is interested in taking the lead, be my guest. I can collaborate.

**Comment by shamb0** [comment]
Hi @abdelhamidbakhta, could you please assign it to me? I'd like to take it on.

**Comment by abdelhamidbakhta** [comment]
> 

You can do that in addition to the `try-runtime` work ? I would prefer to avoid multiple tasks in parallel. 
Especially in this case where both are important, so I would prefer to avoid a bottleneck with one person working on the two in parallel.

**Comment by shamb0** [comment]
@abdelhamidbakhta, I plan to pick up this task after closing the try-runtime. Testing is in progress, and I expect to close it today or tomorrow. I am confident that I can handle it. 😄

**Comment by abdelhamidbakhta** [comment]
> @abdelhamidbakhta, I plan to pick up this task after closing the try-runtime. Testing is in progress, and I expect to close it today or tomorrow. I am confident that I can handle it. 😄

let's go then!

**Comment by shamb0** [comment]
@abdelhamidbakhta, Do we need to do this investigations on `mc-db` (crates/client/db/Cargo.toml) ?

**Comment by shamb0** [comment]
- I have completed the reference study of the Papyrus storage database. 

	https://github.com/starkware-libs/papyrus/blob/main/crates/papyrus_storage/src/db/mod.rs

- I have a high-level overview of the requirements and design. 

- I am currently preparing the database adoption layer at Madara in `crates/client/db/src/lib.rs`. 

- I will soon attempt to commit the draft pull request.

**Comment by abdelhamidbakhta** [comment]
> * I have completed the reference study of the Papyrus storage database.
>   https://github.com/starkware-libs/papyrus/blob/main/crates/papyrus_storage/src/db/mod.rs
> * I have a high-level overview of the requirements and design.
> * I am currently preparing the database adoption layer at Madara in `crates/client/db/src/lib.rs`.
> * I will soon attempt to commit the draft pull request.

Awesome! looking forward to it!

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
