### ISSUE TITLE
dev: investigate best values for bounded types 🔨

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#250]
We use the `BoundedVec` type in many places which requires some bound values.

For now we mostly use `u32::MAX = 4294967295` but probably it shouldn't be the case for everything. 

e.g [1](https://github.com/EvolveArt/kaioshin/commit/9ce2dab5825f67d8b8596640d9656f204b818c31#diff-e6236d7c38d69c88218836096a3fa2873f71671d87b453a9090c716b1e6fc6aeR14) ,[2](https://github.com/keep-starknet-strange/madara/commit/47d4bcf6b25997f891bb146907276325e625c95b#diff-d1e7254b6a1f394f0f8f9fee94b5cfad347b50e492ef7a6d92e7238220852faeR7)

**Comment by tdelabro** [comment]
we can disable the requirement for values in storage to have a bounded size at any moment. For single storages or for the whole pallet. It's up to us

**Comment by tdelabro** [comment]
I will disable the requirement for bounder types in storage in an incoming PR
