### ISSUE TITLE
dev: add block_hash and block_number fields to receipt 🔨

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#252]
Update this [line](https://github.com/keep-starknet-strange/madara/pull/248/files/9012cc4283beedd23ab8e0b12ffc4e892a60c3a1#diff-119590cb37177503b40c572e1f4e6f21d5600e50605bc7e01d744ae158201f18R149)

**Comment by greged93** [comment]
Hey @EvolveArt, I'm down to try this one

**Comment by tdelabro** [comment]
@zediogoviana will give it a try!
