### ISSUE TITLE
feat(test): test coverage for starknet pallet Errors 🧪

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#295]
# Feature Request

**Describe the Feature Request**

In the starknet pallet there are numerous errors, and most of them are not tested in every case in which they could happen.

```rust
/// The Starknet pallet custom errors.
/// ERRORS
#[pallet::error]
pub enum Error<T> {
      AccountNotDeployed,
      TransactionExecutionFailed,
      ClassHashAlreadyDeclared,
      ContractClassHashUnknown,
      ContractClassAlreadyAssociated,
      ContractClassMustBeSpecified,
      AccountAlreadyDeployed,
      ContractAddressAlreadyAssociated,
      InvalidContractClass,
      ClassHashMustBeSpecified,
      TooManyPendingTransactions,
      TooManyPendingEvents,
      StateReaderError,
      EmitEventError,
      StateDiffError,
      ContractNotFound,
  }
```

**Acceptance Criteria**

- PR should increase the coverage of the codebase
- All `starknet` pallet's errors should be tested inside the pallet's tests

**Comment by Eikix** [comment]
I can try to do this one!

**Comment by Eikix** [comment]
note for future issue -> `TooManyPendingTransactions` & `TooManyPendingEvents` deserve their own issue, as it may require to mock a full storage instance?
Maybe a new fixture env

what do you think @EvolveArt?

**Comment by Eikix** [comment]
Same goes for EmitEventError, should we have a dedicated issue to test event emission flow?

**Comment by Eikix** [comment]
optimistically creating an issue for TooManyPendingTransactions and TooManyPendingEvents
