### ISSUE TITLE
feat(test): add end to end flow tests 🧪

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#296]
# Feature Request

**Describe the Feature Request**

We want to have complete tests that tests for end to end user flows in the pallet's tests.

**Acceptance Criteria**

- PR must increase the test coverage of the repo
- New tests should be added that cover the full user flow from `deploy_account` to `invoke`
You can refer to an example [here](https://github.com/starkware-libs/blockifier/blob/main/crates/blockifier/src/transaction/account_transactions_test.rs#L45)

**Comment by ClementWalter** [comment]
I'll do this

**Comment by abdelhamidbakhta** [comment]
> I'll do this

Is it still relevant @ClementWalter ?

**Comment by ClementWalter** [comment]
@abdelhamidbakhta I don't know tbh
