### ISSUE TITLE
feat: in declare_v1 transaction, compute class_hash from contract_class 

### ISSUE THREAD

**Issue by Eikix** [keep-starknet-strange/madara#302]
# Feature Request

In [starknet pallet, declare v1](https://github.com/keep-starknet-strange/madara/blob/main/crates/pallets/starknet/src/lib.rs#L485), we currently accept the contract class hash as part of the payload.
It'd be sounder to compute it inside the declare v1 scope. 

As per: https://docs.starknet.io/documentation/architecture_and_concepts/Blocks/transactions/#declare_v1, user does need to provide the class hash (otherwise we'd need to check it matches the contract class, thus recomputing it)
<img width="864" alt="image" src="https://user-images.githubusercontent.com/66871571/234532385-ff5c20b0-4334-44e5-adf2-d17d34d182f6.png">

**Describe the Feature Request**

From the ContractClass struct, create a method called compute_class_hash that takes a non mutable ref to self and returns the class_hash as per declare v1 -> https://docs.starknet.io/documentation/architecture_and_concepts/Contracts/class-hash/

<img width="864" alt="image" src="https://user-images.githubusercontent.com/66871571/234533391-09e72375-5b81-403b-af1f-7592dc05f5d6.png">

**Comment by Eikix** [comment]
Additional comment, if test PR is done -> update declare tests to not include contract class hash anymore

**Comment by Eikix** [comment]
Current sequencer -> https://github.com/starkware-libs/blockifier/blob/3df4bc49a0e2f3c442137fedd11acbd560cfef92/crates/blockifier/src/transaction/account_transactions_test.rs#L69

**Comment by Eikix** [comment]
Open RPC spec -> https://github.com/starkware-libs/starknet-specs/blob/47727a8f2332c762b93d4acbd07e06bfe78bcf94/api/starknet_api_openrpc.json#L1426

**Comment by marioiordanov** [comment]
Can I take this issue

**Comment by marioiordanov** [comment]
I want to work on this issue

**Comment by EvolveArt** [comment]
> Those changes have a PR [starkware-libs/starknet-api#42](https://github.com/starkware-libs/starknet-api/pull/42).

Hello @marioiordanov ! Great to see your PR making progress on their repo! Do you think you'd be able to tackle this one next which should be quite straightforward once your PRs merged in `starknet-api`

**Comment by marioiordanov** [comment]
Not sure, when the PR is going to be merged. Also I see that Madara is using a fork of the starknet_api, which I can't tell how often is being synced with the starknet_api repo. Aside from that I think it would be easy

**Comment by EvolveArt** [comment]
> Not sure, when the PR is going to be merged. Also I see that Madara is using a fork of the starknet_api, which I can't tell how often is being synced with the starknet_api repo. Aside from that I think it would be easy to be implemented.

Great, well will check that and try to push for it to be merged

**Comment by abdelhamidbakhta** [comment]
@marioiordanov @EvolveArt can we move forward on this ? even if not merged in starknet_api I mean ?

**Comment by marioiordanov** [comment]
@abdelhamidbakhta you mean to move the implementation from starknet_api to the Madara project, or make the changes to starknet-api fork of [tdelabro](https://github.com/tdelabro/starknet-api)

**Comment by abdelhamidbakhta** [comment]
> @abdelhamidbakhta you mean to move the implementation from starknet_api to the Madara project, or make the changes to starknet-api fork of [tdelabro](https://github.com/tdelabro/starknet-api)

I mean make the changes to starknet-api fork of [tdelabro](https://github.com/tdelabro/starknet-api)

**Comment by abdelhamidbakhta** [comment]
> > > > @abdelhamidbakhta you mean to move the implementation from starknet_api to the Madara project, or make the changes to starknet-api fork of [tdelabro](https://github.com/tdelabro/starknet-api)
> > > 
> > > 
> > > I mean make the changes to starknet-api fork of [tdelabro](https://github.com/tdelabro/starknet-api)
> > 
> > 
> > Ok @marioiordanov can you make your PR to the fork so we can finish this ?
> 
> @EvolveArt yeah sure, please assign it to myself

Assigned it to you
