### ISSUE TITLE
Fix `get_class_at`

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/madara#309]
# Description

`get_class_at` is implemented but wants to return a `Sierra` Program. We do not deal with sierra yet so it returns a default value.

# Acceptance criteria

* `get_class_at` returns an actual contract class.

**Comment by 0xEniotna** [comment]
Let me try something for this one !

**Comment by LucasLvy** [comment]
You need to wait for #307 to be merged

**Comment by chee-chyuan** [comment]
can i try this one?

**Comment by EvolveArt** [comment]
> can i try this one?

Already taken by @0xEniotna sorry!
