### ISSUE TITLE
Use real gas price

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/madara#329]
# Description

For now we use a fixed fake gas price (10). We should make it dynamic based on the L1 gas price.

# Acceptance criteria

* gas price is correct and dynamic

**Comment by dbejarano820** [comment]
If no one is taking this one on, I'd love to give it a shot!

**Comment by chee-chyuan** [comment]
> If no one is taking this one on, I'd love to give it a shot!

sorry im supposed to take this. stuck at something atm

**Comment by abdelhamidbakhta** [comment]
> If no one is taking this one on, I'd love to give it a shot!

Assigned to you

**Comment by edisontim** [comment]
If this is stale, I would love to be able to work on this one!

**Comment by edisontim** [comment]
> Hey @edisontim, I'm currently working on it! I'd love to get your take on my approach once I open a PR

Ok! I'll try to keep an eye out for when this is being reviewed

**Comment by dbejarano820** [comment]
Still WIP

**Comment by chirag-bgh** [comment]
@LucasLvy I would like to take this on.

**Comment by abdelhamidbakhta** [comment]
> @LucasLvy I would like to take this on.

Assigned to you

**Comment by apoorvsadana** [comment]
@tdelabro I guess we should open this as well?

**Comment by EvolveArt** [comment]
> What is the archi there:
> 
> 1. query the current gas price to some oracle
> 2. insert it as the beginning of the block as an inherent block value
> 3. use it in the runtime
> 
> Works for a centralized setup.
> 
> @apoorvsadana @EvolveArt wdyt?


Remind the reason why we can't get this from L1 directly querying some full node ?
Althoug I agree that this solution would be fine for now it's far from ideal.

**Comment by apoorvsadana** [comment]
Can we ask Starkware what function are they using on top of the L1 gas price for fee estimation? There is very old [post](https://community.starknet.io/t/fees-in-starknet-alpha/286) on the community forum which talks about using a markup.

> The fee calculated may include a markup to compensate for L1 gas cost fluctuations.

But its almost 2 years since then, maybe they have a mature solution or they know what constants work.

**Comment by tdelabro** [comment]
superseeded by #1573
