### ISSUE TITLE
Improve fee transfer execution

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/madara#332]
# Description

For the fees we use almost the same code as the blockifier and it's not optimal. We should improve things and remove shortcuts that were taken. Ideally those PRs could also be submitted to the blockifier.

# Acceptance criteria

* The code for the fees is cleaned up and improved

**Comment by greged93** [comment]
hey @LucasLvy, anyone on this?

**Comment by abdelhamidbakhta** [comment]
> hey @LucasLvy, anyone on this?

Please take it.
