### ISSUE TITLE
bug: npm install fails for tests

### ISSUE THREAD

**Issue by bajpai244** [keep-starknet-strange/madara#333]
# Bug Report

**Madara version:**

**Current behavior:**

When we shift to the tests folder, and do a `npm` install, it fails with the following error:
```shell
npm ERR! Invalid comparator: latest
```

**Expected behavior:**

The installation should work.

**Steps to reproduce:**

CD into tests, and do `npm install`

**Comment by LucasLvy** [comment]
What node version do you use ?

**Comment by bajpai244** [comment]
@LucasLvy 

Node -> v18.12.1
NPM -> 9.2.0

**Comment by bajpai244** [comment]
@LucasLvy , I guess we should add .nvmrc then!

**Comment by LucasLvy** [comment]
Yep good idea, do you want to do it ?

**Comment by bajpai244** [comment]
> Yep good idea, do you want to do it ?

Yes ser!

I will raise a PR doing so.
