### ISSUE TITLE
dev: Add failing test situation for RPC syncing endpoint

### ISSUE THREAD

**Issue by zediogoviana** [keep-starknet-strange/madara#338]
PR #257 introduced the `starknet_syncing` RPC endpoint, but it's still missing the test for the falling situation (when a node is not syncing and returns `false` instead of the syncing status info).

After talking with @EvolveArt, I’ve been reading about Zombienet and how it could help with the missing test for the syncing RPC endpoint (the situation where the endpoint returns false). I’ve also searched on [substrate's node options](https://docs.substrate.io/reference/command-line-tools/node-template/) to see if there is anything related to syncing that I can toggle, but nothing seems to be what I want… I also found [this question](https://substrate.stackexchange.com/questions/6472/how-to-perform-manual-sync) that’s pretty much what I want, but the answer says the guy can’t do it, and he should try --in-peers and --out-peers to 0 but that’s already the case we have in the current test setup.

This way, it was suggested to move ahead with the PR and open an issue with these findings.

**Comment by chee-chyuan** [comment]
I would like to take this one if possible?

**Comment by zediogoviana** [comment]
Hey @chee-chyuan! What issues are you having?

**Comment by chee-chyuan** [comment]
> > Hey @chee-chyuan! What issues are you having?
> 
> /
> 
> ```
> Unable to update https://github.com/xJonathanLEI/starknet-rs?branch=dev/jsonrpc_0_3_0#403f02e8
> ```

no longer an issue. will try this tmr

**Comment by chee-chyuan** [comment]
> i suspect that by disabling the `--force-authoring` we will be able to stop the dev node from forcefully creating blocks? i would love to give this a try but i cant get the repo to build atm :( https://substrate.stackexchange.com/questions/752/what-is-the-internal-logic-of-force-authoring-flag/776

turns out that i was wrong. how do we get `best_seen_block` to return an error??

**Comment by chee-chyuan** [comment]
> Hi @chee-chyuan! Good thought! However, I had a look at the [source code](https://docs.rs/sc-network-sync/latest/src/sc_network_sync/service/chain_sync.rs.html#96-101) for that function, and it doesn't seem very helpful for what we need since it's just interacting with channels... What do you think?
> 
> Maybe try to see what `ToServiceCommand::BestSeenBlock(tx)` needs to return an `oneshot::Canceled`, but not really sure if this is already a rabbit hole.

indeed a rabbit role. i was digging abit myself without much success
