### ISSUE TITLE
feat: RPC - starknet_addDeployAccountTransaction

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/madara#342]
Submit a new deploy account transaction

**Comment by makluganteng** [comment]
Hi can i take this task ?

**Comment by abdelhamidbakhta** [comment]
> Hi can i take this task ?

Sure, assigned to you

**Comment by EvolveArt** [comment]
> Hi can i take this task ?

Sorry but @greged93 is already on it :(

**Comment by greged93** [comment]
Hey sorry, took over for Lucas but forgot to comment

**Comment by abdelhamidbakhta** [comment]
> Hey sorry, took over for Lucas but forgot to comment

no worries, I assigned it to you

**Comment by abdelhamidbakhta** [comment]
> Hi can i take this task ?

Sorry, this one was already taken my bad. Can you try to pick another one ? would be great

**Comment by makluganteng** [comment]
No worries , do u have nay good recommendation for starters issue ?

**Comment by abdelhamidbakhta** [comment]
> No worries , do u have nay good recommendation for starters issue ?

@EvolveArt can you please make few suggestions ?
Also @makluganteng are you on the telegram group ?

**Comment by makluganteng** [comment]
Yup i am there
