### ISSUE TITLE
Save last proven block

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/madara#350]
# Description

Once we add proving in madara we'll need to know the last proven starknet block in order to return the right status of a block or transaction.

# Acceptance criteria

* Last starknet proven block is stored somewhere
* All the txs and blocks returns the appropriate status

**Comment by abdelhamidbakhta** [comment]
> # Description
> Once we add proving in madara we'll need to know the last proven starknet block in order to return the right status of a block or transaction.
> 
> # Acceptance criteria
> * Last starknet proven block is stored somewhere
> * All the txs and blocks returns the appropriate status

Querying the settlement layer you mean ?

**Comment by zediogoviana** [comment]
Hi @LucasLvy and @abdelhamidbakhta! What's missing for this issue to be ready? Should it be handled in separate smaller issues? What can be done about it?

**Comment by abdelhamidbakhta** [comment]
> Hi @LucasLvy and @abdelhamidbakhta! What's missing for this issue to be ready? Should it be handled in separate smaller issues? What can be done about it?

Basically since we haven't started the part related to proof generation and state diffs on the settlement layer, we can really start working on this.
