### ISSUE TITLE
fix: fix to_rpc_contract_class 

### ISSUE THREAD

**Issue by 0xEniotna** [keep-starknet-strange/madara#363]
## Description 

**Current behavior:**

The RPC functions `get_class` and `get_class_at` use the function `to_rpc_contract_class`.

In fact, this function is broken. it always returns a default value.

```rust
/// Returns a `ContractClassWrapper` from a `RPCContractClass`
pub fn to_rpc_contract_class(_contract_class_wrapped: ContractClassWrapper) -> Result<RPCContractClass> {
    Ok(RPCContractClass::ContractClass(Default::default()))
}
```
**Expected behavior:**

It should return the correct `RPCContractClass`

**Comment by 0xEniotna** [comment]
Taking it myself

**Comment by abdelhamidbakhta** [comment]
> Taking it myself

assigned to you, did you start working on it ?

**Comment by 0xEniotna** [comment]
I took days off so not really but I have the plan in mind. I might need help a some point tho

**Comment by 0xEniotna** [comment]
I'm considering to do something like this:
```rust
```

**Comment by abdelhamidbakhta** [comment]
Hey, indeed it's not a trivial issue.
`Shouldn't I consider only the SierraContractClass case ?` > I don't think so. I mean we want to keep the possibility of using Cairo 0 on Appchains for the moment, and possibly for a long period.

**Comment by abdelhamidbakhta** [comment]
> Hey, indeed it's not a trivial issue.
> `Shouldn't I consider only the SierraContractClass case ?` > I don't think so. I mean we want to keep the possibility of using Cairo 0 on Appchains for the moment, and possibly for a long period.

Hey, indeed it's not a trivial issue.
Shouldn't I consider only the SierraContractClass case ? > I don't think so. I mean we want to keep the possibility of using Cairo 0 on Appchains for the moment, and possibly for a long period.

**Comment by 0xEniotna** [comment]
I just can't find a way to do it. If someone wants to take the issue please go ahead.

I tried to do something like, idk if it will help:
```rust
pub fn to_rpc_contract_class(_contract_class_wrapped: ContractClassWrapper) -> Result<ContractClass> {
    if _contract_class_wrapped.program.contains_key("sierra_program") {
        let entry_points_by_type = EntryPointsByType { constructor: vec![], external: vec![], l1_handler: vec![] };
        let default = SierraContractClass {
            sierra_program: vec![FieldElement::from_dec_str("0").unwrap()],
            contract_class_version: String::from("version"),
            entry_points_by_type,
            abi: String::from("abc"),
        };
        Ok(ContractClass::Sierra(default))
    } else {
        let deprecated_contract_class: DeprecatedContractClass = DeprecatedContractClass {
            program: todo!(),
            entry_points_by_type: _to_deprecated_entrypoint_by_type(_contract_class_wrapped.entry_points_by_type),
            abi: Option::None, // WE MIGHT WANT TO CHANGE THAT
        };
        Ok(ContractClass::Legacy(deprecated_contract_class))
    }
}```

and `to_deprecated_entry_point` being:

```rust
type WrappedEntryPointsByType =
    BoundedBTreeMap<EntryPointTypeWrapper, BoundedVec<EntryPointWrapper, MaxEntryPoints>, MaxEntryPointsType>;

fn _to_deprecated_entrypoint_by_type(entries: WrappedEntryPointsByType) -> DeprecatedEntryPointsByType {
    let mut constructor = vec![];
    let mut external = vec![];
    let mut l1_handler = vec![];

    for (entry_type, entry_points) in entries.into_inner() {
        match entry_type {
            EntryPointTypeWrapper::Constructor => {
                constructor = entry_points
                    .into_iter()
                    .map(|obj| DeprecatedCairoEntryPoint {
                        offset: obj.offset as u64,
                        selector: FieldElement::from_bytes_be(&obj.selector).unwrap(),
                    })
                    .collect();
            }
            EntryPointTypeWrapper::External => {
                external = entry_points
                    .into_iter()
                    .map(|obj| DeprecatedCairoEntryPoint {
                        offset: obj.offset as u64,
                        selector: FieldElement::from_bytes_be(&obj.selector).unwrap(),
                    })
                    .collect();
            }
            EntryPointTypeWrapper::L1Handler => {
                l1_handler = entry_points
                    .into_iter()
                    .map(|obj| DeprecatedCairoEntryPoint {
                        offset: obj.offset as u64,
                        selector: FieldElement::from_bytes_be(&obj.selector).unwrap(),
                    })
                    .collect();
            }
        }
    }

    DeprecatedEntryPointsByType { constructor, external, l1_handler }
}
```

**Comment by abdelhamidbakhta** [comment]
> I just can't find a way to do it. If someone wants to take the issue please go ahead.
> 
> I tried to do something like, idk if it will help:
> 
> ```rust
> pub fn to_rpc_contract_class(_contract_class_wrapped: ContractClassWrapper) -> Result<ContractClass> {
>     if _contract_class_wrapped.program.contains_key("sierra_program") {
>         let entry_points_by_type = EntryPointsByType { constructor: vec![], external: vec![], l1_handler: vec![] };
>         let default = SierraContractClass {
>             sierra_program: vec![FieldElement::from_dec_str("0").unwrap()],
>             contract_class_version: String::from("version"),
>             entry_points_by_type,
>             abi: String::from("abc"),
>         };
>         Ok(ContractClass::Sierra(default))
>     } else {
>         let deprecated_contract_class: DeprecatedContractClass = DeprecatedContractClass {
>             program: todo!(),
>             entry_points_by_type: _to_deprecated_entrypoint_by_type(_contract_class_wrapped.entry_points_by_type),
>             abi: Option::None, // WE MIGHT WANT TO CHANGE THAT
>         };
>         Ok(ContractClass::Legacy(deprecated_contract_class))
>     }
> }```
> 
> and `to_deprecated_entry_point` being:
> 
> ```rust
> type WrappedEntryPointsByType =
>     BoundedBTreeMap<EntryPointTypeWrapper, BoundedVec<EntryPointWrapper, MaxEntryPoints>, MaxEntryPointsType>;
> 
> fn _to_deprecated_entrypoint_by_type(entries: WrappedEntryPointsByType) -> DeprecatedEntryPointsByType {
>     let mut constructor = vec![];
>     let mut external = vec![];
>     let mut l1_handler = vec![];
> 
>     for (entry_type, entry_points) in entries.into_inner() {
>         match entry_type {
>             EntryPointTypeWrapper::Constructor => {
>                 constructor = entry_points
>                     .into_iter()
>                     .map(|obj| DeprecatedCairoEntryPoint {
>                         offset: obj.offset as u64,
>                         selector: FieldElement::from_bytes_be(&obj.selector).unwrap(),
>                     })
>                     .collect();
>             }
>             EntryPointTypeWrapper::External => {
>                 external = entry_points
>                     .into_iter()
>                     .map(|obj| DeprecatedCairoEntryPoint {
>                         offset: obj.offset as u64,
>                         selector: FieldElement::from_bytes_be(&obj.selector).unwrap(),
>                     })
>                     .collect();
>             }
>             EntryPointTypeWrapper::L1Handler => {
>                 l1_handler = entry_points
>                     .into_iter()
>                     .map(|obj| DeprecatedCairoEntryPoint {
>                         offset: obj.offset as u64,
>                         selector: FieldElement::from_bytes_be(&obj.selector).unwrap(),
>                     })
>                     .collect();
>             }
>         }
>     }
> 
>     DeprecatedEntryPointsByType { constructor, external, l1_handler }
> }
> ```

no worries and thanks @0xEniotna 
@EvolveArt will take it from there
