### ISSUE TITLE
bug: Can't build the repo on Fedora 38

### ISSUE THREAD

**Issue by FilipLaurentiu** [keep-starknet-strange/madara#373]
# Bug Report

**Madara version:** 
https://github.com/keep-starknet-strange/madara/commit/c769da5a1db213996d5b69b85179baf0bbe45b70

**Current behavior:**

Can't build `madara`. It seems to be an issue related to an old substrate dependency of rocksdb.
![Screenshot from 2023-05-09 09-44-12](https://user-images.githubusercontent.com/20188480/237015725-f7f924a1-42d3-4937-8f42-cf0d26a3abb5.png)

**Steps to reproduce:**

`cargo build --release`

**Related code:**

```
insert short code snippets here
```

**Other information:**

Issue posted on rust-rocksdb repo : https://github.com/rust-rocksdb/rust-rocksdb/issues/772
Building and linking separately don't work, maybe because is a dependency from another crate, idk
Full error: [err.txt](https://github.com/keep-starknet-strange/madara/files/11428146/err.txt)

**Comment by darmis007** [comment]
Can I pick this up @abdelhamidbakhta ?

**Comment by abdelhamidbakhta** [comment]
> Can I pick this up @abdelhamidbakhta ?

Sure, assigned to you

**Comment by d-roak** [comment]
@FilipLaurentiu can you confirm that #497 fixes this issue?

**Comment by FilipLaurentiu** [comment]
![image](https://github.com/keep-starknet-strange/madara/assets/20188480/d0002a63-1513-450e-a80d-7716c4e03005)
I can confirm that it work :clap:  thank you guys
