### ISSUE TITLE
Add a cairo project to build required artifacts

### ISSUE THREAD

**Issue by ClementWalter** [keep-starknet-strange/madara#377]
# Feature Request

## Describe the Feature Request

The project uses several compiled cairo files for testing and benchmarking madara.
These files were compiled somewhere, someday, by some people. There is no way to generate them from withing the madara project.

This makes the tests:

- less reproducible as the way to generate their inputs is missing
- less reliable as their input is not humain readable
- farther to real test-cases as their input is not a _true_ input from a _true_ end user.

## Describe Preferred Solution

Add a cairo 0.x project to build those required artifacts from regular cairo files.

## Describe Alternatives

We could have though about having another repo but madara is not an organization so we could also make this a monorepo.
Probably overkill for now.

## Related Code

[./resources](../blob/main/resources)

## Additional Context

We had a similar need in kakarot and started with a similar solution. Then we integrated `forge` in our test pipeline.
Not only have we been able to generate the file, but also to dramatically increase the coverage thanks to the easiness of adding new test cases.

## If the feature request is approved, would you be willing to submit a PR?

Yes

**Comment by venkatnetha** [comment]
I want to take this issue. Please assign this to me.

**Comment by abdelhamidbakhta** [comment]
> I want to take this issue. Please assign this to me.

Done, assigned to you. Thanks for your help. Please let us know if you have any issues.

**Comment by abdelhamidbakhta** [comment]
Sorry @venkatnetha I unassigned it since you are not really responsive right now. Maybe you could join the telegram group it would be easier to coordinate

**Comment by bajpai244** [comment]
@abdelhamidbakhta lemme attend this one :)

**Comment by abdelhamidbakhta** [comment]
> @abdelhamidbakhta lemme attend this one :)

Sure thing my friend. Assigned to you

**Comment by LucasLvy** [comment]
The compiler used is `0.10.3`
