### ISSUE TITLE
dev: Make the bounded vector max size configurable in Pallet::Config

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#395]
# Who can do this?
This is a really good issue for somebody which just started digging substrate. You have read the doc, you did one or two tutorials, maybe even [my tutorials](https://github.com/rusty-crewmates/substrate-tutorials) and you want to do you first contribution to the runtime of madara.

# What is the problem?

Substrate storage cannot store raw `Vec`. They require a max size those vectors. This is done using [`BoundedVec`](https://docs.rs/bounded-collections/latest/bounded_collections/bounded_vec/struct.BoundedVec.html) instead.
This type take a second generic type `S: Get<u32>` which is a type which return a value which is the max size of the bounded vector. Think about it as of a numeric value that has been made a type.

Right now, our bounded vec max size id defined by constants such as:
```rust
pub type MaxTransactions = ConstU32<4294967295>;
```
Defined in `crates/primitives/starknet/src/block/mod.rs`.

In order for different chains to set different max, but also for us to be able to tests behaviours where the max size is reached, it would be preferable for those values to be configurable. 

# What to do?

To do so, they should be passed as associated types to the pallet `Config`:
```rust
  #[pallet::config]
    pub trait Config: frame_system::Config {
        type RuntimeEvent: From<Event<Self>> + IsType<<Self as frame_system::Config>::RuntimeEvent>;
        type StateRoot: Get<U256>;
        type SystemHash: Hasher;
        type TimestampProvider: Time;
        #[pallet::constant]
        type UnsignedPriority: Get<TransactionPriority>;
    }
``` 
In the exact same way `UnsignedPriority` is defined:
```rust
        #[pallet::constant]
        type MaxPendingTransactions: Get<u32>;
```

It would probably be great to add one of such types for each type of storage data we have. This way it is possible to configure each one independently.

The we can use them in order to bound our storage size as follow:
```rust
    #[pallet::storage]
    #[pallet::getter(fn pending)]
    pub(super) type Pending<T: Config> =
        StorageValue<_, BoundedVec<(Transaction, TransactionReceiptWrapper), <T as Config>::MaxPendingTransactions>, ValueQuery>;
```
You would also need to modify any implementation of the pallet `Config` trait:
```rust

parameter_types! {
    pub const UnsignedPriority: u64 = 1 << 20;
    pub const MaxPendingTransactions: u32 = 10  // <------
}

impl pallet_starknet::Config for MockRuntime {
    type RuntimeEvent = RuntimeEvent;
    type StateRoot = pallet_starknet::state_root::IntermediateStateRoot<Self>;
    type SystemHash = mp_starknet::crypto::hash::pedersen::PedersenHasher;
    type TimestampProvider = Timestamp;
    type UnsignedPriority = UnsignedPriority;
    type MaxPendingTransactions = MaxPendingTransactions; // <-------
}
```
This will happen both in `mock.rs` and `/Users/tdelabro/Documents/code/starkware/madara/crates/runtime/src/pallets.rs`.
Doc to the [parameter_types!](https://paritytech.github.io/substrate/master/frame_support/macro.parameter_types.html) macro

**Comment by lana-shanghai** [comment]
Hey @tdelabro , there is an enum `pub enum BlockTransactions` defined in the primitives. It is a `BoundedVec` with the length `MaxTransactions`. Since I'm moving `MaxTransactions` to the pallet's config, now there is a back and forth dependency, the pallet imports `BlockTransactions`, and the primitives import `MaxTransactions` for the `BoundedVec`. Do you mind if I move all things dependent on `MaxTransactions` into the pallet? Probably into `types.rs`

**Comment by tdelabro** [comment]
Go ahead!

**Comment by tdelabro** [comment]
Can't you do this instead?

```rust
pub enum BlockTransactions<S: Get<u32>> {
    /// Only hashes
    Hashes(BoundedVec<H256, S>),
    /// Full transactions
    Full(BoundedVec<Transaction, S>),
}
```

So it stays in primitives and is just generic over the `MaxTransactions` sized decided by the runtime?

**Comment by lana-shanghai** [comment]
> So it stays in primitives and is just generic over the `MaxTransactions` sized decided by the runtime?

In this case the issue that I am seeing is that you have to add `madara-runtime = { path = "../runtime" }` to `Cargo.toml` in primitives, if you would like to reuse the types defined there, and that introduces a cyclic dependency, because primitives are in the runtime's and pallet's `Cargo`. I like the idea of it being generic over the length, but in tests for example it needs to fetch the exact type.

**Comment by tdelabro** [comment]
Deemed a bit too complex for not that much value. So we prefer not to push it forward
