### ISSUE TITLE
dev: parametrize Hasher in client ✨

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#402]
Right now, only the runtime parametrizes the `Hasher` with `SystemHash`.
It is currently hardcoded to `PedersenHasher` in the client, we should look into the best way to make this easily configurable.

Should it be forced to be the same as in runtime ?

**Comment by greged93** [comment]
hey @EvolveArt, can have a look at this if it's free

**Comment by abdelhamidbakhta** [comment]
> hey @EvolveArt, can have a look at this if it's free

Assigned to you
