### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by ittayd** [keep-starknet-strange/madara#426]
# Bug Report

**Madara version:**

62609f6808c882f8fe2301af2f4a14e56e06ebfb

**Current behavior:**

Build (from scratch fails)

**Steps to reproduce:**

clone
cargo run --release -- --dev

**Other information:**
The error is:
```
❯ cargo run --release -- --dev
    Updating git repository `https://github.com/xJonathanLEI/starknet-rs`
error: failed to get `starknet-crypto` as a dependency of package `mp-starknet v0.1.0-alpha (/home/ittay/workspace/madara/crates/primitives/starknet)`

Caused by:
  failed to load source for dependency `starknet-crypto`

Caused by:
  Unable to update https://github.com/xJonathanLEI/starknet-rs?branch=dev/jsonrpc_0_3_0#403f02e8

Caused by:
  object not found - no match for id (403f02e83fb3fd9f87654aae1f34c94ad480e9ef); class=Odb (9); code=NotFound (-3)
```

**Comment by abdelhamidbakhta** [comment]
hey @ittayd thanks for submitting. Don't know if it can help but can you please share information about your machine (OS, etc)

**Comment by betacodd** [comment]
can I try to fix this one @abdelhamidbakhta ? In any case it's mandatory for my other issue #427

**Comment by abdelhamidbakhta** [comment]
> can I try to fix this one @abdelhamidbakhta ? In any case it's mandatory for my other issue #427

yes please
