### ISSUE TITLE
bug: chain_spec generation fails 🔨

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#429]
# Bug Report

**Madara version:**

https://github.com/keep-starknet-strange/madara/commit/3db1adafd06259090a2df80cae6617a904b318c3

**Current behavior:**

Chain spec generation currently fails whereas it used to work previously.

**Expected behavior:**

Chain spec should be generated correctly with the following commands : 
```
cargo build --release

./target/release/madara build-spec > ./infra/chain-specs/chain-spec-plain.json
```

**Related code:**

We get the following logs :
```
cargo run -- build-spec --chain dev
    Finished dev [unoptimized + debuginfo] target(s) in 0.62s
     Running `target/debug/madara build-spec --chain dev`
2023-05-19 14:04:33 Building chain spec
Error: Service(Other("Error generating spec json: key must be a string"))
```

**Other information:**

**Comment by sparqet** [comment]
The json generation failed because there is a false at the beginning of the JSON file that should be created. The false came from the ```config.chain_spec``` in [command.rs](https://github.com/keep-starknet-strange/madara/blob/466beea793f346561461a91c2cffb51864d75b9e/crates/node/src/command.rs#L59) because the json is generated from it

**Comment by abdelhamidbakhta** [comment]
> Hi ! Can I take this one ?

Hey @sparqet any progress on this one ?

**Comment by sparqet** [comment]
Hi ! I found the origin of the bug, and I am fixing it today

**Comment by sparqet** [comment]
@abdelhamidbakhta When running this command, the program generates a human-readable JSON chain spec.  The json::to_string_pretty function stops and returns the following error: "Error: Service(Other("Error generating spec json: key must be a string"))". However, by running this command: "cargo run -- build-spec --chain dev --raw ", it returns the string specification encoded in raw format and it works. The raw format allows you to distribute string specifications that all nodes can use to synchronize the string, even after runtime updates.
Do you think that the json in raw format is sufficient, or should we still be able to display to be human-readable ? 

Here's some links where I took this informations : 

https://docs.substrate.io/build/chain-spec/#raw-chain-specifications

https://github.com/paritytech/substrate/blob/master/client/chain-spec/src/chain_spec.rs#L365

**Comment by abdelhamidbakhta** [comment]
@sparqet thanks for the detailed explanation. Ideally yes it would be cool if we could handle the human readable format as well, and generate the raw from it.

**Comment by sparqet** [comment]
Alright I'll work on it !

**Comment by EvolveArt** [comment]
> @sparqet thanks for the detailed explanation. Ideally yes it would be cool if we could handle the human readable format as well, and generate the raw from it. 

I think the readable format won't be that readable given the size of contract classes so not sure of how important that is. Anyway great to know it's not a blocker to start working on testnet chain specs!

**Comment by d-roak** [comment]
Actually, the problem is not quite there. It's in the contract classes, that are not correctly json serializable.

https://github.com/keep-starknet-strange/madara/blob/3f0555a78f94d0b03347d4df11815c9438c3dc7a/crates/node/src/chain_spec.rs#L278-L285

If you want, I can fix it :)

**Comment by sparqet** [comment]
yes I found that it was because of the contract classes, I'll correct it
