### ISSUE TITLE
dev: improve SCALE encoding for Felt252Wrapper(FieldElement)

### ISSUE THREAD

**Issue by glihm** [keep-starknet-strange/madara#449]
The PR #422 introduced a first implementation of [SCALE encoding](https://docs.substrate.io/reference/scale-codec/) support for `FieldElement` from `starknet-rs`.

But it's implementation is not optimized and can be improve for performance and memory point of view.

In this issue, 3 main taks are expected:

1. Improve the encoding of a `FieldElement` to be more compact when it can be.
2. Add support for expected types on converters like `[u8; 32]` alongside `&[u8; 32]`.

I can take this one if someone can assign it to me. :+1:

**Comment by glihm** [comment]
Hi guys,

here is the state:


## Optimized encoding for `felt252`
I have implemented a buffer compaction logic which is optimized for `felt252` values. Indeed, when a felt is serialized into a buffer (little endian), we can compact a lot the values (except when entropy is too high, i.g. keccak hash).

This compaction usually reduces the number of bytes from 32 to less than 13 bytes and sometimes up to 4 bytes, also for huge values!

You can check the implementation [here](https://github.com/glihm/madara/blob/felt252wrapper-scale/crates/primitives/starknet/src/execution/felt252_wrapper.rs#L270).

However... the `TypeInfo` trait, required for decoding by SCALE, does need a size... And we don't have a fixed size with this approach. The tests in the crate to encode/decode are working perfectly. But the problem is when a library tries to map the `TypeInfo` to the actual buffer.. and has no clue how to deal with it. So integration tests are failing.

I am still looking for code, but it seems compromised.

## Idea of alternative
So, the best thing I could propose was to convert the `felt252` into `U256` and let Substrate optimize the encoding. But unfortunately, `U256` are also passed as a buffer, as the compaction for integers they implement is only until `u128`, [here](https://github.com/paritytech/parity-scale-codec/blob/master/src/compact.rs).

Except if under the hood they use two `u128`. But then converting the `felt252` into `U256` would be the best approach.

---

@tdelabro perhaps have more insights on this, or @LucasLvy or @EvolveArt or @ClementWalter 
 some ideas? But I think for now, the most efficient way is to keep the 32 bytes buffer.

**Comment by tdelabro** [comment]
@LucasLvy is on it. It will go directly to the labddaclass repository

**Comment by glihm** [comment]
Thanks for the update, and sorry for the delay. Best of luck guys, I'll follow the updates. :)
