### ISSUE TITLE
feat: move `nonce` and `max_fee` to `Felt252Wrapper` type

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/madara#456]
# Feature Request

**Describe the Feature Request**

`nonce` and `max_fee` must be represented by a `Felt252Wrapper` instead of a `U256`.

Right now in transaction types we have them as `U256`, example with [DeclareTransaction](../blob/main/crates/primitives/starknet/src/transaction/types.rs#L142) struct:

```rust
pub struct DeclareTransaction {
    /// Transaction version.
    pub version: u8,
    /// Transaction sender address.
    pub sender_address: ContractAddressWrapper,
    /// Class hash to declare.
    pub compiled_class_hash: Felt252Wrapper,
    /// Contract to declare.
    pub contract_class: ContractClassWrapper,
    /// Account contract nonce.
    pub nonce: U256,
    /// Transaction signature.
    pub signature: BoundedVec<Felt252Wrapper, MaxArraySize>,
    /// Max fee.
    pub max_fee: U256,
}
```

must be:

```rust
pub struct DeclareTransaction {
    /// Transaction version.
    pub version: u8,
    /// Transaction sender address.
    pub sender_address: ContractAddressWrapper,
    /// Class hash to declare.
    pub compiled_class_hash: Felt252Wrapper,
    /// Contract to declare.
    pub contract_class: ContractClassWrapper,
    /// Account contract nonce.
    pub nonce: Felt252Wrapper,
    /// Transaction signature.
    pub signature: BoundedVec<Felt252Wrapper, MaxArraySize>,
    /// Max fee.
    pub max_fee: Felt252Wrapper,
}
```

**Describe Preferred Solution**

Use `Felt252Wrapper` for `nonce` and `max_fee` fields in all transaction types.

**Comment by bajpai244** [comment]
Hello @abdelhamidbakhta , you can assign this to me :)

**Comment by abdelhamidbakhta** [comment]
> Hey @abdelhamidbakhta @bajpai244, I'm working on refactoring the Transaction structure we have in our primitives, moving it to something similar to starknet-rs enum. This is needed to implement the RPC endpoints linked to Txs queries. While doint this I am already updating the `nonce` and `max_fee` :/ Should have made an issue this is on me.

OK I assigned it to you then, please refer to it in the PR.
Sorry @bajpai244 for the inconvenience. Will find you another issue

**Comment by greged93** [comment]
@abdelhamidbakhta this can go back to @bajpai244, the refactoring is proving to be complex and probably not worth the work, we will just add a `_tx_type` field to Transaction (see #459).

**Comment by bajpai244** [comment]
@abdelhamidbakhta i guess I can take this back then :)
