### ISSUE TITLE
feat: refactoring Transaction to an enum

### ISSUE THREAD

**Issue by greged93** [keep-starknet-strange/madara#457]
# Feature Request

**Describe the Feature Request**

In order to store discern the type of transaction that is saved within a block, update the Transaction structure in primitives to an enum, following the structure from [starknet-rs](https://github.com/xJonathanLEI/starknet-rs/blob/master/starknet-core/src/types/mod.rs#L144).

**Describe Preferred Solution**
Update the implementation of the Transaction structure from the primitives.

**Related Code**
Old implementation:
```
pub struct Transaction {
    /// The version of the transaction.
    pub version: u8,
    /// Transaction hash.
    pub hash: Felt252Wrapper,
    /// Signature.
    pub signature: BoundedVec<Felt252Wrapper, MaxArraySize>,
    /// Sender Address
    pub sender_address: ContractAddressWrapper,
    /// Nonce
    pub nonce: U256,
    /// Call entrypoint
    pub call_entrypoint: CallEntryPointWrapper,
    /// Contract Class
    pub contract_class: Option<ContractClassWrapper>,
    /// Contract Address Salt
    pub contract_address_salt: Option<U256>,
    /// Max fee.
    pub max_fee: U256,
}
```

Update: 
```
pub enum Transaction {
    #[serde(rename = "INVOKE")]
    Invoke(InvokeTransaction),
    #[serde(rename = "L1_HANDLER")]
    L1Handler(L1HandlerTransaction),
    #[serde(rename = "DECLARE")]
    Declare(DeclareTransaction),
    #[serde(rename = "DEPLOY")]
    Deploy(DeployTransaction),
    #[serde(rename = "DEPLOY_ACCOUNT")]
    DeployAccount(DeployAccountTransaction),
}
```

See [here](https://github.com/xJonathanLEI/starknet-rs/blob/master/starknet-core/src/types/mod.rs#LL144C1-L155C2) for more details on the expected implementation.

**If the feature request is approved, would you be willing to submit a PR?**
Yes

**Comment by LucasLvy** [comment]
Use the types defined here inside the enum https://github.com/keep-starknet-strange/madara/blob/466beea793f346561461a91c2cffb51864d75b9e/crates/primitives/starknet/src/transaction/types.rs#L129-L257

**Comment by greged93** [comment]
Closing this, see comment on linked PR

**Comment by ClementWalter** [comment]
@abdelhamidbakhta I've reopen it as you suggested in your comment in #459 ; we want to refacto the types in the primitive to use a similar structure as the one in the RPC, and consequently update the current `TryFrom` into a simple `From` (and no more internal server error)

**Comment by abdelhamidbakhta** [comment]
> @abdelhamidbakhta I've reopen it as you suggested in your comment in #459 ; we want to refacto the types in the primitive to use a similar structure as the one in the RPC, and consequently update the current `TryFrom` into a simple `From` (and no more internal server error)

Oh nice thanks 🙏

**Comment by ClementWalter** [comment]
maybe @greged93 you want to be assigned and take the time to finish what you've already started ? or give it to @glihm ? I believe that he was interested in tackling this as well

**Comment by greged93** [comment]
I can leave it to @glihm if he wanted to tackle it :)

**Comment by glihm** [comment]
> I can leave it to @glihm if he wanted to tackle it :)

Hello @greged93 its up to you I am ok with all scenarios.

1. You tackle it as you already explore it.
2. I can do it.
3. We can sync.

🫡

**Comment by greged93** [comment]
2. is fine for me, would love to discuss on your solution though if you want 💪

**Comment by glihm** [comment]
Sorry @greged93, I was short in time lately.
If you already have something on-going because you're more active on madara, just go ahead.

Otherwise, I'll ping here when starting again working on this one. You can unassign me in case you need to tackle it or let some other contributors taking it!

Sorry again.

**Comment by MavericksFive** [comment]
I can tackle it if it's not assigned to anyone!

**Comment by lambda-0x** [comment]
Hey @MavericksFive are you still working on this? If not I can take this up.

**Comment by abdelhamidbakhta** [comment]
> Hey @MavericksFive are you still working on this? If not I can take this up.

Please take it, not sign of activity for a very long time. Assigned to you.

**Comment by greged93** [comment]
I think @MavericksFive is still working on it, he messaged Wednesday with questions

**Comment by lambda-0x** [comment]
sigh I had already started to work on this but no problem. 

To avoid this kind of misunderstanding we should strongly suggest opening draft PR for big changes. @MavericksFive can you please open a draft PR for this issue?

**Comment by abdelhamidbakhta** [comment]
> I think @MavericksFive is still working on it, he messaged Wednesday with questions

oops my bad then.
We really need to do what @lambda-0x suggested, opening a draft PR early so that we know there is activity on an issue
