### ISSUE TITLE
dev: cleaning chain_spec and mock files

### ISSUE THREAD

**Issue by greged93** [keep-starknet-strange/madara#467]
We currently have a lot of hardcoded storage keys in the `chain_spec.rs` file (located [here](https://github.com/keep-starknet-strange/madara/blob/main/crates/node/src/chain_spec.rs#L263)). This can be cleaned up in a similar fashion to what we have in the `mock.rs` file (located [here](https://github.com/keep-starknet-strange/madara/blob/main/crates/pallets/starknet/src/tests/mock.rs)). 

Additionally, as pointed out by @ClementWalter, the `get_storage_key` function from `mock.rs` takes the target address but actually doesn't do anything with it but returning it in the return tuple. This needs to be cleaned, `get_storage_key` should ONLY return what is expected by it, hence returning the storage key.

**Comment by lana-shanghai** [comment]
I would like to take this one

**Comment by abdelhamidbakhta** [comment]
> I would like to take this one

🙏

**Comment by lana-shanghai** [comment]
In order to have `get_storage_key` return the storage key, which is the second element in the tuple, I will then change the `storage` type here: 
https://github.com/keep-starknet-strange/madara/blob/main/crates/pallets/starknet/src/lib.rs#L272

**Comment by lana-shanghai** [comment]
After looking into having `get_storage_key` return only the storage key, I noticed that that would require removing this key value storage item: 
https://github.com/keep-starknet-strange/madara/blob/main/crates/pallets/starknet/src/lib.rs#L235

So I suggest to leave the return value of `get_storage_key` as the current tuple
