### ISSUE TITLE
dev: `class` related integration tests 🔨

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#486]
Right now `getClass` and `getClassAt` integration tests do not "really" test anything except that it does return something. 
We want to make sure it returns the correct class.

One should wait for https://github.com/keep-starknet-strange/madara/pull/485 to be merged tho

**Comment by edisontim** [comment]
Would be happy to get on this one!

**Comment by EvolveArt** [comment]
> Would be happy to get on this one! 

Not fully ready yet but soon!

**Comment by DaVinciDz** [comment]
Hey @EvolveArt, 
Where are we on this one, let's get started if it's ready

**Comment by edisontim** [comment]
I think this is ready to be started @EvolveArt ? :)

**Comment by abdelhamidbakhta** [comment]
> I think this is ready to be started @EvolveArt ? :)

Yes it is, please go ahead

**Comment by chirag-bgh** [comment]
I can take this if this is stale.

**Comment by EvolveArt** [comment]
Superseded by https://github.com/keep-starknet-strange/madara/issues/664
