### ISSUE TITLE
bug: Add a timeout for Benchmarking

### ISSUE THREAD

**Issue by d-roak** [keep-starknet-strange/madara#498]
# Bug Report
**Madara version:** c49f2c8

**Current behavior:**
The Benchmark workflow stays in an infinite loop when trying to connect to a failed RPC endpoint
E.g. [Benchmark#195](https://github.com/keep-starknet-strange/madara/actions/runs/5124101836)

**Expected behavior:**
After some time of failing to connect to the RPC, fail gracefully. Like done in the tests workflow

**Steps to reproduce:**
Change this line to a faulty command
https://github.com/keep-starknet-strange/madara/blob/c49f2c8bc7c3668ec3ccfac1db454b7c5cbff62a/.github/workflows/benchmark.yml#L50

**Comment by apoorveth** [comment]
I can try this one!

**Comment by abdelhamidbakhta** [comment]
> I can try this one!

Great!
