### ISSUE TITLE
dev: remove `BlockTransactions::Hashes` 

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#499]
```rust
pub enum BlockTransactions {
    /// Only hashes
    Hashes(BoundedVec<Felt252Wrapper, MaxTransactions>),
    /// Full transactions
    Full(BoundedVec<Transaction, MaxTransactions>),
}
```

This is the structure stored by the pallet to represent the block transactions.
For some historical reason, it's an enum with two variants `Full` and `Hashes` the idea was to be able to store full blocks or light blocks. This is no more in our objectives, so we would like to get rid of the `Hashes` variant. And while we are at it, we can probably replace the whole `enum` with a `type` alias:
```rust
type BlockTransactions = BoundedVec<Transaction, MaxTransactions>;
```

After you modified the type itself you will have to get rid of all the times we `match` this `enum` in the codebase.
Most of the time we return an error when in the `Hashes` arm, so there is no changes in behavior to be expected

**Comment by lana-shanghai** [comment]
Can take it unless someone is really really craving a GFI :)

**Comment by tdelabro** [comment]
Go ahead
