### ISSUE TITLE
Implement ERC721 (NFT) Minting Benchmark

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/madara#502]
### Description
In order to expand the capabilities of Madara and provide more comprehensive benchmarking data for our users, we need to create a benchmark for ERC721 (Non-Fungible Tokens) minting. Currently, our benchmarking suite only covers ERC20 transfers, but it would be beneficial to start benchmarking other features, such as NFT minting.

### Tasks
1. **Write an ERC721 Benchmark in TypeScript**
    - Follow the structure of the existing ERC20 benchmark as a reference.
    - Ensure that the benchmark effectively measures the performance of NFT minting.

2. **Update CI to Include the New Benchmark**
    - Integrate the new benchmark into our Continuous Integration (CI) pipeline.
    - If possible, consolidate existing graphs for Transactions Per Second (TPS) with this new feature.

3. **Refactor Existing Benchmark Code**
    - Consider refactoring the existing benchmark code to make it easier to add and benchmark new features in the future.

### Components Needed
- An ERC721 contract written in Cairo 0. For the time being, we will use Cairo 0 as we have yet to support Cairo 1.0.
- TypeScript files to orchestrate sending transactions to the sequencer.
- GitHub Actions workflows to integrate this new benchmark into our CI.

### Guidelines
- Please follow the coding standards and practices already established in the project.
- Make sure to test your code thoroughly and ensure that it does not introduce any new issues.
- If you encounter any problems or need clarification on anything, don't hesitate to ask for help or clarification.
- When submitting your Pull Request (PR), please provide a detailed description of the changes you have made, why you made them, and any additional context that might be useful for reviewing your contribution.

### Additional Information
If you're new to Madara or open-source contributions in general, check out our [Contributor Starter Pack](https://github.com/keep-starknet-strange/madara/blob/main/docs/contributor-starter-pack.md). It has everything you need to get started with your first contribution!

Thank you for your interest in contributing to Madara. We're excited to see what you'll bring to the project!

**Comment by bajpai244** [comment]
@abdelhamidbakhta I guess you can assign this to me, I can try to get this done this week :)

**Comment by abdelhamidbakhta** [comment]
> @abdelhamidbakhta I guess you can assign this to me, I can try to get this done this week :)

Wonderful mate!

**Comment by bajpai244** [comment]
Updates:

We firstly need a reliable way to benchmark the node, currently, the ERC-20 benchmarks are also failing, because of various nonce race conditions.

The task has been subdivided into two tasks:
- Deploy ERC721 to genesis
- Benchmark

There is an issue to make ERC721 part of genesis #567, pr #568 solves this.

Hence, when #568 is merged, and we have a reliable way to benchmark, this task can be picked back up and we can do benchmarking.

LGTM 🚀

**Comment by abdelhamidbakhta** [comment]
> Updates:
> 
> We firstly need a reliable way to benchmark the node, currently, the ERC-20 benchmarks are also failing, because of various nonce race conditions.
> 
> The task has been subdivided into two tasks:
> 
> * Deploy ERC721 to genesis
> * Benchmark
> 
> There is an issue to make ERC721 part of genesis #567, pr #568 solves this.
> 
> Hence, when #568 is merged, and we have a reliable way to benchmark, this task can be picked back up and we can do benchmarking.
> 
> LGTM 🚀

It’s ready to be picked back up! @bajpai244

**Comment by abdelhamidbakhta** [comment]
Up @bajpai244

**Comment by bajpai244** [comment]
@abdelhamidbakhta yes ser 🫡
