### ISSUE TITLE
dev: unit testing for `get_events` rpc logic

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#517]
There is no unit testing for the logic of the `get_events` rpc.

What needs to be testing:
- filtering the events of a single block
- filtering events of multiple blocks
- calls to the RPC (already in place)

Doing so simply splits the code into multiple smaller testable functions.
We also have to find a way to either mock or perform dependency injection in order to test those functions without the whole client running.

**Comment by apoorveth** [comment]
Can I try this one?

**Comment by tdelabro** [comment]
Sure. It's all yours, contact either me @timothee_delabrouille or Greg @greged93 (who developed the RPC) on telegram if you need help understanding the code or on the direction to take :)
