### ISSUE TITLE
feat: remove hardcoded values in starknet pallet tests

### ISSUE THREAD

**Issue by greged93** [keep-starknet-strange/madara#522]
# Feature Request
Update the tests present in pallet starknet.

**Describe the Feature Request**
A lot of the tests present in the starknet pallet use a hardcoded transaction hash and/or a hardcoded address (for deploy account transaction). The transaction hash and address should be calculated using the appropriate function.

**Describe Preferred Solution**
All tests from pallet starknet use the appropriate function to calculate future deployed account address and/or transaction hash.

**Comment by chirag-bgh** [comment]
I can take this.
