### ISSUE TITLE
dev: check extrinsic success in benchmark 🔨

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#523]
**Current Behavior**
Benchmarks runs and produces results wether extrinsics are successful or not.

**Expected Behavior**
Benchmark workflow should fail if last 10 extrinsics fail.
One can use `polkadotjs` and use this example from the [cookbook](https://polkadot.js.org/docs/api/cookbook/tx#how-do-i-get-the-decoded-enum-for-an-extrinsicfailed-event).

**Comment by EvolveArt** [comment]
> Hi, I'd like to take this

Assigned!

**Comment by abdelhamidbakhta** [comment]
hey @nikania any update on this ?

**Comment by abdelhamidbakhta** [comment]
> @abdelhamidbakhta @EvolveArt Should I change tests in benchmarks, adding the last 10 extrinsic fail checks and exit test (changing `starknet-erc20.yml` artillery test) or it is okay to have failed extrinsics and I should just exclude failed extrinsics from metrics (changing `metrics.js` in benchmarks)?

We want the benchmark to fail if there is one extrinsic failed in the last 10 BLOCKS (not extrinsics). So you need to iterate over the transactions of the last 10 blocks and exist if there is 1 failed transaction.

**Comment by nikania** [comment]
I added a check for the failed extrinsics in the artillery test, but it doesn't seem to have any effect on this test (it still successfully completes even if there is a failed extrinsic), therefore it doesn't affect GitHub action workflow. 

I think I change my approach and add a js script to run after tests and metrics to check for the failed extinsics in the last 10 blocks, and if there are any, return an error. With this, the GitHub benchmark workflow will fail if there are any failed extrinsics. Does it sound good?

**Comment by abdelhamidbakhta** [comment]
> I added a check for the failed extrinsics in the artillery test, but it doesn't seem to have any effect on this test (it still successfully completes even if there is a failed extrinsic), therefore it doesn't affect GitHub action workflow.
> 
> I think I change my approach and add a js script to run after tests and metrics to check for the failed extinsics in the last 10 blocks, and if there are any, return an error. With this, the GitHub benchmark workflow will fail if there are any failed extrinsics. Does it sound good?

Sounds good yes
