### ISSUE TITLE
dev: In the client, read the starkware block form the Header's Digest, not from the cold storage

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#529]
# Current state

Currently, in the client (mostly RPCs), in order to retrieve a past Starknet block, we read the Substrate storage of the corresponding Substrate block.

It is done in `crates/client/storage/src/overrides/schema_v1_override.rs`
```rust
 fn current_block(&self, block_hash: B::Hash) -> Option<StarknetBlock> {
        self.query_storage::<StarknetBlock>(
            block_hash,
            &StorageKey(storage_prefix_build(PALLET_STARKNET, STARKNET_CURRENT_BLOCK)),
        )
        .map(Into::into)
    }
```

# Problem

This is a waste of time because the Starknet block is already present in the Substrate block header.
We should rather get it from there. 

# How to improve?

The [sc_client_api](https://paritytech.github.io/substrate/master/sc_client_api/index.html)::[HeaderBackend](https://paritytech.github.io/substrate/master/sc_client_api/trait.HeaderBackend.html#) traits provide a really handy `header` method:
```rust
fn header(
        &self,
        hash: <Block as Block>::Hash
    ) -> Result<Option<<Block as Block>::Header>, Error>;
```

So instead of using our `client: Arc<C>` to read the storage, let use it to get the header. Then, we just have to get this header Digest (the trait `Header` provide with `digest` method), then, just call the `fn find_starknet_block(digest: &Digest) -> Result<StarknetBlock, FindLogError>` defined in `crates/primitives/digest-log/src/lib.rs`.

It will be part of your mission to provide your fellow contributors with a nice interface to do all this work. Come up with your best implem :)

**Comment by chirag-bgh** [comment]
I can take this.
