### ISSUE TITLE
feat: add UDC to the genesis state of the chain 

### ISSUE THREAD

**Issue by bajpai244** [keep-starknet-strange/madara#530]
# Add UDC to the genesis state

[UDC](https://medium.com/starknet-edu/deploying-to-starknet-with-the-universal-deployer-contract-c6de07092bfb) is via how Starknet contracts are now supposed to be deployed, having it deployed in the genesis state of the chain can be very helpful.

**Describe Preferred Solution**

Deploy it as part of the genesis state of the chain, just like how ERC20 and wallet contracts are already deployed as part of the genesis state.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

Yes

**Comment by bajpai244** [comment]
@abdelhamidbakhta as discussed in the chat, I would be interested in taking it :)

**Comment by tdelabro** [comment]
@bajpai244 go ahead!

**Comment by xJonathanLEI** [comment]
Please add it to this address: `0x041a78e741e5af2fec34b695679bc6891742439f7afb8484ecd7766661ad02bf`. It's the expected address I believe.

**Comment by bajpai244** [comment]
@xJonathanLEI thanks for the heads up!

**Comment by bajpai244** [comment]
Update: #599 was closed by mistake when I synced my fork, I will open another PR that fixes this in ~45 mins!
