### ISSUE TITLE
dev: Remove the CurrentBlock storage from the starknet pallet

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#531]
Blocked by #529
Blocked by @LucasLvy adding storage for the BlockContext

# Problem

Currently, Starknet blocks are stored twice, once in the Substrate block header digest, and once in the storage.
There is no good reason to do so. 
We have to put them in the header, so we can remove them from the storage.

# What to do?

Remove the definition of then `CurrentBlock` storage in `crates/pallets/starknet/src/lib.rs`.
Remove everything that interacts with it.
Remove every reference to it in the doc.

**Comment by chirag-bgh** [comment]
I can take this after this gets unblocked

**Comment by DaVinciDz** [comment]
Hii @tdelabro, 
Give me a shot on this one 👍

**Comment by LucasLvy** [comment]
Only one issue at the time plz @DaVinciDz

**Comment by DaVinciDz** [comment]
> Only one issue at the time plz @DaVinciDz

Roger that @LucasLvy :)
