### ISSUE TITLE
Transaction longevity

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/madara#539]
# Description

When an extrinsic is received we have to verify it's validity and set some values such as the priority or the longevity. The longevity is the number of blocks the transaction is valid in the mempool. For example a tx with 2 as longevity will stay 2 blocks in the mempool and then be discarded. We want this to be configurable.

In the pallet config add the transaction longevity value like that:
```rs
    #[pallet::config]
    pub trait Config: frame_system::Config {
        ...
        type TransactionLongevity: Get<TransactionLongevity>;
    }
```
And set the value in the runtime.

# Acceptance criteria

- The longevity value is configured in the pallet config

**Comment by ftupas** [comment]
Hello there, may I take this one?
