### ISSUE TITLE
feat: optimize starknet storage access

### ISSUE THREAD

**Issue by greged93** [keep-starknet-strange/madara#540]
# Feature Request
Update the `get_storage_at` RPC endpoint to remove the need of the runtime API query.

**Describe the Feature Request**
The current implementation of `get_storage_at` endpoint makes use of the runtime API in order to access the starknet storage. We should offload work from the runtime to the `override`.

**Describe Preferred Solution**
Implement storage access in the `override` and replace the storage query in `get_storage_at`.

**Related Code**
- [Current storage query](https://github.com/keep-starknet-strange/madara/blob/main/crates/client/rpc/src/lib.rs#L332)
- `override` [location](https://github.com/keep-starknet-strange/madara/blob/main/crates/client/storage/src/overrides/mod.rs#L56)

**Comment by chirag-bgh** [comment]
I will take this.
