### ISSUE TITLE
feat: optimize chain id retrieval

### ISSUE THREAD

**Issue by greged93** [keep-starknet-strange/madara#541]
# Feature Request
Update the `chain_id_str` function from `Starknet` in the RPC to remove the need of the runtime API query.

**Describe the Feature Request**
The current implementation of `chain_id_str` makes use of the runtime API in order to access the starknet pallet and retrieve the chain id. We should offload work from the runtime to the override.

**Describe Preferred Solution**
Implement `chain_id` in the override and replace the runtime API query in `chain_id_str` in rpc file.

**Related Code**

- [Current chain id query](https://github.com/keep-starknet-strange/madara/blob/main/crates/client/rpc/src/lib.rs#L143)
- `override` [location](https://github.com/keep-starknet-strange/madara/blob/main/crates/client/storage/src/overrides/mod.rs#L56)

**Comment by makluganteng** [comment]
can i try to take this ??

**Comment by greged93** [comment]
Sure !
