### ISSUE TITLE
dev: remove block hash from tx receipt

### ISSUE THREAD

**Issue by greged93** [keep-starknet-strange/madara#543]
The block hash is currently stored inside the `TransactionReceipt` structure, which is not needed. Additionally, the block hash stored in the receipt is incorrect (transaction block hash cannot be known before execution of all transaction and call of the `store_block` function).

Remove the `block_hash` field from the `TransactionReceiptWrapper` structure.

**Comment by cwkang1998** [comment]
Would like to take this as well if no one is on it now

**Comment by greged93** [comment]
hey @cwkang1998 I'm handling this myself, PR almost up
