### ISSUE TITLE
Max steps

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/madara#545]
# Description

Each transaction has a maximum number of steps it can consume. For now they are hardcoded but we need to configure them in the starknet pallet like this.
```rs
#[pallet::config]
    pub trait Config: frame_system::Config {
        ...
        type InvokeTxMaxNSteps: Get<u32>;
        type ValidateMaxNSteps: Get<u32>;
    }
```

Those values need to be fed in the block context which is created by the function `get_block_context`

# Acceptance criteria

- Those values are configurable in the runtime

**Comment by LucasLvy** [comment]
Any news on that ?

**Comment by dbejarano820** [comment]
I'd love to look into this one if it's still on the sidelines @LucasLvy @DaVinciDz

**Comment by makluganteng** [comment]
Is this assigned yet ? if not im interested

**Comment by abdelhamidbakhta** [comment]
> Is this assigned yet ? if not im interested

Please do. Assigned to you

**Comment by makluganteng** [comment]
i saw someone already created a pull request on this PR so ill unassigned myself and look for other issue.
