### ISSUE TITLE
bug: Madara RPC doesn't handle "pending" block id

### ISSUE THREAD

**Issue by ClementWalter** [keep-starknet-strange/madara#551]
# Bug Report

**Current behavior:**

When sending a request with `block_id: "pending"`, the RPC returns "block not found".

**Expected behavior:**

Working

**Steps to reproduce:**

```
curl 0.0.0.0:9933 -H 'content-type: application/json'  --data-raw '{"method":"starknet_getNonce","jsonrpc":"2.0","params":{"contract_address": "0x2", "block_id": "pending"},"id":0}' --compressed
```

**Related code:**

[substrate_block_hash_from_starknet_block](../blob/974d7806ddb7765533c8980bc2ee0570548f2f51/crates/client/rpc/src/lib.rs#L126)

**Other information:**

We would probably just return the same as the "latest" because this "pending" state is not expected to last long enough on madara.

**Comment by ptisserand** [comment]
Can I take this one?
To be sure that I have understood, when ending it should also returned the hash?
