### ISSUE TITLE
dev: replace util functions by `From` impl 🔨

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#552]
Investigate if the [following](https://github.com/keep-starknet-strange/madara/blob/main/crates/client/rpc-core/src/utils.rs#L56) functions could be replaced by a `From` implementation.

**Acceptance Criterion**

The following functions are removed
- `to_tx`
- `to_declare_tx`
- `to_deploy_account_tx`
- `to_invoke_tx`

**Comment by pierrot498** [comment]
Can I take this?

**Comment by LucasLvy** [comment]
once #564 is merged

**Comment by dbejarano820** [comment]
Let me at it!

**Comment by dbejarano820** [comment]
@abdelhamidbakhta

**Comment by lambda-0x** [comment]
@greged93 implementing this already resolves #625, #626, #627, #628, and #629 so maybe we can close them?

cc: @abdelhamidbakhta

**Comment by abdelhamidbakhta** [comment]
> @greged93 implementing this already resolves #625, #626, #627, #628, and #629 so maybe we can close them?
> 
> cc: @abdelhamidbakhta

good point, @greged93 what do you think ?

**Comment by dbejarano820** [comment]
I agree, we still need to add testing. The PR is passing all checks now, just waiting on Lucas to give it a look again

**Comment by lambda-0x** [comment]
Okay I will work on adding test after 597 is merged.
