### ISSUE TITLE
bug: block timestamp should be in seconds not milliseconds

### ISSUE THREAD

**Issue by xJonathanLEI** [keep-starknet-strange/madara#564]
# Bug Report

**Madara version:**

[v0.1.0-testnet-sharingan-alpha.4](https://github.com/keep-starknet-strange/madara/releases/tag/v0.1.0-testnet-sharingan-alpha.4)

**Current behavior:**

Block timestamps are be in UNIX milliseconds.

**Expected behavior:**

Block timestamps should be in UNIX seconds.

**Steps to reproduce:**

```console
$ starkli block-time --rpc "https://sharingan.starknet.rs/" --unix
1686124104000
```

**Related code:**

N/A

**Other information:**

N/A

**Comment by abdelhamidbakhta** [comment]
Oh btw this issue is already assigned to @pierrot498 . But please you can take another one

**Comment by lambda-0x** [comment]
@pierrot498 are you still working on this? if not i can take this up.

**Comment by lambda-0x** [comment]
@pierrot498 are you still working on this? if not I can take this up.
