### ISSUE TITLE
dev: remove verbose logging in benchmark workflow

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/madara#569]
Disable logging in the benchmark CI workflow.
It increases a lot the disk space on the runner and it makes hard to find relevant information when the CI fails. You need to scroll a lot to find information.

**Comment by bajpai244** [comment]
@abdelhamidbakhta ser I can take this 🥷

**Comment by abdelhamidbakhta** [comment]
> @abdelhamidbakhta ser I can take this 🥷

wonderful my friend

**Comment by bajpai244** [comment]
Hello @abdelhamidbakhta , can you give me a few examples of the types of logs you think should be disabled in the current-workflow?

**Comment by abdelhamidbakhta** [comment]
> Hello @abdelhamidbakhta , can you give me a few examples of the types of logs you think should be disabled in the current-workflow?

Basically all logs from the JavaScript part, for examples logs that say ERC20 transfer sent for each single transaction sent, this alone represents 100k lines of logs. Also I think we should set the log level of the Madara instance to error

**Comment by bajpai244** [comment]
@abdelhamidbakhta someone from the chat wanted to tackle this, I have another issue which I am working on, so I guess they can take it!

ps: will tell them to comment here

**Comment by lambda-0x** [comment]
yup its me :)
