### ISSUE TITLE
feat: Madara faucet

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/madara#579]
# Feature Request
 
 @zizou0x initiated the work in this [PR](https://github.com/keep-starknet-strange/madara/pull/576) to have a faucet for Madara based Appchains. 
 
 The 2 components (frontend and backend) of the faucet are defined [here](https://github.com/keep-starknet-strange/madara/blob/main/infra/starknet-stack/docker-compose.yml#L25-L43) in a docker compose file.
 
 However it is not working. 
 
 The goal of this issue it to make the faucet work with Madara so that we can start using it on testnets and for different use cases.
 
 # Acceptance criteria
 
 - Have a working faucet integrated to a Madara chain (can be a local single node chain to start with)
 - Write useful documentation about how to use the faucet and how to deploy it

**Comment by zizou0x** [comment]
I noticed 2 issues: 

1. The transaction is sent from the container and Madara's RPC only allows request from localhost.
2. Even when trying to send the transaction from localhost it fails with : 
```
Failed to parse JSON-RPC params as object: Invalid params in the call: unknown variant `0x100000000000000000000000000000001`, expected `0x0` or `0x1` at line 1 column 603
```

Please reach me out on Telegram (@zizou_0x) if you need anything.
