### ISSUE TITLE
feat: Make port for hurl files configurable through hurl variables

### ISSUE THREAD

**Issue by phklive** [keep-starknet-strange/madara#591]
# Feature Request

**Describe the Feature Request**

The port for hurl files now is 9944 we want to make it configurable through hurl variables.

**Describe Preferred Solution**

Hurl variables do not exist natively but you can create them following this technique:

Hurl is a command-line tool and scripting language for HTTP. It's similar to cURL but includes the ability to execute sequences of HTTP requests and to examine the results. Hurl files are essentially text files that include HTTP requests in the Hurl syntax.

As of my last update in September 2021, Hurl does not natively support variables or dynamic values in the same way as some other HTTP scripting languages. However, there are some workarounds for this:

1. **Use a pre-processing tool**: You could use a script or another program to pre-process your Hurl files and replace placeholders with the desired values. This could be as simple as a bash script using `sed` or `awk`, or a more complex Python or JavaScript program.

2. **Environment variables**: Another common pattern in command-line tools is to use environment variables to pass in dynamic values. If you're using Hurl in a Unix-style shell (like bash or zsh), you could use environment variables in your Hurl files, and then use shell substitution to replace them with actual values when you run the Hurl command.

Here's an example of what that might look like:

```bash
export URL='https://myapi.com'
hurl "$(envsubst < my-request.hurl)"
```

In this case, `my-request.hurl` would include a placeholder like `${URL}` where the URL should be. The `envsubst` command replaces `${URL}` with the value of the `URL` environment variable.

Remember that Hurl is not a full-featured programming or scripting language and does not have built-in support for variables or dynamic content. For more complex scenarios, you might want to use a different tool or language that includes these features. If you're working with APIs, tools like Postman or languages like Python or JavaScript (with libraries like Requests or Axios) can provide much more flexibility.

As Hurl might have been updated to include this functionality after my last update in 2021, please check the latest documentation to ensure this information is up-to-date.

**Comment by phklive** [comment]
For sure that's a great take.

I think you can assign @MdTeach, @abdelhamidbakhta

**Comment by abdelhamidbakhta** [comment]
> According to the [current documentation](https://hurl.dev/docs/templates.html#injecting-variables) of Hurl, it appears that variable injection can be accomplished natively:
> 
> ```shell
> hurl --variable URL =http://0.0.0.0:9944 starknet_call.hurl
> ```
> 
> or,
> 
> ```
> export URL=http://0.0.0.0:9944
> hurl --variable  starknet_call.hurl 
> ```
> 
> or,
> 
> ```
> hurl --variables-file hurl-config.env starknet_call.hurl 
> ```
> 
> So, we can have a config file for the default `URL` value which can be configurable. @phklive can I take this with the config file approach?

Assigned to you
