### ISSUE TITLE
dev: Declare all dependencies on workspace level when used in more than one crate

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/madara#605]
# Description

Go over the dependencies of each create of the project, and try to declare dependencies at the workspace level when they are used in more than one crate. It will be easier to upgrade versions, or being able to switch dependencies.

**Comment by makluganteng** [comment]
Can i try this ?

**Comment by abdelhamidbakhta** [comment]
> Can i try this ?

Sure, assigned to you
