### ISSUE TITLE
feat: Remove storage proof computation in block proposer

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/madara#606]
TBD @abdelhamidbakhta

**Comment by exp-table** [comment]
I think it's already disabled by default!

When calling `new_block_at`, given `PR::ENABLED`, it will call `api.record_proof()` and then later in block_builder.build(), if it was recorded, it will be extracted.

Given the [impl](https://github.com/keep-starknet-strange/madara/blob/main/crates/client/block-proposer/src/lib.rs#L74) for `ProposerFactory::new`, we use the `DisableProofRecording` impl. of `PR` which has `ENABLED` set to false. With that, I don't see how the storage proof is every recorded!

**Comment by abdelhamidbakhta** [comment]
> I think it's already disabled by default!
> 
> When calling `new_block_at`, given `PR::ENABLED`, it will call `api.record_proof()` and then later in `block_builder.build()`, if it was recorded, it will be extracted.
> 
> Given the [impl](https://github.com/keep-starknet-strange/madara/blob/main/crates/client/block-proposer/src/lib.rs#L74) for `ProposerFactory::new`, we use the `DisableProofRecording` impl. of `PR` which has `ENABLED` set to false. With that, I don't see how the storage proof is every recorded!

Thank you, closing the issue then
