### ISSUE TITLE
dev: Use taplo to format TOML files of the project

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/madara#607]
# Description

Use [taplo](https://github.com/tamasfe/taplo) to format TOML files of the project.
It's painful for code reviews when we don't all use same formatting rules.
- Add instructions on how to run taplo locally
- Add a formatting rules file for universal formatting
- Add a workflow in the CI to check the formal of TOML files and fail if not valid

**Comment by lambda-0x** [comment]
I can take a stab at this

**Comment by ApereLieZ** [comment]
There are a few questions
Is the task open?
And can tell you more about how it should be implemented: As a script that the developer can run, or as part of the build process?

**Comment by abdelhamidbakhta** [comment]
> There are a few questions Is the task open? And can tell you more about how it should be implemented: As a script that the developer can run, or as part of the build process?

Hey, yes task is open.
As part of the CI workflow, and eventually adds cargo husky hook to do it + add commands in the readme to run manually

**Comment by ApereLieZ** [comment]
Can I take this?

**Comment by abdelhamidbakhta** [comment]
> Can I take this?

please go, assigned to you
