### ISSUE TITLE
dev: improve extrinsic testing

### ISSUE THREAD

**Issue by bajpai244** [keep-starknet-strange/madara#617]
The current extrinsic testing in [test-starknet-extrinsics](https://github.com/keep-starknet-strange/madara/blob/main/tests/tests/test-starknet/test-starknet-extrinsics.ts) needs some improvement.

If we look closely at these tests, they are just testing for events being emitted marking success, a better way to test should be to test state transitions that occur as part of calls to these extrinsic.

For example:
- In case of deployment: check that the class hash is the one for which the contract has been deployed at that address
- Token transfer should check for changes in the balance
- Mint should check for NFT with the given token id being available and owned by the specific 
- UDC deployment should check the contract was deployed successfully

~~+ Make class hash declaration test work!~~ 

Right now the test is skipped, but it should also be working

**Comment by bajpai244** [comment]
@abdelhamidbakhta I would love to take this!

**Comment by abdelhamidbakhta** [comment]
> @abdelhamidbakhta I would love to take this!

Assigned to you my friend

**Comment by bajpai244** [comment]
NOTE: 

Updating the issue here, as mentioned in PR #631, we should skip bringing fixing the `declare` test into the scope of this issue.

It should be its own issue, as from my previous knowledge it requires a decent scope of work.
