### ISSUE TITLE
dev: KISS and YAGNI for `rpc-core/utils`

### ISSUE THREAD

**Issue by greged93** [keep-starknet-strange/madara#625]
Apply the [KISS and YAGNI principles](https://www.boldare.com/blog/kiss-yagni-dry-principles/) to the file located in `client/rpc-core/src/utils.rs`. Multiple sections of the file include duplicated code which can be extracted into separated util functions. Below is an example of such an occurrence: 
```
signature: BoundedVec::try_from(
     invoke_tx_v1.signature.iter().map(|x| (*x).into()).collect::<Vec<Felt252Wrapper>>(),
)
.map_err(|e| anyhow!("failed to convert signature: {:?}", e))?,
```
and 
```
tx
.signature
.iter()
.map(|f| (*f).into())
.collect::<Vec<Felt252Wrapper>>()
.try_into()
.map_err(|_| anyhow!("failed to bound signatures Vec<H256> by MaxArraySize"))?;
```

Additionally, after applying these principles to the file, unit tests are required for each of the extracted util functions.

**Comment by lambda-0x** [comment]
i can take this up

**Comment by greged93** [comment]
Assigned !

**Comment by lambda-0x** [comment]
@greged93 while I am working on this, I can take care of #626, #627 and #628 as well because they are in same file. If someone else takes it up there might be merge commits that we would need to resolve.

**Comment by dbejarano820** [comment]
Heads up, this PR moves this logic

https://github.com/keep-starknet-strange/madara/pull/597
