### ISSUE TITLE
dev: improve testing of `to_invoke_tx`

### ISSUE THREAD

**Issue by greged93** [keep-starknet-strange/madara#626]
Improve the testing of the `rpc-core/src/utils.rs` file by adding unit tests for `to_invoke_tx`. The tests are expected to cover edge cases in order to be accepted.

**Comment by MdTeach** [comment]
@greged93  I would love to take this!

**Comment by abdelhamidbakhta** [comment]
> @greged93 I would love to take this!

Assigned to you

**Comment by greged93** [comment]
@MdTeach need to wait on #597 to be merged

**Comment by greged93** [comment]
Hey @MdTeach, #597 was merged and moved the logic to the file `primitives/starknet/src/transation/types.rs` and the implementation changed to `impl TryFrom<BroadcastedInvokeTransaction> for InvokeTransaction`. Would be great if you are still able to provide tests for this.

**Comment by MdTeach** [comment]
sure @greged93
