### ISSUE TITLE
dev: improve testing of `to_deploy_account_tx` 

### ISSUE THREAD

**Issue by greged93** [keep-starknet-strange/madara#627]
Improve the testing of the `rpc-core/src/utils.rs` file by adding unit tests for `to_deploy_account_tx`. The tests are expected to cover edge cases in order to be accepted.

**Comment by lambda-0x** [comment]
i can take this up.

FYI after #552 the related logic is no longer inside `to_deploy_account_tx` and instead is moved into [`TryInto` block ](https://github.com/keep-starknet-strange/madara/blob/8cd2c06c026a4173afe8ef45539e4f5ed1eda7bb/crates/primitives/starknet/src/transaction/types.rs#L554-L590)

**Comment by greged93** [comment]
Sounds good, please provide tests for `TryFrom<BroadcastedDeployAccountTransaction> for DeployAccountTransaction`.
