### ISSUE TITLE
dev: improve testing of `to_declare_tx`

### ISSUE THREAD

**Issue by greged93** [keep-starknet-strange/madara#628]
Improve the testing of the `rpc-core/src/utils.rs` file by adding unit tests for `to_declare_tx`. The tests are expected to cover edge cases in order to be accepted.

**Comment by makluganteng** [comment]
can i take this

**Comment by abdelhamidbakhta** [comment]
> can i take this

Yes assigned to you

**Comment by makluganteng** [comment]
got it

**Comment by greged93** [comment]
Hey @makluganteng, #597 was merged and moved the logic to the file `primitives/starknet/src/transation/types.rs` and the implementation changed to `impl TryFrom<BroadcastedDeclareTransaction> for DeclareTransaction`. Would be great if you are still able to provide tests for this.

**Comment by makluganteng** [comment]
Okey ill start making the test cases for this.

**Comment by lambda-0x** [comment]
@makluganteng if you are busy with something else I can take this up

**Comment by makluganteng** [comment]
Im currently still doing it just a little stuck on this

**Comment by makluganteng** [comment]
@lambda-0x i think u can take this task i have been quite stuck on a get_contract_class error somehow when i run on test.

**Comment by lambda-0x** [comment]
@greged93 you can assign this to me
