### ISSUE TITLE
dev: KISS and YAGNI for `rpc/lib`

### ISSUE THREAD

**Issue by greged93** [keep-starknet-strange/madara#629]
Apply the [KISS and YAGNI principles](https://www.boldare.com/blog/kiss-yagni-dry-principles/) to the file located in `client/rpc/src/lib.rs`. Multiple sections of the file include duplicated code which can be extracted into separated functions. Below is an example of such an occurrence: 
```
self.pool.submit_one(&SPBlockId::hash(self.client.info().best_hash), TX_SOURCE, extrinsic).await.map_err(
|e|  {
          error!("Failed to submit extrinsic: {:?}", e);
          StarknetRpcApiError::ContractError
     },
)?;
```
The above code is present at three different locations and could be replaced by one implementation of a method for the `Starknet` structure.

Additionally, after applying these principles to the file, unit tests are required.

**Comment by venkatnetha** [comment]
Please assign this to me

**Comment by abdelhamidbakhta** [comment]
> Please assign this to me

Assigned to you

**Comment by dbejarano820** [comment]
If this goes stale, I'm interested in taking it on

**Comment by abdelhamidbakhta** [comment]
> If this goes stale, I'm interested in taking it on

Please take it, assigned to you
