### ISSUE TITLE
bug: implement `declare` test for extrinsic

### ISSUE THREAD

**Issue by bajpai244** [keep-starknet-strange/madara#632]
# Bug Report

**Madara version:**

de627585d860f971e3aa3eb952d7d5126007e327

**Current behavior:**

The current [declare test](https://github.com/keep-starknet-strange/madara/blob/de627585d860f971e3aa3eb952d7d5126007e327/tests/tests/test-starknet/test-starknet-extrinsics.ts#L47) test for extrinsic is skipped. It should not be skipped and there is some bug that makes it not work, which needs to be identified and fixed.

**Expected behavior:**

- The `declare` test should work and not be skipped
- The test must make sure that the class has been declared { other tests in the file can be looked into for inspiration }

**Comment by cwkang1998** [comment]
Can I try this?

**Comment by abdelhamidbakhta** [comment]
> Can I try this? Will be able to work on it this week

Sure, assigned to you

**Comment by abdelhamidbakhta** [comment]
Any progress on this @cwkang1998 ?

**Comment by cwkang1998** [comment]
> Any progress on this @cwkang1998 ?
Going to be working on this tonight, will try to get a PR in for this soon

**Comment by abdelhamidbakhta** [comment]
> > Any progress on this @cwkang1998 ?
> 
> Going to be working on this tonight, will try to get a PR in for this soon

Cool, thank you

**Comment by lambda-0x** [comment]
@cwkang1998 are you still working on this? If not I can take this up

cc: @abdelhamidbakhta

**Comment by cwkang1998** [comment]
@lambda-0x Hey, I am working on this, sorry for taking so long. If its urgent you can take it

**Comment by lambda-0x** [comment]
no problem. if you are already working on it. Just saw it was stale so asked.

I think it would be a good idea to open a draft PR so when needed you can ask in madara telegram chat for help and link the relevant code.

**Comment by cwkang1998** [comment]
Found out that the issue was mainly due to the fact that when generating the SDK via polkadotjs from the Rust code, it does not properly handle enum values for the declare transactions.

**Comment by tdelabro** [comment]
Won't be relevant when we switch to rust test
