### ISSUE TITLE
dev: fix inconsistency of using constants

### ISSUE THREAD

**Issue by bajpai244** [keep-starknet-strange/madara#633]
In the current codebase there are places where sometimes a constant is used, but other times the value is just provided as a string.

This brings inconsistency, as changing the source constant might not result in a change of value everywhere.

One example being:
`TOKEN_CLASS_HASH` exists, still, the value is hardcoded [here](https://github.com/keep-starknet-strange/madara/blob/de627585d860f971e3aa3eb952d7d5126007e327/tests/util/starknet.ts#L148).

All places where string values have been used should be investigated in the tests and their utils and must be replaced with constants wherever possible.

**Comment by bajpai244** [comment]
@abdelhamidbakhta , I would like to take this one :)

**Comment by lambda-0x** [comment]
@bajpai244 are you still working on this? If not i can take this up.

**Comment by lambda-0x** [comment]
@bajpai244 are you still working on this? If not i can take this up.

cc: @abdelhamidbakhta

**Comment by bajpai244** [comment]
Hello @lambda-0x , I was little busy, but I will get this done :)
