### ISSUE TITLE
dev: fix header hash tests 🧪

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#636]
# Bug Report

**Madara version:**

[4a9bc0a008428c594388a375fc3be367940ef165](https://github.com/keep-starknet-strange/madara/commit/4a9bc0a008428c594388a375fc3be367940ef165)

**Current behavior:**

Right now the test don't really test anything apart that we haven't changed the implementation.

**Expected behavior:**

We should test against a block-hash computed with the starknet cli/starkli.

**Comment by lambda-0x** [comment]
I can take this up

**Comment by abdelhamidbakhta** [comment]
> I can take this up.
> 
> EDIT: Is there a tool to calculate `transaction_commitment` and `event_commiment` for a given block? its explained [here](https://docs.starknet.io/documentation/architecture_and_concepts/Blocks/header/) but i don't understand that.
> 
> EDIT2: Method to calculate this values is wrong in the docs, Waiting on pathfinder team to know whats the right way.

Did we figure out the right approach or still not yet ?

**Comment by lambda-0x** [comment]
from @drspacemn 

> Ahhhh I see. Okay yeah I'm fairly sure the docs are incorrect and pathfinder has it correct, but yes I'll double check w/ Ariel

https://t.me/MadaraStarknet/6091

will start working on this today.

**Comment by drspacemn** [comment]
Yes the docs are incorrect here. The return should be `h(tx_hash, h(0,0))` for non invoke txs.
