### ISSUE TITLE
 dev: KISS and YAGNI for `pallet/starknet`

### ISSUE THREAD

**Issue by greged93** [keep-starknet-strange/madara#641]
Apply the [KISS and YAGNI principles](https://www.boldare.com/blog/kiss-yagni-dry-principles/) to the file located in `pallets/starknet/src/lib.rs`. Multiple sections of the file include duplicated code which can be extracted into separated functions. Below is an example of such an occurrence: 
```
let tx_hash = TransactionHash(transaction.hash.into());
let events = match (execute_call_info, fee_transfer_call_info) {
    (Some(mut exec), Some(mut fee)) => {
        let mut events =
            Self::emit_events(&mut exec, tx_hash).map_err(|_| Error::<T>::EmitEventError)?;
        events.append(
            &mut Self::emit_events(&mut fee, tx_hash).map_err(|_| Error::<T>::EmitEventError)?,
        );
        events
    }
    (_, Some(mut fee)) => {
        Self::emit_events(&mut fee, tx_hash).map_err(|_| Error::<T>::EmitEventError)?
    }
    _ => Vec::default(),
};
```
The above code is present at three different locations and could be replaced by one helper function for example.
Additionally, after applying these principles to the file, unit tests are required for any helper function you were able to extract.

**Comment by ptisserand** [comment]
Can I work on this issue?

**Comment by greged93** [comment]
Hey @ptisserand, looks like exp table took it but didn't comment :/ would you be willing to take on the testing part ?
