### ISSUE TITLE
dev: KISS/YAGNI for Hasher traits 🔨

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#643]
Right now we have two traits `CryptoHasherT` and `HasherT` both used at different places and which do not reuse correctly `starknet-rs`, cf this [function](https://github.com/xJonathanLEI/starknet-rs/blob/009bac782bd6d908ca5b1ede9938b38dcbd2fb31/starknet-core/src/crypto.rs#L25).

We should unify those implementations and keep it simple.

**Comment by ApereLieZ** [comment]
I'm ready to address this issue

**Comment by exp-table** [comment]
soon 😏
