### ISSUE TITLE
feat: support for estimateFee version

### ISSUE THREAD

**Issue by apoorvsadana** [keep-starknet-strange/madara#646]
# Feature Request

Add support for `0x100000000000000000000000000000001` version in estimateFee rpc.

Currently, the testnet and mainnet support 0x100000000000000000000000000000001 version for the estimateFee rpc call. [Starknetjs](https://github.com/starkware-libs/cairo-lang/blob/00ee90123c0bbaffe13dd05a79d2d57b0cb747be/src/starkware/starknet/definitions/constants.py#LL64C9-L64C9) also uses this version by default when calling estimateFee within the account.execute method.

**Describe Preferred Solution**

Madara currently relies on the `starknet-core` crate for this. I have created an issue over there which can be tracked [here](https://github.com/xJonathanLEI/starknet-rs/issues/402). Once this is fixed, we can directly integrate their solution with Madara.

**Describe Alternatives**

An alternate method could be to create a custom wrapper on top of `BroadcastedTransaction` to handle a custom fee version. However, that will only be a temporary solution and ideally we should have the issue fixed in the core library

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

Yes

**Comment by xJonathanLEI** [comment]
See: https://github.com/xJonathanLEI/starknet-rs/issues/402#issuecomment-1625849247.

Please test with the branch and let me know if it works. Then I can merge and release a new (breaking) version for `starknet-core`.
