### ISSUE TITLE
dev: improve testing of `Starknet pallet`

### ISSUE THREAD

**Issue by greged93** [keep-starknet-strange/madara#648]
Implement testing for the utils function present in the `Starknet pallet` emit_events_for_calls. This function should be unit tested and tests should cover corner cases.

**Comment by ptisserand** [comment]
Can I work on this one ?

**Comment by ptisserand** [comment]
@greged93 do you know if there is an helper/util function to build `CallInfo` ?

**Comment by greged93** [comment]
I don't think we do yet, easiest might be to execute an entrypoint

**Comment by greged93** [comment]
Hey @ptisserand, are you still working on this?

**Comment by ptisserand** [comment]
Hi @greged93 , sorry I was busy with work and forgot this issue during LambdaZK&StarkNetCC week.

I will try to finish this task this week.

**Comment by tdelabro** [comment]
solved by #985
