### ISSUE TITLE
bug: Make the given_hardcoded_contract_run_invoke_tx_then_multiple_events_is_emitted test in invoke_tx.rs pass

### ISSUE THREAD

**Issue by ClementWalter** [keep-starknet-strange/madara#669]
# Bug Report

**Madara version:**

current

**Current behavior:**

The test is ignored because it doesn't pass.

**Expected behavior:**

Test passes

**Steps to reproduce:**

Run the test

**Related code:**

https://github.com/ClementWalter/madara/blob/44e75cfbb739786cf44be09e8e3aaa91169c5eb2/crates/pallets/starknet/src/tests/invoke_tx.rs#L206

**Other information:**

Problem is probably on the blockifier

**Comment by jobez** [comment]
i can take this!
