### ISSUE TITLE
feat: make the default compiler version easily configurable in the ProgramWrapper conversion 

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/madara#670]
# Feature Request

**Describe the Feature Request**

**Describe Preferred Solution**

**Describe Alternatives**

**Related Code**

**Additional Context**

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

**Comment by dbejarano820** [comment]
I can tackle this
