### ISSUE TITLE
Alternate sequencer address input

### ISSUE THREAD

**Issue by justinFrevert** [keep-starknet-strange/madara#680]
Following https://github.com/keep-starknet-strange/madara/issues/588, we should update the service code in the client so that the sequencer address input can be set via keystore. This would allow the operator to use the current RPC key insertion flow, or insert beforehand through their terminal. 

The motivation for this change is it's slightly more secure, more flexible options for the operator, and is similar to the process for session key insertion for validators(more familiar experience).

For implementation, the current code which gets the address from the storage in the client could look at the keystore to retrieve the key. In the future, we may even sequencer selection to look at whether someone has the key(if it's not already)

E.g. inserting `//Alice` key
`./target/release/madara key insert --scheme sr25519 --key-type sequ --suri 0xe5be9a5092b81bca64be81d212e7f2f9eba183bb7a90954f7b76361f6edb5c0a`

Or through an RPC call to `author_insertKey`

**Comment by MdTeach** [comment]
I would love to take this!

**Comment by justinFrevert** [comment]
> I would love to take this!

Maybe needs to wait on #588, but not sure

**Comment by abdelhamidbakhta** [comment]
@tdelabro @lana-shanghai do you think we should do it ? 
If yes then I will assign it to either @justinFrevert if he wants or @MdTeach

**Comment by tdelabro** [comment]
@abdelhamidbakhta is this compatible with the starknet account abstraction?
What we want to use is the address of a starknet account, which is different from the public key of a signer.

@justinFrevert, did you have this constraint in mind when writing this issue?

**Comment by abdelhamidbakhta** [comment]
> @abdelhamidbakhta is this compatible with the starknet account abstraction? What we want to use is the address of a starknet account, which is different from the public key of a signer.
> 
> @justinFrevert, did you have this constraint in mind when writing this issue?

You are right, what we need to use is the address of a starknet account.

**Comment by justinFrevert** [comment]
Oh that's right I wasn't thinking clearly about the accounts. We could probably close this.

Instead, if we're interested in similar functionality, a similar idea would be to extend the cli with an option like '--sequencer_address'.
