### ISSUE TITLE
dev: Integration Tests w/ different pallets' configuration 🔨

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#685]
Right now, integration tests are run against one runtime configuration defined in `crates/runtime/src/pallets.rs`.
However, with the integration of the state root computation under a flag `EnableStateRoot` we'd want to run integration tests both with this flag on and off.

In order to do this, we would need to define multiple runtimes or a runtime that can be configured through node configuration.

One direction to explore is also the use of [feature-flags](https://substrate.stackexchange.com/questions/1361/attempting-to-build-multiple-runtimes-stopped-by-accountnonceapi-account-nonce), like `madara-state-root` for instance.

**Comment by MdTeach** [comment]
@EvolveArt I would love to take this

**Comment by apoorvsadana** [comment]
Can I pick this one?

**Comment by lambda-0x** [comment]
i can take this up
