### ISSUE TITLE
Run the `__validate__` entrypoint before accepting a tx in the mempool

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/madara#69]
# Description

We don't want to discover that a tx doesn't pass the validation step when we're construction the block it's an unnecessary waste of time and resources so we need to verify that a tx is valid when adding it to the mempool.

# Acceptance criteria

* Invalid (`__validate__` fails) transactions are not added in the mempool

**Comment by ZePedroResende** [comment]
Hi ! I want to try and tackle this

**Comment by abdelhamidbakhta** [comment]
@ZePedroResende what's the status ?

**Comment by marioiordanov** [comment]
@abdelhamidbakhta I want to work on this

**Comment by LucasLvy** [comment]
Worth waiting for #312

**Comment by abdelhamidbakhta** [comment]
@LucasLvy since #312 has been merged can we actively work on this ?
@marioiordanov are you still willing to tackle this issue ?

**Comment by marioiordanov** [comment]
@abdelhamidbakhta yes, I am almost done with it

**Comment by abdelhamidbakhta** [comment]
> @abdelhamidbakhta yes, I am almost done with it

glad to here this mate, thank you!

**Comment by marioiordanov** [comment]
> glad to here this mate, thank you!
@abdelhamidbakhta 
https://github.com/keep-starknet-strange/madara/pull/394

**Comment by LucasLvy** [comment]
The pr has been reverted so reopening the issue
