### ISSUE TITLE
feat: SN OS Output Facts + Proving

### ISSUE THREAD

**Issue by drspacemn** [keep-starknet-strange/madara#693]
Upon finalization of a Madara block:
- run the StarkNet OS via the CairoRunner w/ the starknet layout
- capture the SN OS program outputs and store them on the client
- extract the Position Independent Execution(PIE) from the runner

**Describe Preferred Solution**

DA Options:
- StarkNet Canonical -> submit the PIE to the SHARP -> query the job status -> write the DA facts to ETH L1 once block is proved
- Sovereign Rollup -> write the DA facts to a DAS of our choosing (Celestia) 

**Related Code**

[StarkNet OS Run](https://github.com/starkware-libs/cairo-lang/blob/361fe32d5930db340ea78fe05aedfe706f6c9405/src/starkware/starknet/core/os/syscall_handler.py#L887)

[StarkNet OS Fact Storage](https://github.com/starkware-libs/cairo-lang/blob/361fe32d5930db340ea78fe05aedfe706f6c9405/src/starkware/starknet/storage/starknet_storage.py#L69)

**Comment by drspacemn** [comment]
To include [issue#35](https://github.com/keep-starknet-strange/madara/issues/350) in scope

**Comment by EvolveArt** [comment]
Research
---

First we can get a `Cairo PIE` (Position Independent Execution) by running `cairo-run` with `--cairo_pie_output`.
Q: Is that available in Cairo 1 ?
Q: If yes, how is it different than Cairo 0 ?

https://github.com/starkware-libs/cairo-lang/blob/361fe32d5930db340ea78fe05aedfe706f6c9405/src/starkware/cairo/sharp/client_lib.py#L6

-> Wrapper around `SHARP` API

https://github.com/starkware-libs/cairo-lang/blob/361fe32d5930db340ea78fe05aedfe706f6c9405/src/starkware/cairo/sharp/sharp_client.py#L11

-> SHARP Client
1. init_client: Initializes a SharpClient instance.
2. submit: Command for submitting a Cairo job to SHARP.
3. get_job_status: Command for retrieving the status of a SHARP Cairo job.
4. is_verified: Command for verifying if a fact is registered on the SHARP fact-registry.

https://github.com/starkware-libs/cairo-lang/blob/361fe32d5930db340ea78fe05aedfe706f6c9405/src/starkware/cairo/lang/vm/cairo_pie.py#L2

-> Cairo PIE!

```python
metadata: CairoPieMetadata
memory: MemoryDict
additional_data: Dict[str, Any]
execution_resources: ExecutionResources
version: Dict[str, str] = field(
    default_factory=lambda: {"cairo_pie": CURRENT_CAIRO_PIE_VERSION}
)
```

`metadata` : Where can we get this from ? Does `cairo-rs` returns it ?
`memory` : Same Q
`execution_ressources` : We have that ☑️
