### ISSUE TITLE
bug: `protocol_version` should be a String instead of `Option<u8>`

### ISSUE THREAD

**Issue by lambda-0x** [keep-starknet-strange/madara#700]
# Bug Report

https://github.com/keep-starknet-strange/madara/commit/8816af429c44a5fec5d0ec0142382f0282cceaf3

**Current behavior:**

Currently we encode [`protocol_version`](https://github.com/keep-starknet-strange/madara/blob/8816af429c44a5fec5d0ec0142382f0282cceaf3/crates/primitives/starknet/src/block/header.rs#L44) as `Option<u8>`

**Expected behavior:**

[It should be `String`](https://github.com/eqlabs/pathfinder/blob/33dbc6160eb10e117e61611818c115d8a246205e/crates/common/src/header.rs#L14). If its kept to `Option<u8>` for `non-std` reason, we can use `Felt` or there should be a mapping to convert `protocol_version` to a `String` so it can be returned in rpc call in proper format.

I can work on this if its relevant

**Comment by lambda-0x** [comment]
can take this up

**Comment by EvolveArt** [comment]
Let's first make a PR to set it in the `store_block` method and defining in it in the runtime config.
Discussed with @abdelhamidbakhta and it should probably stay a `u8` not an `Option<u8>` tho. 

What do you see as incompatibility vectors if we do this @lambda-0x ?

**Comment by lambda-0x** [comment]
yeah after digging more into this looks like the `protocol_version` there means the major version of starknet.

so `0.10.0`, `0.11.2` are both considered as `protocol_version` `0`. so it being `u8` make sense.

I got confused because official RPC needs to return the full version of starknet using i.e. `0.11.2` so i not sure where thats stored.

**Comment by lambda-0x** [comment]
will close this and open a new PR with updated information
