### ISSUE TITLE
dev: Starknetjs version migration from 4.22.0 to 5+

### ISSUE THREAD

**Issue by apoorvsadana** [keep-starknet-strange/madara#702]
Our starknet tests currently use version 4.22.0. This version was made for Cairo 0 and new Cairo 1 changes are coming on 5+ versions. We should start migrating to 5+ as well to avoid a lot of changes later on.

**Comment by apoorvsadana** [comment]
@abdelhamidbakhta, I am working on #682 so I can pick this up as I will need 5+ version to test declare V2

**Comment by abdelhamidbakhta** [comment]
> @abdelhamidbakhta, I am working on #682 so I can pick this up as I will need 5+ version to test declare V2

Sure, the more contributions the sooner the M2 ;)

**Comment by apoorvsadana** [comment]
Haha, on it 🚀
