### ISSUE TITLE
test: Block proposer logic

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/madara#703]
# Description

Implement unit tests for the block proposer logic: https://github.com/keep-starknet-strange/madara/blob/main/crates/client/block-proposer/src/lib.rs

A good start would be to pick up tests from: https://github.com/paritytech/substrate/blob/master/client/basic-authorship/src/basic_authorship.rs#L578

**Comment by MdTeach** [comment]
@abdelhamidbakhta  I would love to take this!

**Comment by abdelhamidbakhta** [comment]
> @abdelhamidbakhta I would love to take this!

Let's go, assigned to you
