### ISSUE TITLE
test: Transaction pool logic

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/madara#704]
# Description

Implement unit tests for the transaction pool logic: https://github.com/keep-starknet-strange/madara/tree/main/crates/client/transaction-pool

A good start would be to pick up tests from: https://github.com/paritytech/substrate/blob/master/client/transaction-pool/tests/pool.rs

**Comment by abdelhamidbakhta** [comment]
> @abdelhamidbakhta, I had a question, what other tests apart from the one that has been specified in parity's test would be required here?
> 
> Are there some unique things to our implementation of the pool that would require additional tests?
> 
> Also, I guess I can spend time on this one :)

For now the implementation is the same. But we will of course try to see if we can customize it to be more efficient for our needs, and hence we will probably need more tests.
First step will be to be iso tests with what is in substrate transaction pool crate. then see if we can improve the coverage. 
Assigned to you

**Comment by bajpai244** [comment]
got it ser 🙌

**Comment by abdelhamidbakhta** [comment]
> got it ser 🙌

hey mate, are you still on it ?

**Comment by bajpai244** [comment]
Hello @abdelhamidbakhta , not as of now, I guess you can unassign me as of now :)

**Comment by Juul-Mc-Goa** [comment]
Hey, I can work on this issue if it's still relevant.
This would be my first issue so I might occasionally need some guidance.

**Comment by abdelhamidbakhta** [comment]
> Hey, I can work on this issue if it's still relevant.
> This would be my first issue so I might occasionally need some guidance.

Please do.
@tdelabro @lana-shanghai

**Comment by tdelabro** [comment]
I think that was it
