### ISSUE TITLE
dev: update to handle `ContractClassV1`

### ISSUE THREAD

**Issue by greged93** [keep-starknet-strange/madara#707]
The current codebase doesn't handle a `ContractClassV1` for now and just returns a `ContractClassV0` everywhere. We need to update this in order to handle a `ContractClassV1` where needed.

Please search in the codebase for FIXMEs linked to issue 707.

**Comment by apoorvsadana** [comment]
I am working on #682 which will handle this as well, so you can assign it to me :)
