### ISSUE TITLE
dev: handle `CompiledClassHash`

### ISSUE THREAD

**Issue by greged93** [keep-starknet-strange/madara#708]
The update of blockifier to the latest commit caused an update on the traits `StateReader` and `State`. The traits now include `get_compiled_class_hash` and `set_compiled_class_hash`. These functions need to be implemented. 

This also requires an update to the storage of the Starknet pallet in order to store the `compiled_class_hash`.

**Comment by EvolveArt** [comment]
I'll take this right after the state root

**Comment by EvolveArt** [comment]
Seems to be quite linked to #744 tho
