### ISSUE TITLE
dev: handle `initial_gas`

### ISSUE THREAD

**Issue by greged93** [keep-starknet-strange/madara#710]
The `initial_gas` for a transaction is for now hardcoded (either to a max value or to 0). This needs to be updated once the `initial_gas` can be set in a transaction and retrieved from a transaction.

**Comment by sparqet** [comment]
Can I get this one ?

**Comment by greged93** [comment]
Assigned !

**Comment by sparqet** [comment]
so we close this issue for not being feasible ?
