### ISSUE TITLE
dev: handle `paid_fee_on_l1` for `L1HandlerTransaction`

### ISSUE THREAD

**Issue by greged93** [keep-starknet-strange/madara#712]
The field `paid_fee_on_l1` is currently hardcoded to 0 in the file `primitives/starknet/transaction.rs`. This needs to be updated in order to provide the correct l1 fee.

**Comment by sk1122** [comment]
how will we get the correct gas fee paid on l1?

querying L1 rpc with transaction hash from [this line](https://github.com/keep-starknet-strange/madara/blob/main/crates/primitives/starknet/src/transaction/mod.rs#L569)?

**Comment by greged93** [comment]
@sk1122 I haven't looked much into this and raised the issue for tracking, you would have to research how it can be done, starting for example by looking into [blockifier](https://github.com/keep-starknet-strange/blockifier/tree/no_std-support)

**Comment by sk1122** [comment]
Found this [function](https://github.com/keep-starknet-strange/blockifier/blob/main/crates/blockifier/src/transaction/transaction_execution.rs#L39), it takes `paid_fee_on_l1` as a parameter, but can't find where `from_api` is called from.

Also found this [file](https://github.com/keep-starknet-strange/blockifier/blob/main/crates/blockifier/src/fee/fee_utils.rs), which calculates the l1 gas fees, but don't think its applicable here

also, is SHARP implemented for Madara? if not, then should that be first implemented before this?

**Comment by greged93** [comment]
@sk1122 as far as I understand, the `paid_fee_on_l1` is not related to SHARP but to L1->L2 messaging. You can find more info about this fee [here](https://docs.starknet.io/documentation/architecture_and_concepts/L1-L2_Communication/messaging-mechanism/#l1-l2_message_fees).

**Comment by sk1122** [comment]
understood, i misunderstood it for batch tx from L2->L1, will look into it!

**Comment by tdelabro** [comment]
Yes we should!

**Comment by ayushtom** [comment]
Can i pick this?

**Comment by abdelhamidbakhta** [comment]
> Can i pick this? @tdelabro

Yes assigned to you. Thanks

**Comment by ayushtom** [comment]
https://t.me/MadaraStarknet/10512

I think this needs some planning so you can unassign this if this can take some time. I'll try to pick another issue and work on that

**Comment by tdelabro** [comment]
will be resolved by #1132
