### ISSUE TITLE
dev: include the ABI in declared classes

### ISSUE THREAD

**Issue by greged93** [keep-starknet-strange/madara#723]
Right now the structure used for storage of the contract classes is `ContractClassWrapper`. This structure does not contain an ABI field and as such the ABI of the contract cannot be stored. Update the structure to allow the ABI to be stored and returned with the endpoint `getClass`.

**Comment by sparqet** [comment]
Hi @greged93 can I take this issue ?

**Comment by greged93** [comment]
Hey @sparqet, I was going to add this myself quickly forgot to assigned myself

**Comment by sparqet** [comment]
no problem !
