### ISSUE TITLE
dev: Retrieve chain-spec from URL

### ISSUE THREAD

**Issue by d-roak** [keep-starknet-strange/madara#727]
Currently, we are retrieving and copying the chain-spec from the local filesystem. A better approach would be retrieving it from an URL such as https://chain-spec.madara.wtf/

We should allow different chain-specs for multiple testnets and main net

**Comment by drspacemn** [comment]
You can now access chainspecs via:
https://sharingan.madara.wtf/chain-specs/*

example - https://sharingan.madara.wtf/chain-specs/testnet-sharingan.json

**Comment by d-roak** [comment]
Small note on that. I don't know the future naming conventions. But if "sharingan" is the name only for the testnet, maybe the URL should be something like:
https://chains.madara.wtf/sharingan/spec.json
https://chains.madara.wtf/sharingan/spec-raw.json
https://chains.madara.wtf/rinnegan/spec.json
https://chains.madara.wtf/rinnegan/spec-raw.json

Or this:
https://chains.madara.wtf/testnet-sharingan/spec.json
https://chains.madara.wtf/testnet-sharingan/spec-raw.json
https://chains.madara.wtf/mainnet-rinnegan/spec.json
https://chains.madara.wtf/mainnet-rinnegan/spec-raw.json

What do you think?

**Comment by drspacemn** [comment]
Makes sense to me.

I prefer the former i.e. `https://chains.madara.wtf/sharingan`

**Comment by drspacemn** [comment]
The above has been implemented you can pull chain specs as follows:

https://chains.madara.wtf/sharingan/testnet-sharingan.json

**Comment by d-roak** [comment]
Awesome, let's close this one
