### ISSUE TITLE
bug: sequencers forking

### ISSUE THREAD

**Issue by d-roak** [keep-starknet-strange/madara#737]
There is currently a problem where the sequencers might fork from each other.
This issue needs more investigation because it's unclear how to reproduce it.

Some things that might cause it:
- https://github.com/paritytech/substrate/issues/14347
- https://github.com/paritytech/substrate/issues/13947
- using the `--force-authoring` flag
- nodes storing different chains that were not finalized yet, and using that chain to sync instead of using the longest chain. e.g: 
   - node1 has finality 500, highest 1000 and some block 600 stored in the db
   - node2 joins and syncs with the 600 instead of the 1000

Edit (26/06/2023): downgrading substrate from `2e7fde8` to `polkadot-v0.9.43` fixes the issue

**Comment by EvolveArt** [comment]
Downgrading substrate from `2e7fde8` to `polkadot-v0.9.43` fixes the issue
