### ISSUE TITLE
bug: StarknetRuntimeApi_get_hasher is not found

### ISSUE THREAD

**Issue by LucasLvy** [keep-starknet-strange/madara#742]
When running `cargo r  -r -- --chain local  --pool-limit=100000 --pool-kbytes=500000` it panics with `Error: Service(Application(Application(Execution(Other("Exported method StarknetRuntimeApi_get_hasher is not found")))))`

**Comment by lambda-0x** [comment]
not able to reproduce this. are you running any transaction after starting local chain?
