### ISSUE TITLE
dev: verify compatibility with blockifier

### ISSUE THREAD

**Issue by greged93** [keep-starknet-strange/madara#745]
Some functions from `pallets/starknet/src/lib.rs` were taken from [blockifier](https://github.com/keep-starknet-strange/blockifier). Including but not limited to:
- `verify_tx_version`
- `handle_nonce`
- `validate_tx`
- ...

We need to verify that any changes to these functions in the last update of blockifier is applied to our functions, in order to support Cairo 1.0.

In order to have a PR accepted we need:
- A full list of impacted functions (hence all functions that have been copied from blockifier).
- Update to these functions in order to match the blockifier changes.
- Update to any test impacted and additional tests for any business logic update.

**Comment by lambda-0x** [comment]
i can work on this
