### ISSUE TITLE
Full End-to-End Guide for Deploying on Sharingan Testnet

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/madara#761]
---

**Describe the documentation you'd like**

A comprehensive, end-to-end guide for deploying on the Sharingan testnet. This guide should be broad and encompass various languages and SDKs, specifically starknet-rs, starknet-js, and starknet-py, among others. The objective of this guide is to provide developers with a clear understanding of how to deploy on the testnet using existing tooling and/or scripts in different languages. 

**Preferred Format**

The guide should be easy to understand and should be formatted as follows:

1. **Introduction:** Brief about Sharingan testnet, its applications and its importance.
2. **Pre-requisites:** List of things/programs required before the process begins.
3. **Step-by-Step Instructions:** A step-by-step process on how to deploy on the testnet. 
   - Section for each language/SDK.
   - Each step should have a brief explanation of what is happening.
   - Code snippets for each step where applicable.
   - Any images or diagrams that can be used to help illustrate the process.
4. **Troubleshooting:** Common errors and their solutions.
5. **Conclusion:** Final thoughts and a brief about what can be done after the deployment.

**Additional context or references**

Please include references or links to official resources that provide more detailed information about the Sharingan testnet and the specific SDKs (starknet-rs, starknet-js, starknet-py). 

**Who can help?**

Anyone with experience deploying on the Sharingan testnet using one or more of the SDKs listed above is encouraged to contribute. If you are a developer with experience in one of these areas, please consider sharing your expertise to help create this guide.

Thank you!

**Comment by rakesh9541** [comment]
can you assign it to me?? I would love to do this

**Comment by abdelhamidbakhta** [comment]
> can you assign it to me?? I would love to do this

Let’s go ! Assigned to you

**Comment by rakesh9541** [comment]
@abdelhamidbakhta I have made the pull request :)

**Comment by AnmolSirola** [comment]
@AbdelStark Can I take this issue ser :)

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
