### ISSUE TITLE
One-Click Application Packaging for Madara across MacOS, Linux, and Windows

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/madara#762]
---

**Feature Description**

We are looking for a solution that would allow users to run Madara as a full node on the Sharingan testnet with just one click. The application should support various platforms - MacOS, Linux, and Windows. Upon execution, it should employ a default configuration and immediately connect to the Sharingan testnet.

**Requirements**

1. **Packaging:** The application should be available as a downloadable package on the respective platform.
2. **One-Click Execution:** Once downloaded, users should be able to run the application with a single click.
3. **Default Configuration:** The application should automatically configure itself as a full node for the Sharingan testnet, using default settings.
4. **Connection to Sharingan Testnet:** Post-setup, the application should automatically connect to the Sharingan testnet.

**Preferred User Flow**

1. User downloads the application package suitable for their platform (MacOS, Linux, Windows).
2. User executes the downloaded package.
3. The application sets up Madara as a full node with default configuration.
4. The application connects to the Sharingan testnet.

**Who can help?**

Anyone with experience in application packaging and distribution across MacOS, Linux, and Windows platforms is invited to contribute to this feature. Furthermore, a basic understanding of the Madara full node setup and the Sharingan testnet would be beneficial.

Thank you!

**Comment by d-roak** [comment]
close #728 as duplicate and add #727 as a blocker for this

**Comment by apoorvsadana** [comment]
@abdelhamidbakhta can I pick this?

**Comment by abdelhamidbakhta** [comment]
> 

Sure, assigned to you

**Comment by tdelabro** [comment]
@apoorvsadana and this team did this during the Paris hackaton
