### ISSUE TITLE
Madara Kit: A Web Application for Interacting with Madara Chain

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/madara#764]
---

**Feature Description**

We are looking for contributors to create the "Madara Kit", a web application designed to interact with a Madara chain. 

**Requirements**

1. **Chain Information:** The web application should display basic information about the Madara chain, such as the details of the latest block.

2. **Transaction Capabilities:** The application should enable users to perform various actions, including:
   - Perform ERC20 transfers.
   - Mint NFTs (Non-Fungible Tokens).

3. **Deploy Cairo Contract:** Optionally, the application could include the ability to deploy a Cairo contract directly through the interface.

**Preferred User Flow**

1. User visits the Madara Kit web application.
2. User views the basic information about the Madara chain, including the latest block.
3. User chooses to perform an action (ERC20 transfer, NFT minting, or Cairo contract deployment).
4. The web application guides the user through the necessary steps and performs the chosen action on the Madara chain.

**Who Can Help?**

Contributors with experience in web development and interacting with blockchain networks, particularly the Madara chain, are highly encouraged to participate. Knowledge in ERC20 transfers, NFT minting, and Cairo contract deployment would be beneficial for this project.

If you want to build it in Rust for the fun feel free, there is an example here: https://github.com/keep-starknet-strange/madara-kit
However, it's not mandatory at all. You can of course go with a more traditional stack like React + TailwindCSS, or something else.

Thank you!

**Comment by abdelhamidbakhta** [comment]
> It should be like an explorer but with an interface like OZ Wizard?

Yes

**Comment by 0xlny** [comment]
Hey there! 

As discussed on TG, here is a first draft of what it could looks like: https://www.figma.com/file/6AyuP4IqYQaCFZ949bu0pv/Madara-Webkit?type=design&node-id=0%3A1&mode=design&t=pHmXvkiihQfXZlUx-1

Lmk what you think & if you need owner/editor access to the Figma :) I will iterate on it based on feedback.

**Comment by codeWhizperer** [comment]
Where do I set up the repository for the project and is there an available doc about  APIs to get details on blocks and transactions from the sequencer?

**Comment by abdelhamidbakhta** [comment]
There is already a repo: https://github.com/keep-starknet-strange/madara-kit
You can ignore what is inside it was just an example to use Rust to build the frontend but it was just an experiment. Let’s build it with a more classical stack such as React with Chakra UI as suggested by @0xlny

**Comment by codeWhizperer** [comment]
Alright, will get started with the project.

**Comment by codeWhizperer** [comment]
@abdelhamidbakhta The UI templates should be ready by tomorrow, I have started working on it. I bootstrapped the project with nextjs and tailwind CSS on a separate branch. I will raise a PR soon.

**Comment by abdelhamidbakhta** [comment]
> @abdelhamidbakhta The UI templates should be ready by tomorrow, I have started working on it. I bootstrapped the project with nextjs and tailwind CSS on a separate branch. I will raise a PR soon.
> 
> ![Screenshot_20230705_074821](https://user-images.githubusercontent.com/63842643/251060784-5742e5aa-cdc1-46a9-9638-6750cca5c448.png)

Awesome 😎
