### ISSUE TITLE
Creating a Modern, Responsive Landing Page for Madara Website

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/madara#765]
---

**Feature Description**

We are seeking contributors to help create a modern, responsive landing page for the Madara website. This landing page should present all relevant information about Madara in a comprehensive and attractive manner.

**Requirements**

1. **Modern and Responsive Design:** The landing page should follow contemporary design principles and should be responsive to ensure compatibility across various device types and screen sizes.

2. **Comprehensive Information:** The page should contain all relevant information about Madara, including but not limited to:
    - Overview of Madara
    - Key features and benefits
    - Use cases 
    - Any latest news or updates

3. **Highlighting Appchain Potential:** The main focus of the landing page should be to highlight Madara's potential for projects that want to run as an Appchain. It should effectively communicate the benefits and features of running as an Appchain.

**Preferred User Flow**

1. User visits the Madara website.
2. User is greeted with an attractive and informative landing page.
3. The user can navigate through the page to understand more about Madara, its features, and the benefits of running as an Appchain.

**Who Can Help?**

Contributors with experience in web development, particularly in creating modern, responsive web pages, are invited to contribute. Having a good understanding of Madara and its potential for projects wanting to run as an Appchain would be beneficial for this task.

Thank you!

**Comment by dbejarano820** [comment]
I can help with this

**Comment by dbejarano820** [comment]
@abdelhamidbakhta 
Can we create a new empty repo called `madara-web` or `madara-landing-page` for this?

**Comment by abdelhamidbakhta** [comment]
> @abdelhamidbakhta Can we create a new empty repo called `madara-web` or `madara-landing-page` for this?

assigned to you

**Comment by dbejarano820** [comment]
This can be closed
