### ISSUE TITLE
Implementing Autonomous Smart Contracts for Madara

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/madara#766]
---

**Feature Description**

We're seeking contributors to implement autonomous smart contracts for Madara. Inspiration can be drawn from the Mikasa hackathon project (https://github.com/mikasa-ack), which implements autonomous smart contracts for Ink! as a Substrate pallet. Some of the code from this project can be leveraged to accomplish our goal.

**Requirements**

1. **Autonomous Smart Contracts:** The implementation of autonomous smart contracts within Madara, similar to what has been accomplished within the Mikasa project.

2. **Code Reusability:** Leverage existing code from the Mikasa project where possible, adhering to DRY (Don't Repeat Yourself) principles.

3. **Configuration:** This feature should be optional and configurable at the Starknet pallet level, ensuring flexibility for users.

**Preferred User Flow**

1. User configures the Starknet pallet to enable autonomous smart contracts.
2. Autonomous smart contracts become available within the Madara environment.

**Who Can Help?**

Contributors with experience in smart contract development, particularly within a Substrate pallet context, are highly encouraged to participate. Familiarity with the Madara project, Starknet pallet, and the Mikasa hackathon project would be beneficial for this task.

Thank you!

**Comment by dbejarano820** [comment]
Will definitely be looking into this

**Comment by lana-shanghai** [comment]
I would like to tackle this one 🤓

**Comment by abdelhamidbakhta** [comment]
> I would like to tackle this one 🤓

please do!

**Comment by lana-shanghai** [comment]
@abdelhamidbakhta how do we want to treat the `sender` field of the `AsyncMessage`? In this implementation we just take the signed origin and convert it with `account_id_to_account_id32`. With madara, do we want to use a deployed account?

**Comment by EvolveArt** [comment]
> @abdelhamidbakhta how do we want to treat the `sender` field of the `AsyncMessage`? In the mikasa implementation we just take the signed origin and convert it with `account_id_to_account_id32`. With madara, do we want to use a deployed account?

I think so yes would make sense, account will always mean deployed account in the context of madara

**Comment by lana-shanghai** [comment]
> 

@EvolveArt should we keep track of which Substrate account deployed which account then? In that case we could check if the caller is indeed owner of that account in madara context

**Comment by lana-shanghai** [comment]
OK I have an idea. I will use the H256 of a Substrate account as salt.

**Comment by andyjsbell** [comment]
Can I help here?

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
