### ISSUE TITLE
dev: remove `PENDING` status 🔨

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#767]
In 0.12 Starknet will remove `PENDING` status for transactions.
We should also remove it, it was quite confusing anyway and can help simply a few different parts of the codebase.

**Blockers**

We need to wait for rpc specs + starknet-rs + starknet-js to remove it before.

**Comment by sparqet** [comment]
can I take this issue and are we able to remove it ?

**Comment by EvolveArt** [comment]
> can I take this issue and are we able to remove it ?

Wait 1/2 weeks for 0.12, should be good

**Comment by abdelhamidbakhta** [comment]
> > can I take this issue and are we able to remove it ?
> 
> Wait 1/2 weeks for 0.12, should be good

why ? we dont have to wait for 0.12, we can remove it now.

**Comment by sparqet** [comment]
I'm on it

**Comment by abdelhamidbakhta** [comment]
> I'm on it

hey, when will it be ready ?

**Comment by ayushtom** [comment]
Can i pick this if @sparqet has not picked yet?

**Comment by ayushtom** [comment]
https://github.com/keep-starknet-strange/madara/pull/971

**Comment by ayushtom** [comment]
#971 https://github.com/keep-starknet-strange/madara/pull/971

**Comment by ayushtom** [comment]
I found was that we never consume or write logic dependent on the pending state of transaction in the codebase.

Closest we come to writing logic based on `transaction status` is here -https://github.com/keep-starknet-strange/madara/blob/main/crates/client/rpc/src/lib.rs#L865

No other occurences came close to consuming this value.

We show this value in RPC Spec here for reference but this is used for readme and has no impact on codebase - https://github.com/keep-starknet-strange/madara/blob/main/crates/client/rpc-core/starknet_openRPC.json#L1883

I think we can close this issue if this sounds good to everyone.
