### ISSUE TITLE
dev: add different storage layouts as command line params 🔨

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#770]
**Current Behavior**

Right now the storage layout can either be `None` or similar to the public starknet (cf #667). In the future we might have different storage layouts (Ethereum, Pragma etc).

**Expected Behavior**

A new `storage-layout` option is added to the command line options.
It has 2 values : `=none` or `=default` which respectively corresponds to `EnableStateRoot = false` and `EnableStateRoot = true` in `pallets.rs` runtime config.

**Comment by dbejarano820** [comment]
once 667 is merged, i could take this
