### ISSUE TITLE
feat: store class hash and sierra program mapping

### ISSUE THREAD

**Issue by apoorvsadana** [keep-starknet-strange/madara#775]
# Feature Request

**Describe the Feature Request**

Once we have Declare V2 implemented from this #744, we will need a way to store the Sierra program which is passed from the RPC call. Right now, the Sierra program isn't stored anywhere and so we aren't able to return it when the user calls `get_class_at`. When storing this mapping, we must do it in a way that it is communicated to all the other nodes.

**Describe Preferred Solution**

We can implement this in the run time but that should be our last option as the runtime should only have the information needed for the chain state. The Sierra program is not essential for the chain state and so we must store them elsewhere. The db in the client isn't gossiped between the nodes and is a local copy. So we need to explore how we can get this done.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

Yes

**Comment by apoorvsadana** [comment]
the implementation here would mostly use the same approach used here #723

**Comment by apoorvsadana** [comment]
@tdelabro can we open this issue as well

**Comment by tdelabro** [comment]
I think I'm tackling this in my refactoring PR

**Comment by apoorvsadana** [comment]
Oh ok, awesome!

**Comment by tdelabro** [comment]
Actually I think this is still required

**Comment by tdelabro** [comment]
closed by #1409
