### ISSUE TITLE
feat: Check `compiled_class_hash` inside the pallet

### ISSUE THREAD

**Issue by apoorvsadana** [keep-starknet-strange/madara#789]
# Feature Request

**Describe the Feature Request**

Currently, the`compiled_class_hash` is checked in the client in declare v2. This creates a vulnerability because a node can choose not to verify the `compiled_class_hash` and accept transactions. Other nodes will not be able to check this as there is no check in the runtime. 

Right now, the sierra compiler doesn't support `no_std` because of which it's not possible to have this check in the runtime. However, `no_std` for the compiler is in the roadmap and we must move this check to the runtime whenever that is implemented.

**Describe Preferred Solution**

I think we should implement this check `validate_unsigned` but open to discuss.

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

Yes

**Comment by abdelhamidbakhta** [comment]
@apoorvsadana you want to tackle it ?

**Comment by apoorvsadana** [comment]
Sure, you can assign it to me but we would need no_std in the Sierra compiler before we can build this. I can pick this up once we've that :)

**Comment by apoorvsadana** [comment]
@abdelhamidbakhta, can we remove this from the stale issue. I think it's a critical bug that shouldn't ship to prod, this issue will help us keep track of it

**Comment by abdelhamidbakhta** [comment]
> @abdelhamidbakhta, can we remove this from the stale issue. I think it's a critical bug that shouldn't ship to prod, this issue will help us keep track of it

good point, done.
@tdelabro we need to prioritize it for next sprint, or even this one if someone could tackle it

**Comment by tdelabro** [comment]
Will probably be unlocked by #1407
