### ISSUE TITLE
feat: get `entry_points_by_type` for ContractClassV1 in RPC calls

### ISSUE THREAD

**Issue by apoorvsadana** [keep-starknet-strange/madara#790]
# Feature Request

**Describe the Feature Request**

RPC calls `get_class_at` and `get_class` use `to_rpc_contract_class` to convert a blockifier ContractClass to the starknet-rs one. For V1, we need to convert `entry_points_by_type` from  a `HashMap<EntryPointType, Vec<EntryPointV1>>` (from blockifier) to an instance of `EntryPointsByType` (from starknet-rs). We will need a way to figure out how to get the `function_idx` which is required fro `EntryPointsByType`. A good start for this is to refer to how we went from `function_idx` to `offset` and `bultins` over [here](https://github.com/keep-starknet-strange/cairo/blob/64ef5864c5b92ee40b46ecb0b6fd854bd790938d/crates/cairo-lang-starknet/src/contract_class_into_casm_contract_class.rs#L194). 

In case it's impossible to convert back (I am not sure of this as of yet), we might need to store this along with the Sierra program over here #775

**Comment by tchataigner** [comment]
Hey hey ! I'm interested in making my first contribution and I was thinking in handling this one :raised_hands: 

I'm currently investigating the method to get `function_idx`. I'll let you know in a few hours if I could not find a way to get it :+1:

**Comment by apoorvsadana** [comment]
Hey @KaushikKC, awesome! @tdelabro can you assign this to him?

**Comment by tdelabro** [comment]
@antiyro it seems to be related to the problem you are experiencing with deoxys right now

**Comment by Juul-Mc-Goa** [comment]
Hi, I'd like to work on this :)
(I'm just starting to work on this project btw, so I might need a bit of help)

**Comment by tdelabro** [comment]
One at a time. Focus on #704 for now

**Comment by somthn0somthn** [comment]
Is this still open and relevant?

**Comment by tdelabro** [comment]
@somthn0somthn I think the entry points by type part is doable. You can start with this.
The sierra_program part looks uncertain to me. Don't try for now

**Comment by somthn0somthn** [comment]
Gotcha. Thanks!

**Comment by mbtariq82** [comment]
Hey, can i take this?

**Comment by apoorvsadana** [comment]
Sure, assigned @mbtariq82!

**Comment by tdelabro** [comment]
replaced by #1316
