### ISSUE TITLE
bug: Deploy transaction for Cairo 1 contracts

### ISSUE THREAD

**Issue by apoorvsadana** [keep-starknet-strange/madara#794]
Decalre v2 is working and Cairo 1 contracts can be deployed to Madara once #744 is merged. Sample code for the same can be found in `addDeclareTransaction` tests in the `test-starknet-rpc.ts`. However, deploying the same contract gives the error `InvalidTransaction::BadProof`.

**Comment by tdelabro** [comment]
I don't understand. Is it working or not?

**Comment by apoorvsadana** [comment]
Declaring is working but not deploying.

**Comment by apoorvsadana** [comment]
I can do this @abdelhamidbakhta

**Comment by abdelhamidbakhta** [comment]
> I can do this @abdelhamidbakhta

Let’s go

**Comment by apoorvsadana** [comment]
@abdelhamidbakhta, @LucasLvy has already fixed this here - #814, I have created a small PR just to add account deployment tests - #816 (I checked out from Lucas' branch so we should merge that first)

**Comment by apoorvsadana** [comment]
@abdelhamidbakhta we can close this now :)
