### ISSUE TITLE
feat: update `estimateFee` according to new spec

### ISSUE THREAD

**Issue by apoorvsadana** [keep-starknet-strange/madara#795]
`estimateFee` takes an array of requests instead of a single request based on the new RPC spec - https://github.com/starkware-libs/starknet-specs. The feature will be to adapt Madara's `estimateFee` function according to the new spec.

As a part of this, we will also need to fix the TS estimateFee test cases which won't work after we merge #744

**Comment by exp-table** [comment]
Count on me to do it 🏄‍♂️

**Comment by abdelhamidbakhta** [comment]
> Count on me to do it 🏄‍♂️

Let’s go
