### ISSUE TITLE
bug: correctly set `compiled_class_hash` in `DeclareTransaction`

### ISSUE THREAD

**Issue by apoorvsadana** [keep-starknet-strange/madara#796]
#744 has a bug in `transaction/mod.rs` where inside `impl TryInto<DeclareTransaction> for &Transaction` we set the `compiled_class_hash` equal to `class_hash`. This is because `compiled_class_hash` is not yet implemented in `CallEntryPoint` in blockifier @LucasLvy. Once this is done, we can fix this issue.

**Comment by edisontim** [comment]
Hey, is the the CallEntryPoint in blockifier implemented? I can't find it but neither can I find an issue related to its implementation

**Comment by sparqet** [comment]
Are we able to fix it now ?

**Comment by sparqet** [comment]
I think yes, so may I take this one ?

**Comment by apoorvsadana** [comment]
Sorry for the late reply guys. This hasn't been implemented it in the blockifier yet. @LucasLvy, can someone do that as a part of this issue itself?

**Comment by tdelabro** [comment]
There will be big change in the implem of this soon. I'm working on it. It should most likely solve the issue

**Comment by mbtariq82** [comment]
Hey,
Is this still open and if so can i take it? This is my first contribution so might need some help.

**Comment by apoorvsadana** [comment]
Hey @mbtariq82, thanks for taking the initiative. Unfortunately, this issue is closed now, we should have closed it earlier. However, there are a lot of other issues you can pick up! Do let me know if you need help in finding an issue.
