### ISSUE TITLE
dev: add weights benchmarking to `starknet` pallet 

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#818]
Discovered the following error message in the `ERC721 MINT` benchmark in #801 CI : 
```
Discarding proposal for slot 281416161; block production took too long 
```
But **ONLY** for the ERC721 mint benchmark, the erc20 is running perfectly fine. 
It seems that it's finally time we pay for ignoring the weight system of substrate.

**Current Behavior**

Starknet pallet's extrinsics have a default 0 weight, we just don't use the [weight system](https://docs.substrate.io/build/tx-weights-fees/) for now.
However this is problematic, because weights are used to **stop** block production at the right time and avoid what we call *overfilling*. This is a huge attack vector that is currently possible, you can read more about it [here](https://substrate.stackexchange.com/a/6732).

**Expected Behavior**
The weight system is how substrate figures out how much computation is going into the blocks. 
Substrate expects the weight to be as accurate as possible for the **_worst case_**.

**Approach**

One possible approach is to follow the path of `frontier` and do the following steps : 
1. [Benchmark steps/gas <-> weight mapping](https://github.com/paritytech/frontier/blob/3c75079ed627ec83db88ca78d2ea4d4da6b3d8af/frame/evm/src/benchmarking.rs#L32)
2. [Add `BLOCK_GAS_LIMIT` as a pallet config parameter](https://github.com/paritytech/frontier/blob/3c75079ed627ec83db88ca78d2ea4d4da6b3d8af/template/runtime/src/lib.rs#L316)
3. [Write `weight_to_gas` function](https://github.com/paritytech/frontier/blob/master/primitives/evm/src/lib.rs#L231)
4. [Add weight computation on pallet's extrinsics](https://github.com/paritytech/frontier/blob/3c75079ed627ec83db88ca78d2ea4d4da6b3d8af/frame/ethereum/src/lib.rs#L275)
5. [Create `GasWeightMapping` trait and write a simple implementation](https://github.com/paritytech/frontier/blob/3c75079ed627ec83db88ca78d2ea4d4da6b3d8af/frame/evm/src/lib.rs#L742C11)

Some open questions left : 
- _We need to set `gas_per_step` somewhere ? Where and how ?_ Probably in the pallet's config.
- _Should we have a minimum target of gas/step within a block ?_ I don't think so.
- _GasLimitPovSizeRatio_ ? I don't know what it refers to.

**UPDATE**

Action Items:

- [ ] Every extrinsic should return the weight corresponding to the maximum of steps defined in the runtime config
- [ ] Implement a simple FCFS ordering policy
- [ ] Explore new ordering policies implementation and how they should fit in the overall architecture

**Comment by justinFrevert** [comment]
@EvolveArt trying to give comments where I can:

I guess `gas` can be replaced with `step` within this proposal if I understood that tg chat correctly.

If we want to follow Frontier's approach of gas<-> weight mapping, `3.` could maybe include a `steps_to_weight` function? Maybe this can help answer the `gas_per_step` question since having both functions completes the mapping.

**Comment by tdelabro** [comment]
Closed after investigation. See result here: https://github.com/keep-starknet-strange/madara/discussions/968

**Comment by EvolveArt** [comment]
https://github.com/paritytech/substrate/issues/1354

**Comment by tdelabro** [comment]
@apoorvsadana do you think you can take care of creating this gas to weight mapping and impl it in the pallet starknet, using tx.max_weight ?

**Comment by apoorvsadana** [comment]
Yep. I can start working on this after Devconnect. Assigned to myself.
