### ISSUE TITLE
dev: split integration tests into multiple files 🔨

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#824]
**Current Behavior**

All integration tests currently sit in `test-starknet-rpc.ts` which is becoming quite large.

**Expected Behavior**

Split these tests within multiple files, you can follow the organization of the `starknet` pallet tests folder.

**Comment by MdTeach** [comment]
@EvolveArt I would love to take this

**Comment by abdelhamidbakhta** [comment]
> @EvolveArt I would love to take this

let's go
