### ISSUE TITLE
dev: improve error message in `pallet/starknet`

### ISSUE THREAD

**Issue by greged93** [keep-starknet-strange/madara#827]
Go through the codebase and improve the current error messages we are receiving. This is an example of a [bad error message](https://github.com/keep-starknet-strange/madara/blob/main/crates/pallets/starknet/src/lib.rs#L533):
```
log!(error, "Transaction execution failed: {:?}", e);
```
It doesn't give enough context on the failure: is the failure inside `invoke`, `declare` or `deploy_account`? 

Another example can be [here](https://github.com/keep-starknet-strange/madara/blob/main/crates/pallets/starknet/src/lib.rs#L1115). This message doesn't clearly explain that the failure happened during an estimate fee, which can be helpful when debugging.

**Comment by sparqet** [comment]
Hi can I take this issue ?

**Comment by greged93** [comment]
sure, assigned!
