### ISSUE TITLE
feat: optional charging of fees

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/madara#847]
# Feature Request

Make the charing of fees optional.
Introduce a new config in the pallet and make it optional.
Add relevant tests.

**Comment by jobez** [comment]
ill take it ser

**Comment by apoorvsadana** [comment]
@abdelhamidbakhta, spoke to @EvolveArt, I will pick this up

**Comment by abdelhamidbakhta** [comment]
> @abdelhamidbakhta, spoke to @EvolveArt, I will pick this up

Awesome thanks
