### ISSUE TITLE
bug: contract call on non existing contract returns the wrong error message

### ISSUE THREAD

**Issue by ClementWalter** [keep-starknet-strange/madara#853]
# Bug Report

## Current behavior

Taking a random contract address as example, the behavior on goerli is

```
starkli call 0x01e96d9d047081203a40639c05ba879be96e91e612e000fc10b94c17bbd61062 bytecode
WARNING: no valid provider option found. Falling back to using the sequencer gateway for the goerli-1 network.
Error: Contract not found
```

while on madara it's:

```
starkli call 0x01e96d9d047081203a40639c05ba879be96e91e612e000fc10b94c17bbd61062 bytecode --rp
c=http://127.0.0.1:9944
Error: Contract error
```

## Wat do

Fix the returned error here:
https://github.com/keep-starknet-strange/madara/blob/a24d36520d035fb7629a1ad11fe2f0968c0472ef/crates/client/rpc/src/lib.rs#L247

to return Contract not found if the contract does not exist.

**Other information:**

starkli is 🔥

**Comment by MdTeach** [comment]
@ClementWalter I would love to take this

**Comment by ayushtom** [comment]
@MdTeach if you're aren't working on this right now, can I pick it up?

**Comment by MdTeach** [comment]
@ayushtom I'm still on it I should be done by this week.
