### ISSUE TITLE
dev: move chain_id into the config rather than the storage

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#861]
The `chain_id` is currently stored in the storage
```rust
    #[pallet::storage]
    #[pallet::getter(fn chain_id)]
    pub(super) type ChainId<T: Config> = StorageValue<_, Felt252Wrapper, ValueQuery>;
```

Meaning that, in theory, this value could be changed at any time. It would be more coherent to have it as a const declared in the pallet Config.

**Comment by lambda-0x** [comment]
i can work on this

**Comment by tdelabro** [comment]
@lambda-0x please go ahead!
