### ISSUE TITLE
bug: Reading balance_of ERC20 Cairo 1 contract

### ISSUE THREAD

**Issue by aymericdelab** [keep-starknet-strange/madara#862]
# Bug Report

**Madara version:**
41e8ca4dc3b5622191fc95fad48870e1927c3275

**Current behavior:**
Calling balance_of in deployed erc20 contract in test-cairo-1.ts throws an error:
```
 LibraryError: 40: Contract error
      at RpcProvider.errorHandler (node_modules/starknet/src/provider/rpc.ts:96:13)
      at RpcProvider.fetchEndpoint (node_modules/starknet/src/provider/rpc.ts:107:12)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async RpcProvider.callContract (node_modules/starknet/src/provider/rpc.ts:416:20)
      at async Context.<anonymous> (tests/test-starknet-rpc/test-cairo-1.ts:163:27)
``` 

**Expected behavior:**
Should be able to call view functions from deployed contract.

**Steps to reproduce:**
I'm adding this line in test "should declare and deploy erc20 contract then transfer some tokens", after deploying the contract and calling transfer
```
const balanceOf = await providerRPC.callContract({contractAddress: deployRes.contract_address[0], entrypoint: "balance_of", calldata: [CAIRO_1_ACCOUNT_CONTRACT]});
```

**Comment by tdelabro** [comment]
Can we test this again to see if it is still broken

**Comment by KaushikKC** [comment]
Can i work on this ?

**Comment by apoorvsadana** [comment]
This should be solved already @KaushikKC. @lana-shanghai can you confirm?

**Comment by tdelabro** [comment]
@KaushikKC you can try to reproduce if you want, and tell us if it has been fixed

**Comment by tdelabro** [comment]
I think it has been solved. Reopen if I'm wrong
