### ISSUE TITLE
Remove patched crates when `rocksdb` is compatible with `cranelift`

### ISSUE THREAD

**Issue by ZePedroResende** [keep-starknet-strange/madara#87]
A [patch](https://github.com/rust-rocksdb/rust-rocksdb/pull/760) was summited for `librocksdb-sys` to enable rustc_codegen_cranelift compilation.  
 However the version used as a dependency on this project is older so we created a new fork of the specific version needed with the `cranelift` patch in this [repo](https://github.com/finiam/rust-rocksdb/tree/patch/0.19.0).
 When the `rocksdb` version that is compatible with `rustc_codegen_cranelift` is being used by default we can remove the patch version from the Cargo file.

**Comment by LucasLvy** [comment]
resolved #96
