### ISSUE TITLE
bug: When submitting a declare tx with debug_info, madara fails

### ISSUE THREAD

**Issue by ClementWalter** [keep-starknet-strange/madara#873]
# Bug Report

**Madara version:**

**Current behavior:**

Send a declare tx with a contract compiled with `debug_info`, fails with error

```
Failed to submit extrinsic: Pool(TooLowPriority { old: 18446744073709551615, new: 18446744073709551615 })
```

**Expected behavior:**

Pass with or without debug_info, or at least raises "do not support debug_info"

**Steps to reproduce:**

Compile a Cairo 0 contract with or without the `--no-debug-info` flag and try to declare it to `madara`

**Comment by geraldzm** [comment]
Is this still needed ? 

Would be interested to work on this issue, I'm still learning the codebase though

**Comment by geraldzm** [comment]
Is this still needed? 

would be interested to work on this issue :), I'm Still learning the codebase though
