### ISSUE TITLE
feat: integration with Substrate L1 (Tangle Network)

### ISSUE THREAD

**Issue by drewstone** [keep-starknet-strange/madara#877]
# Feature Request

**Describe the Feature Request**

Looking for insight/advice on where to begin to integrate this directly into a standalone Substrate chain. We would use Substrate validators to sequence the rollup in addition to validating the L1. Possibly I'm off base in my thinking here (since the validators would be dual-purpose) but proposing it as a topic for discussion and exploration.

We're building [Tangle](https://tangle.webb.tools/), a standalone Substrate based chain running both an EVM and an threshold MPC. Providing a place for rollups to innovate is core to our mission of being on the cutting edge. We'd be interested to explore adding this system to Tangle to extend its functionality for Starknet contracts.

**Describe Preferred Solution**

I currently see that this uses ETH L1 to read messages from. We would instead be looking to generalize this purpose to an arbitrary L1, be it Substrate or a different EVM (such as Substrate's Frontier). It could leverage any chain's finality.

**Describe Alternatives**

**Related Code**

**Additional Context**

- [Our repo](https://github.com/webb-tools/tangle)

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

Yes w/ assistance (and can propose a grant to W3F/Polkadot)

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
