### ISSUE TITLE
dev: Add InvalidTransactionType Invariant StarknetApiError in PR #826

### ISSUE THREAD

**Issue by MavericksFive** [keep-starknet-strange/madara#878]
In PR #826, the handling of incorrect transaction types in the mod.rs file located at [File]/crates/primitives/darknet/src/transaction/mod.rs is incorrect.

Currently, the StarknetApiError returned for incorrect transaction types is OutOfRange. However,  it should return an InvalidTransactionType error to more accurately reflect the nature of the issue.

This suggests that StarknetApiError does not currently handle this case with a specific invariant. It may be necessary to fork StarknetApiError or modify its behavior to handle this case more accurately.

Related PR: [#826]

**Comment by nicobevilacqua** [comment]
I'm having issues running `cargo test` on that branch.
Should I do something special?
<img width="732" alt="image" src="https://github.com/keep-starknet-strange/madara/assets/5586894/e46ef14b-cb75-4de2-b2cd-bb319853ee20">

**Comment by MavericksFive** [comment]
Hey @nicobevilacqua, it's normal, tests are not refactored yet! (There is another issue on that point)

**Comment by nicobevilacqua** [comment]
I've added a new error type in the starknet-api repo. Lmk if that what you thought and I'd create a PR
https://github.com/nicobevilacqua/starknet-api-InvalidTransactionType/commit/a06a6d8f6c80cf111864aca1dba7be7d24b908f3

**Comment by nicobevilacqua** [comment]
I've removed the string parameter here: https://github.com/nicobevilacqua/starknet-api-InvalidTransactionType/commit/731c19f02bc98cd695a28de8f0aa0300ce7c83d8 and I've changed the error here
https://github.com/nicobevilacqua/madara-InvalidTransactionType-Invariant-StarknetApiError-fix/commit/5be292053355672e32340b8a959c04fb3adbe823

Let me know if that's ok and I'll create the PRs on both repos

**Comment by lana-shanghai** [comment]
@tdelabro this issue depends on the closed PR [826](https://github.com/keep-starknet-strange/madara/pull/826) why was it closed?

**Comment by lana-shanghai** [comment]
Hey @nicobevilacqua really sorry but @tdelabro informed us that the PR 826 will not be reopened and that this issue needs to be closed too :( can you let us know in telegram how much time you spent researching and you will get paid for the time spent. @tdelabro let's please find another issue for him.

**Comment by nicobevilacqua** [comment]
Hey @lana-shanghai.

No problem, It was just 3 hours (It took me a while to understand the project and the requirement but the change was quite easy).
