### ISSUE TITLE
dev:  Refactoring all the test considering considering the change of Transaction to an enum in PR #826

### ISSUE THREAD

**Issue by MavericksFive** [keep-starknet-strange/madara#880]
In PR https://github.com/keep-starknet-strange/madara/pull/826, refactor all the tests impacted by Transaction struct to enum changes.

Related PR: [https://github.com/https://github.com/keep-starknet-strange/madara/pull/826]

**Comment by TedZy829** [comment]
Hi, I'm interested in taking this issue, can i get a further explanation about what's the issue about?

**Comment by lana-shanghai** [comment]
> Hi, I'm interested in taking this issue, can i get a further explanation about what's the issue about?

Assigned you! If you look at the first commit, especially the `types.rs` file, you will see that there is a major type refactoring going on, mainly from struct to enum. It will break a lot of tests along with the change, so they need to be fixed too. Also there are a couple of unaddressed comments from @LucasLvy there.

**Comment by TedZy829** [comment]
hmm...so in order to fix this issue, i should run each and every test, and if there is an error, i should fix the error? is that a way to do the test, or do you propose another way to do it?

**Comment by tdelabro** [comment]
Wiil be changed in incoming big refacto. See: https://github.com/tdelabro/madara/tree/simplify-tx-types
