### ISSUE TITLE
ci: cleanup cache for a PR when the workflow finishes

### ISSUE THREAD

**Issue by d-roak** [keep-starknet-strange/madara#882]
Currently, workflows might fail due to poisoned caches

**Comment by harsiddhdave44** [comment]
@d-roak Can you please provide some more details? 
Currently, the Pull Request Close workflow is failing, which seems to be happening due to a missing secret.

**Comment by tdelabro** [comment]
It happened to me. How do I fix this? At least for my PR

**Comment by tdelabro** [comment]
So for now, the repo maintainers are able to manually remove the existing caches, and it will be successful on next CI launch. 
But it would be great if we have a way to clean those automatically.
I don't know if it should be done after each run, or every X time, or under some other contiditions.

@d-roak you already did some work on the CI, would you like to do some research on this too?

**Comment by d-roak** [comment]
We can't do it with in our current use case. I'll restructure it
ref: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

**Comment by tdelabro** [comment]
Should I take it out of the sprint? Postpone it to a later one?
