### ISSUE TITLE
feat: narwhal&bullshark consensus compatible with substrate

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/madara#897]
### Description

The goal of this issue is to implement the Narwhal and Bullshark consensus algorithms in a way that is compatible with the Substrate framework. This will allow Madara to leverage the benefits of these consensus algorithms and the Substrate's modular framework.

### Background

Narwhal and Bullshark are consensus protocols that use a Directed Acyclic Graph (DAG) structure for efficient propagation and validation of transactions across the network. They also use Byzantine Fault Tolerance (BFT) algorithms to ensure consensus can be reached even in the presence of malicious or faulty nodes. 

Narwhal uses a leaderless approach, with all nodes in the network participating equally in the consensus process. Bullshark, on the other hand, is optimized for the common synchronous case and provides a practical low latency fast-path, making it more efficient in certain scenarios.

### Tasks

1. **Research**: Understand the Narwhal and Bullshark consensus algorithms and how they can be integrated with the Substrate framework.
2. **Design**: Create a design document detailing how these consensus algorithms will be implemented in Madara. This should include any necessary changes to the existing architecture.
3. **Implementation**: Implement the design, ensuring that the new consensus algorithms are fully compatible with Substrate.
4. **Testing**: Write comprehensive tests to ensure the new consensus algorithms work as expected and do not introduce any regressions.
5. **Documentation**: Update the project documentation to reflect the new consensus algorithms.

### Acceptance Criteria

- The Narwhal and Bullshark consensus algorithms are fully implemented and compatible with the Substrate framework.
- The implementation passes all tests.
- The project documentation is updated to reflect the new consensus algorithms.

### Resources

- [Narwhal Consensus Mechanism](https://docs.sui.io/learn/architecture/consensus)
- [Bullshark Consensus Mechanism](https://arxiv.org/abs/2105.11827)
- [Narwhal Rust Implementation in Sui Repository](https://github.com/MystenLabs/sui/tree/main/narwhal)

**Comment by adizere** [comment]
Interesting. I'm curious, what is the problem being solved exactly? I'm trying to understand why Narwhal/Bullshark specifically. Is it that current framework is centralized, or an efficiency problem, or performance, or stability?

**Comment by gogo2464** [comment]
Hello. I am interested in coding because I would like to generate proof of execution. Is it an interesting to contribute to this please?

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
