### ISSUE TITLE
feat: besu's bonsai storage layout like primitives

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/madara#898]
### Description

The goal of this issue is to investigate and build primitives to implement a storage layout and optimization techniques similar to Besu Bonsai. Unlike other clients that store nodes of the world state by hash, Bonsai stores them by location in the trie. This approach enables natural pruning by replacing old nodes at the same position in the trie with the new ones.

### Background

Besu Bonsai's technique ensures that there is only one version of the state at any given time. Consequently, it does not support managing reorganizations (reorgs) as it only maintains a single state. Bonsai addresses this limitation by introducing "trielogs".

### Tasks

1. **Research**: Understand the Besu Bonsai storage layout and optimization techniques, and how they can be implemented in Madara.
2. **Design**: Create a design document detailing how the Besu Bonsai-like storage layout and optimization techniques will be implemented in Madara. This should include any necessary changes to the existing architecture.
3. **Implementation**: Implement the design, ensuring that the new storage layout and optimization techniques are fully functional.
4. **Testing**: Write comprehensive tests to ensure the new storage layout and optimization techniques work as expected and do not introduce any regressions.
5. **Documentation**: Update the project documentation to reflect the new storage layout and optimization techniques.

### Acceptance Criteria

- The Besu Bonsai-like storage layout and optimization techniques are fully implemented.
- The implementation passes all tests.
- The project documentation is updated to reflect the new storage layout and optimization techniques.

### Resources
- [Bonsai design article](https://hackmd.io/@kt2am/BktBblIL3)
- [Besu Bonsai implementation](https://github.com/hyperledger/besu/tree/1a7635bc3ef75c31e5c5ac050b2cd3a22d833ada/ethereum/core/src/main/java/org/hyperledger/besu/ethereum/bonsai)

**Comment by tdelabro** [comment]
Here it is: https://github.com/keep-starknet-strange/bonsai-trie
