### ISSUE TITLE
feat: compute state root in client instead of runtime

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/madara#900]
### Description

The goal of this issue is to move the computation of the global state root from the runtime to the client. This computation is a heavy process that consumes a lot of time and resources in the block production. By moving it to an asynchronous task, we can speed up block production.

### Background

Currently, the global state root is computed as defined in the Starknet specs and fed into the block. A potential solution to speed up this process would be to include the state root of block N - 1 in the block header N, instead of the state root of the block N. However, for this to save time, it would need to be done in an asynchronous manner.

### Tasks

1. **Research**: Understand the current process of computing the global state root and how it can be moved to the client.
2. **Design**: Create a design document detailing how the global state root computation will be moved to the client and made asynchronous. This should include any necessary changes to the existing architecture.
3. **Implementation**: Implement the design, ensuring that the new process for computing the global state root is fully functional and improves block production speed.
4. **Testing**: Write comprehensive tests to ensure the new process for computing the global state root works as expected and does not introduce any regressions.
5. **Documentation**: Update the project documentation to reflect the new process for computing the global state root.

### Acceptance Criteria

- The global state root is computed in the client instead of the runtime.
- The computation of the global state root is done asynchronously.
- The implementation passes all tests.
- The project documentation is updated to reflect the new process for computing the global state root.

### Resources

- #179 
- #130

**Comment by tdelabro** [comment]
@antiyro you are working on this aren't you?

**Comment by tdelabro** [comment]
> @antiyro you are working on this aren't you?

he is

**Comment by tdelabro** [comment]
@antiyro when integration in madara?

**Comment by hhamud** [comment]
@tdelabro @apoorvsadana  if @antiyro or anyone else is not working on this one then I can grab this issue

**Comment by tdelabro** [comment]
@hhamud thanks but @antiyro is currently on it

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
