### ISSUE TITLE
feat: Implement AlephBFT Consensus in Madara

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/madara#909]
### Description

The goal of this issue is to implement the AlephBFT consensus algorithm in Madara. AlephBFT is a peer-reviewed consensus protocol that is used in the Aleph Zero blockchain. This will allow Madara to leverage the benefits of the AlephBFT consensus algorithm.

### Background

AlephBFT is a unique consensus algorithm used in the Aleph Zero blockchain. It is implemented in Rust and is based on the Substrate framework. The Aleph node is based on a Substrate node where the default finality gadget (GRANDPA) has been replaced with AlephBFT. Block authoring is realized with Substrate's Aura.

### Tasks

1. **Research**: Understand the AlephBFT consensus algorithm and how it can be integrated with Madara.
2. **Design**: Create a design document detailing how the AlephBFT consensus will be implemented in Madara. This should include any necessary changes to the existing architecture.
3. **Implementation**: Implement the design, ensuring that the new consensus algorithm is fully functional.
4. **Testing**: Write comprehensive tests to ensure the new consensus algorithm works as expected and does not introduce any regressions.
5. **Documentation**: Update the project documentation to reflect the new consensus algorithm.

### Acceptance Criteria

- The AlephBFT consensus algorithm is fully implemented in Madara.
- The implementation passes all tests.
- The project documentation is updated to reflect the new consensus algorithm.

### Resources

- [AlephBFT Documentation](https://docs.alephzero.org/aleph-zero/explore/alephbft-consensus)
- [AlephZero Substrate Node](https://github.com/Cardinal-Cryptography/aleph-node/tree/main)

**Comment by hhamud** [comment]
hey can I take this one?

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
