### ISSUE TITLE
feat: Implement HotStuff Consensus in Madara

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/madara#912]
### Description

The goal of this issue is to implement the HotStuff consensus algorithm in Madara. HotStuff is a consensus protocol used in the Diem blockchain. This will allow Madara to leverage the benefits of the HotStuff consensus algorithm.

### Background

HotStuff is a consensus protocol that is used in the Diem blockchain. It is implemented in Rust and is designed to be small, efficient, and easy to benchmark and modify. It uses real cryptography (dalek), networking (tokio), and storage (rocksdb).

### Tasks

1. **Research**: Understand the HotStuff consensus algorithm and how it can be integrated with Madara.
2. **Design**: Create a design document detailing how the HotStuff consensus will be implemented in Madara. This should include any necessary changes to the existing architecture.
3. **Implementation**: Implement the design, ensuring that the new consensus algorithm is fully functional.
4. **Testing**: Write comprehensive tests to ensure the new consensus algorithm works as expected and does not introduce any regressions.
5. **Documentation**: Update the project documentation to reflect the new consensus algorithm.

### Acceptance Criteria

- The HotStuff consensus algorithm is fully implemented in Madara.
- The implementation passes all tests.
- The project documentation is updated to reflect the new consensus algorithm.

### Resources

- [HotStuff Paper](https://arxiv.org/abs/2106.10362)
- [HotStuff Rust Implementation](https://github.com/asonnino/hotstuff)

Please feel free to contribute to this issue. Any help is appreciated!

**Comment by lukeglwang** [comment]
Excited to make this key functionality happen together
