### ISSUE TITLE
dev: Make the client runtime agnostic

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#919]
Substrate is designed so that the client does not have to know about the runtime.
This allows for two things:
- runtime upgrage
- reuse the same code for different versions of the chain (testnet, mainnet, ...)

We are currently using the `madara-runtime` crate as a dependency in multiple crates in `crates/client/`. This has to stop.

Tasks:
- [x] remove it from the `rpc` crate imports
- [x] remove it from the `storage` crate imports. This will require a rework of the way starknet events are read. Maybe we cannot read them directly from the pallet `system` storage and will have to relly only on the `RuntimeApi`

**Comment by EvolveArt** [comment]
I'll work on this

**Comment by EvolveArt** [comment]
@tdelabro Just to confirm, we should also remove `pallet-starknet` dependency from client right ?

**Comment by tdelabro** [comment]
I think so, yes. What is being imported from it?

**Comment by EvolveArt** [comment]
> I think so, yes. What is being imported from it?

`use pallet_starknet::runtime_api::{ConvertTransactionRuntimeApi, StarknetRuntimeApi};` so we cannot really remove it

**Comment by tdelabro** [comment]
Ok so let's keep it. It's not the runtime but the pallet. It will stay the same across different runtimes
