### ISSUE TITLE
doc: translate Madara article and website to Portuguese

### ISSUE THREAD

**Issue by abdelhamidbakhta** [keep-starknet-strange/madara#921]
# Feature Request

Translate this article: https://starknet-website-cms-posts-harnessing-the-beast-madara-an.yukilabs.workers.dev/en/posts/ecosystem/harnessing-the-beast-madara-and-the-revolution-of-starknet-appchains

Translate the website: madara.zone

**Comment by abdelhamidbakhta** [comment]
> I can take the article for now

thank you, assigned to you!

**Comment by d-roak** [comment]
@joaopereira12 will do the translation of:
https://madara.zone/
https://docs.madara.zone/

**Comment by abdelhamidbakhta** [comment]
> @joaopereira12 will do the translation of: https://madara.zone/ https://docs.madara.zone/

amazing! thank you @joaopereira12

**Comment by pedrovalido** [comment]
dropping this issue to give it to @joaopereira12

**Comment by joaopereira12** [comment]
I can make those translations @d-roak

**Comment by d-roak** [comment]
I'm really good at self-assigning 😅
Assigned
