### ISSUE TITLE
doc: translate Madara article and website to German

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/madara#923]
# Feature Request
Translate this article: https://starknet-website-cms-posts-harnessing-the-beast-madara-an.yukilabs.workers.dev/en/posts/ecosystem/harnessing-the-beast-madara-and-the-revolution-of-starknet-appchains

Translate the website: madara.zone

**Comment by abdelhamidbakhta** [comment]
> gib me

Sure thing bro

**Comment by anaminguyen** [comment]
Hi @abdelhamidbakhta and @welttowelt, can I pick this up?

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
