### ISSUE TITLE
tracking: Translation of Madara content to different languages

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/madara#924]
- #921 
- #922 
- #923 
- #926

**Comment by dbejarano820** [comment]
Do we need spanish?

**Comment by Immanuelolivia1** [comment]
I want to work on the Chinese translation

**Comment by Xaxxoo** [comment]
According to google search, as at 2001, there are over  88 million Hausa speakers in the world and the language is spoken in over 8 countries in Africa. It is the third most spoken language in Africa. I am making a case for why we need this article translated into Hausa. It is my native language and I can help with the translation if assigned to do it.

**Comment by jancris100** [comment]
Hi can you assign Germany translation to me ?

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
