### ISSUE TITLE
doc: translate Madara article and website to Hindi

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/madara#926]
# Feature Request
Translate this article: https://starknet-website-cms-posts-harnessing-the-beast-madara-an.yukilabs.workers.dev/en/posts/ecosystem/harnessing-the-beast-madara-and-the-revolution-of-starknet-appchains

Translate the website: madara.zone

**Comment by gryptoo** [comment]
👋 would like to do this

**Comment by abdelhamidbakhta** [comment]
> 👋 would like to do this

let's go, thank you!

**Comment by Enenche23** [comment]
Am interested in this task, I would love to do this...

**Comment by abdelhamidbakhta** [comment]
> Am interested in this task, I would love to do this...

you are welcome to help @gryptoo

**Comment by Calebux** [comment]
Can i work with them on this?

**Comment by Enenche23** [comment]
please let's talk on Discord  @gryptoo

**Comment by Enenche23** [comment]
NIce @Calebux if you get assigned we can start working on it Asap my discord is @.chriselias

**Comment by gryptoo** [comment]
Sure thing, please reach out to me on discord @gryptooo

**Comment by Enenche23** [comment]
please i have mistakenly unassigned myself @abdelhamidbakhta could you please reassign me?

**Comment by Enenche23** [comment]
good afternoon @abdelhamidbakhta

**Comment by Enenche23** [comment]
could I still submit the pull request for the translation to Hindi? @abdelhamidbakhta
