### ISSUE TITLE
doc:  translate Madara article to Russian

### ISSUE THREAD

**Issue by gylman** [keep-starknet-strange/madara#929]
# Feature Request

Translate this article: https://starknet-website-cms-posts-harnessing-the-beast-madara-an.yukilabs.workers.dev/en/posts/ecosystem/harnessing-the-beast-madara-and-the-revolution-of-starknet-appchains

**Comment by gylman** [comment]
cannot add 'translation' label

**Comment by gylman** [comment]
what is the format of submission?

**Comment by abdelhamidbakhta** [comment]
> cannot add 'translation' label

Done

**Comment by abdelhamidbakhta** [comment]
> what is the format of submission?

Markdown

**Comment by gylman** [comment]
Is there a sample, a Markdown in english, where exact fields have to be replaced by translations? Otherwise, if everyone makes their own markdown, there is a high chance there will be differences, misses, additions, which would make it hard to automate making translated web pages?

**Comment by gylman** [comment]
And please assign me

**Comment by abdelhamidbakhta** [comment]
> Is there a sample, a Markdown in english, where exact fields have to be replaced by translations? Otherwise, if everyone makes their own markdown, there is a high chance there will be differences, misses, additions, which would make it hard to automate making translated web pages?

very good point, we need to create a markdown reference in english corresponding to the article. @welttowelt can you do it and put it in `docs/content/artciles/en` ?

**Comment by abdelhamidbakhta** [comment]
> And please assign me

assigned to you

**Comment by welttowelt** [comment]
> > Is there a sample, a Markdown in english, where exact fields have to be replaced by translations? Otherwise, if everyone makes their own markdown, there is a high chance there will be differences, misses, additions, which would make it hard to automate making translated web pages?
> 
> very good point, we need to create a markdown reference in english corresponding to the article. @welttowelt can you do it and put it in `docs/content/artciles/en` ?

done pls check

**Comment by abdelhamidbakhta** [comment]
> > > Is there a sample, a Markdown in english, where exact fields have to be replaced by translations? Otherwise, if everyone makes their own markdown, there is a high chance there will be differences, misses, additions, which would make it hard to automate making translated web pages?
> > 
> > 
> > very good point, we need to create a markdown reference in english corresponding to the article. @welttowelt can you do it and put it in `docs/content/artciles/en` ?
> 
> done pls check

Where bro ?

**Comment by welttowelt** [comment]
https://github.com/keep-starknet-strange/madara/pull/932

**Comment by abdelhamidbakhta** [comment]
> #932

ah thanks bro
