### ISSUE TITLE
dev: add a CHANGELOG.md file 

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#931]
Add a CHANGELOG.md file and make sure, in the CI,  it has been updated for every PR on main

**Comment by Tidus91** [comment]
Hey, i'm ok to do this one

**Comment by d-roak** [comment]
@Tidus91 let's add it within the pull-request.yml workflow. Also it should not be enforced, we can take the PR title to auto-fill

You can take a look into this action: https://github.com/marketplace/actions/changelog-ci

**Comment by d-roak** [comment]
If u want to drop it, just let us know. I'll pick it up

**Comment by tdelabro** [comment]
I think you can take over it @d-roak, @Tidus91 is working on tests now

**Comment by tdelabro** [comment]
> Also it should not be enforced, we can take the PR title to auto-fill

I would rather prefer the manual change of CHANGELOG being enforced. I think it will end up with better, more precise, more extensive logs. Don't you think?

**Comment by d-roak** [comment]
![image](https://github.com/keep-starknet-strange/madara/assets/5263301/d4a27eb5-51c6-474c-98a4-550d00605747)
I think this one can be discussed in the official tg group
