### ISSUE TITLE
dev: add LRU cache layer to block fetching client-side

### ISSUE THREAD

**Issue by EvolveArt** [keep-starknet-strange/madara#947]
```rust
/// Manage LRU caches for block data and their transaction statuses.
/// These are large and take a lot of time to fetch from the database.
/// Storing them in an LRU cache will allow to reduce database accesses
/// when many subsequent requests are related to the same blocks.
pub struct EthBlockDataCacheTask<B: BlockT>(mpsc::Sender<EthBlockDataCacheMessage<B>>);
```

This code was taken from [frontier](https://github.com/paritytech/frontier/blob/194f6bb06152402ba44b340c3d401ae6e0670d96/client/rpc/src/eth/cache/mod.rs#L76) and is extensively used on their RPC layer. We should investigate adding this on our side and evaluate the performance gain using https://github.com/keep-starknet-strange/gomu-gomu-no-gatling

**Comment by tchataigner** [comment]
As @tdelabro pointed me to this issue I can try to work on this for our RPC layer. Would be glad to try out performance testing as well.

**Comment by tdelabro** [comment]
Yes sure. Try to draw inspiration from the frontier impl: https://github.com/paritytech/frontier

**Comment by tchataigner** [comment]
Hey ! Sorry for not giving news before today, was taken out by a bad cold. 

I have been wondering about a detail in the cache implementation which I think is still important to determine. In frontier implementation we can see that they have a `max_size` parameter which limits the cache total stored size to a given threshold.

However, this implementation has one flaw I think, it only looks at stored values size and not at the allocated size (e.g.: for a value `"a"`, value size: 1 byte, allocated size: 148 bytes). In the context of P2P networks and precise memory management, I was wondering if I should:
1. Keep the same memory management as frontier, which is imprecise but will allow for more values to be stored.
2. Change the memory management to allocated memory, allowing for more precise memory predictability. 
3. Have a middle ground where either or both could be selected.

Eager to get your take on that :raised_hands:

**Comment by tdelabro** [comment]
I think in the first time you can go with the easier one.
And then if it's not too difficult switch to the second one which is more precise.

**Comment by tdelabro** [comment]
@tchataigner has been working on l1-l2 messaging recently.
If someone want to take the work for this issue where he left it, it would be great

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
