### ISSUE TITLE
dev: clean node and mock genesis state

### ISSUE THREAD

**Issue by greged93** [keep-starknet-strange/madara#951]
The current node genesis as well as the mock genesis used for testing in the starknet pallet contain incorrect contract addresses and class hashes. The PR should:
- Compute the correct class hashes for all contracts as well as the correct contract addresses.
- Update all values in the genesis for the node and the mocking.

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
