### ISSUE TITLE
bug: max steps limit doesn't work (rebase needed)

### ISSUE THREAD

**Issue by apoorvsadana** [keep-starknet-strange/madara#956]
Currently, Madara doesn't obey the max steps limit of Starknet. This mostly happens because of this code in the blockifier - https://github.com/keep-starknet-strange/blockifier/blob/15c81976e72f76ab7b5b19e68b597f9ae583dcd8/crates/blockifier/src/execution/cairo1_execution.rs#L225

This has already been fixed on the prod version of the blockifier. I beleive there might be more issues that might exist in Madara because our blockifier is based on an older version. Hence, I think we should now rebase our blockifier.

**Comment by apoorvsadana** [comment]
@abdelhamidbakhta you can assign this to me to avoid some one else picking it up

**Comment by lana-shanghai** [comment]
> @abdelhamidbakhta you can assign this to me to avoid some one else picking it up

Done! :)

**Comment by apoorvsadana** [comment]
fixed with #993
