### ISSUE TITLE
spike: performance - measurements, investigate recent inconsistencies, ci enforcements, plan for performance optimisations

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/madara#977]
### Description

There have been recent inconsistencies in the performance benchmarks of Madara. This issue aims to investigate these inconsistencies, ensure consistent performance measurements, enforce stricter CI rules regarding performance, and define a plan for future performance optimisations.

### Tasks

1. **Track Changes**: Review the latest changes made to the project and determine their impact on performance.
2. **Consistent Measurements**: Ensure that our performance measurement approach is consistent. One potential method is to measure performance 10 times with the exact same codebase and check for consistency in the results.
3. **CI Enforcements**: Implement stricter rules regarding performance evolution. Consider blocking the CI with a lower tolerance rate than our current threshold. However, before implementing this, we must ensure that our performance results are consistent.
4. **Performance Optimisation Plan**: Define a clear and actionable plan for performance optimisations in Madara.
5. **Issue Breakdown**: This overarching issue should be divided into multiple smaller issues, each with specific action items.

### Resources

- [Madara Benchmark Page](https://keep-starknet-strange.github.io/madara/dev/bench/)

**Comment by tdelabro** [comment]
repository archived in favor of https://github.com/madara-alliance/madara
