### ISSUE TITLE
bug: Events not emited in correct order when call to other contracts

### ISSUE THREAD

**Issue by tdelabro** [keep-starknet-strange/madara#985]
By reading the code, I'm pretty sure we don't emit the event in the correct order when a contract call another one.

## Problem
Here is an example of flow:

tx call contract1
 - event 1 is emitted
 -contract1 call contract2:
     -event 2 is emitted
 - event 3 is emitted

 What we expect:
 the event should be emitted in the following order: 1, 2, 3
 
 What is happening:
 event are emitted in this order: 1, 3, 2
 
 ## What to do:
 
 1) Write test to prove my point. Related to: #648
 2) Fix it
 
 ### How to fix
 
 ```rust
pub struct OrderedEvent {
    pub order: usize,
    pub event: EventContent,
}
```
 
 Events are emitted after tx execution by reading the returned `CallInfo` struct. It contains a `CallExecution` struct that contains a `Vec<OrderedEvent>`. All the events in this vec are guaranteed to be in ascending order. But they are not necessarily contiguous. Going back to our example it will look like this `[event1, event3]`, while `event2` is stored in another `CallInfo` in the field `inner_calls`.
 
 Rather than first emitting all current `CallInfo` events and then recursively iterating over the `inner_calls`, we should read all of them at the same time and order them.
 
 Two possible implems:
 1) visit all `CallInfo` and store their events in a single vec and then order by their field `order`. The drawback is allocation/reallocation, vec sorting and another extra iteration to then emit the events.
 2) visit all `CallInfo`, keep a trace of their vec of events somewhere, and use those pointers to emit them in the correct order. Advantages: no allocation.

**Comment by m-kus** [comment]
I can take this one, it is related to my work on transaction/block traces
